import Foundation

// Fourth translation table (Localizer checks all four). Covers Vault + passcode +
// lock screens, Paywall, the success screens, Quick Clean flow, and preview badges.
enum LocalizedStrings4 {
    static let table: [String: [String: String]] = [
        "en": en, "es": es, "pt": pt, "fr": fr, "de": de, "it": it, "nl": nl,
        "tr": tr, "uk": uk, "ru": ru, "he": he, "ar": ar, "fa": fa, "id": id,
        "vi": vi, "ja": ja, "ko": ko, "zh-Hans": zhHans, "zh-Hant": zhHant,
    ]

    private static let en: [String: String] = [
        "vault.title": "Private Vault", "vault.addMore": "Add More", "vault.addToVault": "Add to Vault",
        "vault.addCamera": "Add from Camera", "vault.addPhotos": "Add from Photos",
        "vault.importError": "Couldn’t import", "vault.emptyTitle": "No private photos yet",
        "vault.emptyBody": "Tap Add More to bring photos here.\nThey’re encrypted AES-256 on this device only.",
        "vault.encrypting": "Encrypting…", "vault.deleteItemTitle": "Delete this item?",
        "vault.deleteItemBody": "This permanently removes the encrypted copy from your vault.",
        "vault.decryptFailTitle": "Decryption failed", "vault.decryptFailBody": "Couldn’t decrypt this file. It may be corrupted.",
        "vault.aes": "AES-256 Encrypted", "vault.share": "Share",
        "vault.lockedTitle": "Private Vault is\nLocked", "vault.lockedBody": "Your photos are encrypted and\nprotected.",
        "vault.unlockFaceID": "Unlock with %@", "vault.authFailTitle": "Couldn’t authenticate",
        "vault.unlockReason": "Unlock your private vault",
        "passcode.create": "Create a Passcode", "passcode.reenter": "Re-enter Passcode",
        "passcode.createSub": "Choose a 6-digit code to protect\nyour private vault.",
        "passcode.confirmSub": "Enter the same 6 digits again to\nconfirm your new passcode.",
        "passcode.mismatch": "Codes don’t match — start over", "passcode.saveErrorTitle": "Couldn’t save passcode",
        "passcode.saveErrorBody": "Failed to store passcode securely. Please try again.",
        "passcode.wrongCurrent": "That passcode doesn’t match — try again", "passcode.saveError2Title": "Couldn’t save",
        "passcode.saveError2Body": "Failed to save new passcode. Please try again.",
        "passcode.changeTitle": "Change Passcode", "passcode.newTitle": "New Passcode",
        "passcode.verifySub": "Enter your current 6-digit passcode to\nverify your identity.",
        "passcode.newSub": "Choose a new 6-digit code for your\nprivate vault.",
        "passcode.usePasscode": "Use Passcode", "passcode.enterTitle": "Enter Passcode", "passcode.wrong": "Wrong passcode — try again",
        "paywall.unlockStorage": "Unlock More Storage", "paywall.enableTrial": "Enable Free Trial",
        "paywall.purchaseFailTitle": "Purchase failed", "paywall.restore": "Restore",
        "paywall.subtitle": "Keep what you want, remove the unnecessary!", "paywall.photos": "Photos", "paywall.drive": "Drive",
        "paywall.of": " of ", "paywall.used": " used", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "Premium",
        "paywall.features": "Smart Cleaning, VideoCompressor, No Limits.", "paywall.perWeek": "/week",
        "paywall.monthly": "Monthly", "paywall.monthlyDesc": "Full access, cancel anytime", "paywall.continue": "Continue",
        "paywall.terms": "Terms of Use", "paywall.privacy": "Privacy Policy",
        "paywall.unavailable": "Subscription product unavailable", "paywall.noRestore": "No purchases to restore.",
        "success.congrats": "Congratulations!", "success.junkRemoved": "Junk Files Removed", "success.perfect": "Perfect!",
        "success.cleaned": "Cleaned", "success.photosOptimized": "Photos Optimized", "success.memoryBoosted": "Memory Boosted",
        "success.totalCleaned": "Total Cleaned", "success.junkRemoved2": "Junk Removed",
        "quickclean.cleaning": "Cleaning your phone...", "quickclean.scanning": "Scanning for similar photos…",
        "quickclean.permBody": "The app needs access to your photo library to scan for cleanup.",
        "quickclean.emptyTitle": "Already squeaky clean", "quickclean.emptyBody": "We didn’t find any similar photos to clean right now.",
        "cleaning.deleting": "Deleting Selected photos...", "deleteconfirm.title": "Delete %d Photos?",
        "deleteconfirm.body": "These %@ of photos will be\npermanently removed.",
        "preview.delete": "DELETE", "preview.keep": "KEEP",
    ]

    private static let es: [String: String] = [
        "vault.title": "Bóveda privada", "vault.addMore": "Añadir más", "vault.addToVault": "Añadir a la bóveda",
        "vault.addCamera": "Añadir desde la cámara", "vault.addPhotos": "Añadir desde Fotos",
        "vault.importError": "No se pudo importar", "vault.emptyTitle": "Aún no hay fotos privadas",
        "vault.emptyBody": "Toca Añadir más para traer fotos aquí.\nSe cifran con AES-256 solo en este dispositivo.",
        "vault.encrypting": "Cifrando…", "vault.deleteItemTitle": "¿Eliminar este elemento?",
        "vault.deleteItemBody": "Esto elimina permanentemente la copia cifrada de tu bóveda.",
        "vault.decryptFailTitle": "Fallo al descifrar", "vault.decryptFailBody": "No se pudo descifrar este archivo. Puede estar dañado.",
        "vault.aes": "Cifrado AES-256", "vault.share": "Compartir",
        "vault.lockedTitle": "La bóveda privada\nestá bloqueada", "vault.lockedBody": "Tus fotos están cifradas y\nprotegidas.",
        "vault.unlockFaceID": "Desbloquear con %@", "vault.authFailTitle": "No se pudo autenticar",
        "vault.unlockReason": "Desbloquea tu bóveda privada",
        "passcode.create": "Crear un código", "passcode.reenter": "Repetir el código",
        "passcode.createSub": "Elige un código de 6 dígitos para\nproteger tu bóveda privada.",
        "passcode.confirmSub": "Vuelve a escribir los 6 dígitos para\nconfirmar tu nuevo código.",
        "passcode.mismatch": "Los códigos no coinciden — empieza de nuevo", "passcode.saveErrorTitle": "No se pudo guardar el código",
        "passcode.saveErrorBody": "No se pudo guardar el código de forma segura. Inténtalo de nuevo.",
        "passcode.wrongCurrent": "Ese código no coincide — inténtalo de nuevo", "passcode.saveError2Title": "No se pudo guardar",
        "passcode.saveError2Body": "No se pudo guardar el nuevo código. Inténtalo de nuevo.",
        "passcode.changeTitle": "Cambiar código", "passcode.newTitle": "Nuevo código",
        "passcode.verifySub": "Escribe tu código actual de 6 dígitos\npara verificar tu identidad.",
        "passcode.newSub": "Elige un nuevo código de 6 dígitos\npara tu bóveda privada.",
        "passcode.usePasscode": "Usar código", "passcode.enterTitle": "Introduce el código", "passcode.wrong": "Código incorrecto — inténtalo de nuevo",
        "paywall.unlockStorage": "Libera más espacio", "paywall.enableTrial": "Activar prueba gratis",
        "paywall.purchaseFailTitle": "Compra fallida", "paywall.restore": "Restaurar",
        "paywall.subtitle": "¡Conserva lo que quieras, elimina lo innecesario!", "paywall.photos": "Fotos", "paywall.drive": "Drive",
        "paywall.of": " de ", "paywall.used": " usados", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "Premium",
        "paywall.features": "Limpieza inteligente, compresor de video, sin límites.", "paywall.perWeek": "/semana",
        "paywall.monthly": "Mensual", "paywall.monthlyDesc": "Acceso completo, cancela cuando quieras", "paywall.continue": "Continuar",
        "paywall.terms": "Términos de uso", "paywall.privacy": "Política de privacidad",
        "paywall.unavailable": "Producto de suscripción no disponible", "paywall.noRestore": "No hay compras que restaurar.",
        "success.congrats": "¡Felicidades!", "success.junkRemoved": "Archivos basura eliminados", "success.perfect": "¡Perfecto!",
        "success.cleaned": "Limpiado", "success.photosOptimized": "Fotos optimizadas", "success.memoryBoosted": "Memoria liberada",
        "success.totalCleaned": "Total limpiado", "success.junkRemoved2": "Basura eliminada",
        "quickclean.cleaning": "Limpiando tu teléfono...", "quickclean.scanning": "Buscando fotos similares…",
        "quickclean.permBody": "La app necesita acceso a tu fototeca para buscar elementos que limpiar.",
        "quickclean.emptyTitle": "Ya está impecable", "quickclean.emptyBody": "No encontramos fotos similares para limpiar ahora.",
        "cleaning.deleting": "Eliminando las fotos seleccionadas...", "deleteconfirm.title": "¿Eliminar %d fotos?",
        "deleteconfirm.body": "Estos %@ de fotos se eliminarán\nde forma permanente.",
        "preview.delete": "ELIMINAR", "preview.keep": "CONSERVAR",
    ]

    private static let pt: [String: String] = [
        "vault.title": "Cofre privado", "vault.addMore": "Adicionar mais", "vault.addToVault": "Adicionar ao cofre",
        "vault.addCamera": "Adicionar da câmera", "vault.addPhotos": "Adicionar das Fotos",
        "vault.importError": "Não foi possível importar", "vault.emptyTitle": "Ainda sem fotos privadas",
        "vault.emptyBody": "Toque em Adicionar mais para trazer fotos aqui.\nSão criptografadas com AES-256 só neste dispositivo.",
        "vault.encrypting": "Criptografando…", "vault.deleteItemTitle": "Excluir este item?",
        "vault.deleteItemBody": "Isto remove permanentemente a cópia criptografada do seu cofre.",
        "vault.decryptFailTitle": "Falha ao descriptografar", "vault.decryptFailBody": "Não foi possível descriptografar este arquivo. Ele pode estar corrompido.",
        "vault.aes": "Criptografia AES-256", "vault.share": "Compartilhar",
        "vault.lockedTitle": "O cofre privado\nestá bloqueado", "vault.lockedBody": "Suas fotos estão criptografadas e\nprotegidas.",
        "vault.unlockFaceID": "Desbloquear com %@", "vault.authFailTitle": "Falha na autenticação",
        "vault.unlockReason": "Desbloqueie seu cofre privado",
        "passcode.create": "Criar uma senha", "passcode.reenter": "Repetir a senha",
        "passcode.createSub": "Escolha um código de 6 dígitos para\nproteger seu cofre privado.",
        "passcode.confirmSub": "Digite os mesmos 6 dígitos novamente\npara confirmar sua nova senha.",
        "passcode.mismatch": "Os códigos não coincidem — recomece", "passcode.saveErrorTitle": "Não foi possível salvar a senha",
        "passcode.saveErrorBody": "Falha ao salvar a senha com segurança. Tente novamente.",
        "passcode.wrongCurrent": "Essa senha não coincide — tente de novo", "passcode.saveError2Title": "Não foi possível salvar",
        "passcode.saveError2Body": "Falha ao salvar a nova senha. Tente novamente.",
        "passcode.changeTitle": "Alterar senha", "passcode.newTitle": "Nova senha",
        "passcode.verifySub": "Digite sua senha atual de 6 dígitos\npara verificar sua identidade.",
        "passcode.newSub": "Escolha uma nova senha de 6 dígitos\npara seu cofre privado.",
        "passcode.usePasscode": "Usar senha", "passcode.enterTitle": "Digite a senha", "passcode.wrong": "Senha incorreta — tente de novo",
        "paywall.unlockStorage": "Libere mais espaço", "paywall.enableTrial": "Ativar teste grátis",
        "paywall.purchaseFailTitle": "Falha na compra", "paywall.restore": "Restaurar",
        "paywall.subtitle": "Guarde o que quiser, remova o desnecessário!", "paywall.photos": "Fotos", "paywall.drive": "Drive",
        "paywall.of": " de ", "paywall.used": " usados", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "Premium",
        "paywall.features": "Limpeza inteligente, compressor de vídeo, sem limites.", "paywall.perWeek": "/semana",
        "paywall.monthly": "Mensal", "paywall.monthlyDesc": "Acesso total, cancele quando quiser", "paywall.continue": "Continuar",
        "paywall.terms": "Termos de uso", "paywall.privacy": "Política de privacidade",
        "paywall.unavailable": "Produto de assinatura indisponível", "paywall.noRestore": "Nenhuma compra para restaurar.",
        "success.congrats": "Parabéns!", "success.junkRemoved": "Arquivos inúteis removidos", "success.perfect": "Perfeito!",
        "success.cleaned": "Limpo", "success.photosOptimized": "Fotos otimizadas", "success.memoryBoosted": "Memória liberada",
        "success.totalCleaned": "Total limpo", "success.junkRemoved2": "Lixo removido",
        "quickclean.cleaning": "Limpando seu telefone...", "quickclean.scanning": "Procurando fotos semelhantes…",
        "quickclean.permBody": "O app precisa de acesso à sua fototeca para procurar o que limpar.",
        "quickclean.emptyTitle": "Já está impecável", "quickclean.emptyBody": "Não encontramos fotos semelhantes para limpar agora.",
        "cleaning.deleting": "Excluindo as fotos selecionadas...", "deleteconfirm.title": "Excluir %d fotos?",
        "deleteconfirm.body": "Estes %@ de fotos serão\nremovidos permanentemente.",
        "preview.delete": "EXCLUIR", "preview.keep": "MANTER",
    ]

    private static let fr: [String: String] = [
        "vault.title": "Coffre privé", "vault.addMore": "Ajouter", "vault.addToVault": "Ajouter au coffre",
        "vault.addCamera": "Ajouter depuis l’appareil photo", "vault.addPhotos": "Ajouter depuis Photos",
        "vault.importError": "Importation impossible", "vault.emptyTitle": "Aucune photo privée",
        "vault.emptyBody": "Touchez Ajouter pour importer des photos ici.\nElles sont chiffrées AES-256 sur cet appareil uniquement.",
        "vault.encrypting": "Chiffrement…", "vault.deleteItemTitle": "Supprimer cet élément ?",
        "vault.deleteItemBody": "Cela supprime définitivement la copie chiffrée de votre coffre.",
        "vault.decryptFailTitle": "Échec du déchiffrement", "vault.decryptFailBody": "Impossible de déchiffrer ce fichier. Il est peut-être corrompu.",
        "vault.aes": "Chiffré AES-256", "vault.share": "Partager",
        "vault.lockedTitle": "Le coffre privé\nest verrouillé", "vault.lockedBody": "Vos photos sont chiffrées et\nprotégées.",
        "vault.unlockFaceID": "Déverrouiller avec %@", "vault.authFailTitle": "Échec de l’authentification",
        "vault.unlockReason": "Déverrouillez votre coffre privé",
        "passcode.create": "Créer un code", "passcode.reenter": "Ressaisir le code",
        "passcode.createSub": "Choisissez un code à 6 chiffres pour\nprotéger votre coffre privé.",
        "passcode.confirmSub": "Saisissez à nouveau les 6 chiffres pour\nconfirmer votre nouveau code.",
        "passcode.mismatch": "Les codes ne correspondent pas — recommencez", "passcode.saveErrorTitle": "Impossible d’enregistrer le code",
        "passcode.saveErrorBody": "Échec de l’enregistrement sécurisé du code. Réessayez.",
        "passcode.wrongCurrent": "Ce code ne correspond pas — réessayez", "passcode.saveError2Title": "Enregistrement impossible",
        "passcode.saveError2Body": "Échec de l’enregistrement du nouveau code. Réessayez.",
        "passcode.changeTitle": "Changer le code", "passcode.newTitle": "Nouveau code",
        "passcode.verifySub": "Saisissez votre code actuel à 6 chiffres\npour vérifier votre identité.",
        "passcode.newSub": "Choisissez un nouveau code à 6 chiffres\npour votre coffre privé.",
        "passcode.usePasscode": "Utiliser le code", "passcode.enterTitle": "Saisir le code", "passcode.wrong": "Code incorrect — réessayez",
        "paywall.unlockStorage": "Libérez plus d’espace", "paywall.enableTrial": "Activer l’essai gratuit",
        "paywall.purchaseFailTitle": "Échec de l’achat", "paywall.restore": "Restaurer",
        "paywall.subtitle": "Gardez ce que vous voulez, supprimez le superflu !", "paywall.photos": "Photos", "paywall.drive": "Drive",
        "paywall.of": " sur ", "paywall.used": " utilisés", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "Premium",
        "paywall.features": "Nettoyage intelligent, compresseur vidéo, sans limites.", "paywall.perWeek": "/semaine",
        "paywall.monthly": "Mensuel", "paywall.monthlyDesc": "Accès complet, annulez à tout moment", "paywall.continue": "Continuer",
        "paywall.terms": "Conditions d’utilisation", "paywall.privacy": "Politique de confidentialité",
        "paywall.unavailable": "Produit d’abonnement indisponible", "paywall.noRestore": "Aucun achat à restaurer.",
        "success.congrats": "Félicitations !", "success.junkRemoved": "Fichiers inutiles supprimés", "success.perfect": "Parfait !",
        "success.cleaned": "Nettoyé", "success.photosOptimized": "Photos optimisées", "success.memoryBoosted": "Mémoire libérée",
        "success.totalCleaned": "Total nettoyé", "success.junkRemoved2": "Déchets supprimés",
        "quickclean.cleaning": "Nettoyage de votre téléphone...", "quickclean.scanning": "Recherche de photos similaires…",
        "quickclean.permBody": "L’app a besoin d’accéder à votre photothèque pour rechercher des éléments à nettoyer.",
        "quickclean.emptyTitle": "Déjà impeccable", "quickclean.emptyBody": "Nous n’avons trouvé aucune photo similaire à nettoyer pour le moment.",
        "cleaning.deleting": "Suppression des photos sélectionnées...", "deleteconfirm.title": "Supprimer %d photos ?",
        "deleteconfirm.body": "Ces %@ de photos seront\nsupprimées définitivement.",
        "preview.delete": "SUPPRIMER", "preview.keep": "GARDER",
    ]

    private static let de: [String: String] = [
        "vault.title": "Privater Tresor", "vault.addMore": "Hinzufügen", "vault.addToVault": "Zum Tresor hinzufügen",
        "vault.addCamera": "Von Kamera hinzufügen", "vault.addPhotos": "Aus Fotos hinzufügen",
        "vault.importError": "Import fehlgeschlagen", "vault.emptyTitle": "Noch keine privaten Fotos",
        "vault.emptyBody": "Tippe auf Hinzufügen, um Fotos hierher zu holen.\nSie werden mit AES-256 nur auf diesem Gerät verschlüsselt.",
        "vault.encrypting": "Verschlüsseln…", "vault.deleteItemTitle": "Dieses Element löschen?",
        "vault.deleteItemBody": "Dies entfernt die verschlüsselte Kopie dauerhaft aus deinem Tresor.",
        "vault.decryptFailTitle": "Entschlüsselung fehlgeschlagen", "vault.decryptFailBody": "Diese Datei konnte nicht entschlüsselt werden. Sie ist möglicherweise beschädigt.",
        "vault.aes": "AES-256 verschlüsselt", "vault.share": "Teilen",
        "vault.lockedTitle": "Privater Tresor ist\ngesperrt", "vault.lockedBody": "Deine Fotos sind verschlüsselt und\ngeschützt.",
        "vault.unlockFaceID": "Mit %@ entsperren", "vault.authFailTitle": "Authentifizierung fehlgeschlagen",
        "vault.unlockReason": "Entsperre deinen privaten Tresor",
        "passcode.create": "Code erstellen", "passcode.reenter": "Code erneut eingeben",
        "passcode.createSub": "Wähle einen 6-stelligen Code, um\ndeinen privaten Tresor zu schützen.",
        "passcode.confirmSub": "Gib dieselben 6 Ziffern erneut ein,\num deinen neuen Code zu bestätigen.",
        "passcode.mismatch": "Codes stimmen nicht überein — von vorn", "passcode.saveErrorTitle": "Code konnte nicht gespeichert werden",
        "passcode.saveErrorBody": "Code konnte nicht sicher gespeichert werden. Bitte erneut versuchen.",
        "passcode.wrongCurrent": "Dieser Code stimmt nicht — erneut versuchen", "passcode.saveError2Title": "Speichern fehlgeschlagen",
        "passcode.saveError2Body": "Neuer Code konnte nicht gespeichert werden. Bitte erneut versuchen.",
        "passcode.changeTitle": "Code ändern", "passcode.newTitle": "Neuer Code",
        "passcode.verifySub": "Gib deinen aktuellen 6-stelligen Code ein,\num deine Identität zu bestätigen.",
        "passcode.newSub": "Wähle einen neuen 6-stelligen Code\nfür deinen privaten Tresor.",
        "passcode.usePasscode": "Code verwenden", "passcode.enterTitle": "Code eingeben", "passcode.wrong": "Falscher Code — erneut versuchen",
        "paywall.unlockStorage": "Mehr Speicher freischalten", "paywall.enableTrial": "Gratis-Test aktivieren",
        "paywall.purchaseFailTitle": "Kauf fehlgeschlagen", "paywall.restore": "Wiederherstellen",
        "paywall.subtitle": "Behalte, was du willst, entferne den Rest!", "paywall.photos": "Fotos", "paywall.drive": "Drive",
        "paywall.of": " von ", "paywall.used": " belegt", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "Premium",
        "paywall.features": "Smarte Reinigung, Videokompressor, keine Limits.", "paywall.perWeek": "/Woche",
        "paywall.monthly": "Monatlich", "paywall.monthlyDesc": "Voller Zugriff, jederzeit kündbar", "paywall.continue": "Weiter",
        "paywall.terms": "Nutzungsbedingungen", "paywall.privacy": "Datenschutzrichtlinie",
        "paywall.unavailable": "Abo-Produkt nicht verfügbar", "paywall.noRestore": "Keine Käufe zum Wiederherstellen.",
        "success.congrats": "Glückwunsch!", "success.junkRemoved": "Datenmüll entfernt", "success.perfect": "Perfekt!",
        "success.cleaned": "Bereinigt", "success.photosOptimized": "Fotos optimiert", "success.memoryBoosted": "Speicher freigegeben",
        "success.totalCleaned": "Gesamt bereinigt", "success.junkRemoved2": "Müll entfernt",
        "quickclean.cleaning": "Dein Telefon wird bereinigt...", "quickclean.scanning": "Suche nach ähnlichen Fotos…",
        "quickclean.permBody": "Die App benötigt Zugriff auf deine Fotomediathek, um nach Aufräumbarem zu suchen.",
        "quickclean.emptyTitle": "Schon blitzsauber", "quickclean.emptyBody": "Wir haben gerade keine ähnlichen Fotos zum Aufräumen gefunden.",
        "cleaning.deleting": "Ausgewählte Fotos werden gelöscht...", "deleteconfirm.title": "%d Fotos löschen?",
        "deleteconfirm.body": "Diese %@ an Fotos werden\ndauerhaft entfernt.",
        "preview.delete": "LÖSCHEN", "preview.keep": "BEHALTEN",
    ]

    private static let it: [String: String] = [
        "vault.title": "Cassaforte privata", "vault.addMore": "Aggiungi", "vault.addToVault": "Aggiungi alla cassaforte",
        "vault.addCamera": "Aggiungi da fotocamera", "vault.addPhotos": "Aggiungi da Foto",
        "vault.importError": "Importazione non riuscita", "vault.emptyTitle": "Ancora nessuna foto privata",
        "vault.emptyBody": "Tocca Aggiungi per portare qui le foto.\nVengono cifrate AES-256 solo su questo dispositivo.",
        "vault.encrypting": "Cifratura…", "vault.deleteItemTitle": "Eliminare questo elemento?",
        "vault.deleteItemBody": "Questo rimuove definitivamente la copia cifrata dalla tua cassaforte.",
        "vault.decryptFailTitle": "Decifratura non riuscita", "vault.decryptFailBody": "Impossibile decifrare questo file. Potrebbe essere danneggiato.",
        "vault.aes": "Cifrato AES-256", "vault.share": "Condividi",
        "vault.lockedTitle": "La cassaforte privata\nè bloccata", "vault.lockedBody": "Le tue foto sono cifrate e\nprotette.",
        "vault.unlockFaceID": "Sblocca con %@", "vault.authFailTitle": "Autenticazione non riuscita",
        "vault.unlockReason": "Sblocca la tua cassaforte privata",
        "passcode.create": "Crea un codice", "passcode.reenter": "Reinserisci il codice",
        "passcode.createSub": "Scegli un codice di 6 cifre per\nproteggere la tua cassaforte privata.",
        "passcode.confirmSub": "Inserisci di nuovo le stesse 6 cifre\nper confermare il nuovo codice.",
        "passcode.mismatch": "I codici non coincidono — ricomincia", "passcode.saveErrorTitle": "Impossibile salvare il codice",
        "passcode.saveErrorBody": "Impossibile salvare il codice in modo sicuro. Riprova.",
        "passcode.wrongCurrent": "Quel codice non coincide — riprova", "passcode.saveError2Title": "Salvataggio non riuscito",
        "passcode.saveError2Body": "Impossibile salvare il nuovo codice. Riprova.",
        "passcode.changeTitle": "Cambia codice", "passcode.newTitle": "Nuovo codice",
        "passcode.verifySub": "Inserisci il codice attuale di 6 cifre\nper verificare la tua identità.",
        "passcode.newSub": "Scegli un nuovo codice di 6 cifre\nper la tua cassaforte privata.",
        "passcode.usePasscode": "Usa codice", "passcode.enterTitle": "Inserisci il codice", "passcode.wrong": "Codice errato — riprova",
        "paywall.unlockStorage": "Libera più spazio", "paywall.enableTrial": "Attiva prova gratuita",
        "paywall.purchaseFailTitle": "Acquisto non riuscito", "paywall.restore": "Ripristina",
        "paywall.subtitle": "Tieni ciò che vuoi, rimuovi il superfluo!", "paywall.photos": "Foto", "paywall.drive": "Drive",
        "paywall.of": " di ", "paywall.used": " usati", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "Premium",
        "paywall.features": "Pulizia smart, compressore video, nessun limite.", "paywall.perWeek": "/settimana",
        "paywall.monthly": "Mensile", "paywall.monthlyDesc": "Accesso completo, annulla quando vuoi", "paywall.continue": "Continua",
        "paywall.terms": "Termini d’uso", "paywall.privacy": "Informativa sulla privacy",
        "paywall.unavailable": "Prodotto in abbonamento non disponibile", "paywall.noRestore": "Nessun acquisto da ripristinare.",
        "success.congrats": "Congratulazioni!", "success.junkRemoved": "File inutili rimossi", "success.perfect": "Perfetto!",
        "success.cleaned": "Pulito", "success.photosOptimized": "Foto ottimizzate", "success.memoryBoosted": "Memoria liberata",
        "success.totalCleaned": "Totale pulito", "success.junkRemoved2": "Spazzatura rimossa",
        "quickclean.cleaning": "Pulizia del telefono...", "quickclean.scanning": "Ricerca di foto simili…",
        "quickclean.permBody": "L’app ha bisogno di accedere alla tua libreria foto per cercare cosa pulire.",
        "quickclean.emptyTitle": "Già pulitissimo", "quickclean.emptyBody": "Al momento non abbiamo trovato foto simili da pulire.",
        "cleaning.deleting": "Eliminazione delle foto selezionate...", "deleteconfirm.title": "Eliminare %d foto?",
        "deleteconfirm.body": "Questi %@ di foto verranno\nrimossi definitivamente.",
        "preview.delete": "ELIMINA", "preview.keep": "MANTIENI",
    ]

    private static let nl: [String: String] = [
        "vault.title": "Privékluis", "vault.addMore": "Meer toevoegen", "vault.addToVault": "Aan kluis toevoegen",
        "vault.addCamera": "Toevoegen via camera", "vault.addPhotos": "Toevoegen uit Foto’s",
        "vault.importError": "Importeren mislukt", "vault.emptyTitle": "Nog geen privéfoto’s",
        "vault.emptyBody": "Tik op Meer toevoegen om foto’s hierheen te halen.\nZe worden alleen op dit apparaat met AES-256 versleuteld.",
        "vault.encrypting": "Versleutelen…", "vault.deleteItemTitle": "Dit item verwijderen?",
        "vault.deleteItemBody": "Hiermee wordt de versleutelde kopie permanent uit je kluis verwijderd.",
        "vault.decryptFailTitle": "Ontsleutelen mislukt", "vault.decryptFailBody": "Kan dit bestand niet ontsleutelen. Het is mogelijk beschadigd.",
        "vault.aes": "AES-256 versleuteld", "vault.share": "Delen",
        "vault.lockedTitle": "Privékluis is\nvergrendeld", "vault.lockedBody": "Je foto’s zijn versleuteld en\nbeschermd.",
        "vault.unlockFaceID": "Ontgrendelen met %@", "vault.authFailTitle": "Verifiëren mislukt",
        "vault.unlockReason": "Ontgrendel je privékluis",
        "passcode.create": "Toegangscode maken", "passcode.reenter": "Code opnieuw invoeren",
        "passcode.createSub": "Kies een code van 6 cijfers om\nje privékluis te beschermen.",
        "passcode.confirmSub": "Voer dezelfde 6 cijfers opnieuw in om\nje nieuwe code te bevestigen.",
        "passcode.mismatch": "Codes komen niet overeen — begin opnieuw", "passcode.saveErrorTitle": "Code opslaan mislukt",
        "passcode.saveErrorBody": "Code kon niet veilig worden opgeslagen. Probeer opnieuw.",
        "passcode.wrongCurrent": "Die code klopt niet — probeer opnieuw", "passcode.saveError2Title": "Opslaan mislukt",
        "passcode.saveError2Body": "Nieuwe code kon niet worden opgeslagen. Probeer opnieuw.",
        "passcode.changeTitle": "Code wijzigen", "passcode.newTitle": "Nieuwe code",
        "passcode.verifySub": "Voer je huidige 6-cijferige code in om\nje identiteit te verifiëren.",
        "passcode.newSub": "Kies een nieuwe 6-cijferige code\nvoor je privékluis.",
        "passcode.usePasscode": "Code gebruiken", "passcode.enterTitle": "Voer code in", "passcode.wrong": "Verkeerde code — probeer opnieuw",
        "paywall.unlockStorage": "Ontgrendel meer opslag", "paywall.enableTrial": "Gratis proef activeren",
        "paywall.purchaseFailTitle": "Aankoop mislukt", "paywall.restore": "Herstellen",
        "paywall.subtitle": "Houd wat je wilt, verwijder het onnodige!", "paywall.photos": "Foto’s", "paywall.drive": "Drive",
        "paywall.of": " van ", "paywall.used": " gebruikt", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "Premium",
        "paywall.features": "Slim opschonen, videocompressor, geen limieten.", "paywall.perWeek": "/week",
        "paywall.monthly": "Maandelijks", "paywall.monthlyDesc": "Volledige toegang, altijd opzegbaar", "paywall.continue": "Doorgaan",
        "paywall.terms": "Gebruiksvoorwaarden", "paywall.privacy": "Privacybeleid",
        "paywall.unavailable": "Abonnementsproduct niet beschikbaar", "paywall.noRestore": "Geen aankopen om te herstellen.",
        "success.congrats": "Gefeliciteerd!", "success.junkRemoved": "Rommelbestanden verwijderd", "success.perfect": "Perfect!",
        "success.cleaned": "Opgeschoond", "success.photosOptimized": "Foto’s geoptimaliseerd", "success.memoryBoosted": "Geheugen vrijgemaakt",
        "success.totalCleaned": "Totaal opgeschoond", "success.junkRemoved2": "Rommel verwijderd",
        "quickclean.cleaning": "Je telefoon opschonen...", "quickclean.scanning": "Zoeken naar vergelijkbare foto’s…",
        "quickclean.permBody": "De app heeft toegang tot je fotobibliotheek nodig om op te ruimen.",
        "quickclean.emptyTitle": "Al brandschoon", "quickclean.emptyBody": "We hebben nu geen vergelijkbare foto’s gevonden om op te ruimen.",
        "cleaning.deleting": "Geselecteerde foto’s verwijderen...", "deleteconfirm.title": "%d foto’s verwijderen?",
        "deleteconfirm.body": "Deze %@ aan foto’s worden\npermanent verwijderd.",
        "preview.delete": "VERWIJDEREN", "preview.keep": "BEHOUDEN",
    ]

    private static let tr: [String: String] = [
        "vault.title": "Özel kasa", "vault.addMore": "Daha ekle", "vault.addToVault": "Kasaya ekle",
        "vault.addCamera": "Kameradan ekle", "vault.addPhotos": "Fotoğraflar’dan ekle",
        "vault.importError": "İçe aktarılamadı", "vault.emptyTitle": "Henüz özel fotoğraf yok",
        "vault.emptyBody": "Buraya fotoğraf getirmek için Daha ekle’ye dokun.\nYalnızca bu cihazda AES-256 ile şifrelenir.",
        "vault.encrypting": "Şifreleniyor…", "vault.deleteItemTitle": "Bu öğe silinsin mi?",
        "vault.deleteItemBody": "Bu işlem şifreli kopyayı kasandan kalıcı olarak kaldırır.",
        "vault.decryptFailTitle": "Şifre çözme başarısız", "vault.decryptFailBody": "Bu dosyanın şifresi çözülemedi. Bozuk olabilir.",
        "vault.aes": "AES-256 şifreli", "vault.share": "Paylaş",
        "vault.lockedTitle": "Özel kasa\nkilitli", "vault.lockedBody": "Fotoğrafların şifreli ve\nkorunuyor.",
        "vault.unlockFaceID": "%@ ile kilidi aç", "vault.authFailTitle": "Kimlik doğrulanamadı",
        "vault.unlockReason": "Özel kasanın kilidini aç",
        "passcode.create": "Parola oluştur", "passcode.reenter": "Parolayı yeniden gir",
        "passcode.createSub": "Özel kasanı korumak için\n6 haneli bir kod seç.",
        "passcode.confirmSub": "Yeni parolanı onaylamak için\naynı 6 haneyi tekrar gir.",
        "passcode.mismatch": "Kodlar eşleşmiyor — baştan başla", "passcode.saveErrorTitle": "Parola kaydedilemedi",
        "passcode.saveErrorBody": "Parola güvenli şekilde kaydedilemedi. Tekrar dene.",
        "passcode.wrongCurrent": "O parola eşleşmiyor — tekrar dene", "passcode.saveError2Title": "Kaydedilemedi",
        "passcode.saveError2Body": "Yeni parola kaydedilemedi. Tekrar dene.",
        "passcode.changeTitle": "Parolayı değiştir", "passcode.newTitle": "Yeni parola",
        "passcode.verifySub": "Kimliğini doğrulamak için mevcut\n6 haneli parolanı gir.",
        "passcode.newSub": "Özel kasan için yeni bir\n6 haneli kod seç.",
        "passcode.usePasscode": "Parola kullan", "passcode.enterTitle": "Parolayı gir", "passcode.wrong": "Yanlış parola — tekrar dene",
        "paywall.unlockStorage": "Daha fazla alan aç", "paywall.enableTrial": "Ücretsiz denemeyi etkinleştir",
        "paywall.purchaseFailTitle": "Satın alma başarısız", "paywall.restore": "Geri yükle",
        "paywall.subtitle": "İstediğini sakla, gereksizi kaldır!", "paywall.photos": "Fotoğraflar", "paywall.drive": "Drive",
        "paywall.of": " / ", "paywall.used": " kullanıldı", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "Premium",
        "paywall.features": "Akıllı temizlik, video sıkıştırıcı, sınır yok.", "paywall.perWeek": "/hafta",
        "paywall.monthly": "Aylık", "paywall.monthlyDesc": "Tam erişim, istediğin zaman iptal et", "paywall.continue": "Devam",
        "paywall.terms": "Kullanım koşulları", "paywall.privacy": "Gizlilik politikası",
        "paywall.unavailable": "Abonelik ürünü kullanılamıyor", "paywall.noRestore": "Geri yüklenecek satın alma yok.",
        "success.congrats": "Tebrikler!", "success.junkRemoved": "Gereksiz dosyalar silindi", "success.perfect": "Mükemmel!",
        "success.cleaned": "Temizlendi", "success.photosOptimized": "Fotoğraflar optimize edildi", "success.memoryBoosted": "Bellek boşaltıldı",
        "success.totalCleaned": "Toplam temizlenen", "success.junkRemoved2": "Gereksizler silindi",
        "quickclean.cleaning": "Telefonun temizleniyor...", "quickclean.scanning": "Benzer fotoğraflar aranıyor…",
        "quickclean.permBody": "Uygulamanın temizlenecekleri taraması için fotoğraf kitaplığına erişmesi gerekir.",
        "quickclean.emptyTitle": "Zaten tertemiz", "quickclean.emptyBody": "Şu anda temizlenecek benzer fotoğraf bulamadık.",
        "cleaning.deleting": "Seçili fotoğraflar siliniyor...", "deleteconfirm.title": "%d fotoğraf silinsin mi?",
        "deleteconfirm.body": "Bu %@ fotoğraf kalıcı olarak\nkaldırılacak.",
        "preview.delete": "SİL", "preview.keep": "TUT",
    ]

    private static let uk: [String: String] = [
        "vault.title": "Приватний сейф", "vault.addMore": "Додати ще", "vault.addToVault": "Додати в сейф",
        "vault.addCamera": "Додати з камери", "vault.addPhotos": "Додати з Фото",
        "vault.importError": "Не вдалося імпортувати", "vault.emptyTitle": "Ще немає приватних фото",
        "vault.emptyBody": "Торкніться Додати ще, щоб перенести фото сюди.\nВони шифруються AES-256 лише на цьому пристрої.",
        "vault.encrypting": "Шифрування…", "vault.deleteItemTitle": "Видалити цей елемент?",
        "vault.deleteItemBody": "Це назавжди видалить зашифровану копію з вашого сейфа.",
        "vault.decryptFailTitle": "Не вдалося розшифрувати", "vault.decryptFailBody": "Не вдалося розшифрувати цей файл. Можливо, він пошкоджений.",
        "vault.aes": "Шифрування AES-256", "vault.share": "Поділитися",
        "vault.lockedTitle": "Приватний сейф\nзаблоковано", "vault.lockedBody": "Ваші фото зашифровані та\nзахищені.",
        "vault.unlockFaceID": "Розблокувати через %@", "vault.authFailTitle": "Не вдалося автентифікувати",
        "vault.unlockReason": "Розблокуйте свій приватний сейф",
        "passcode.create": "Створити код", "passcode.reenter": "Введіть код ще раз",
        "passcode.createSub": "Виберіть 6-значний код, щоб\nзахистити свій приватний сейф.",
        "passcode.confirmSub": "Введіть ті самі 6 цифр ще раз,\nщоб підтвердити новий код.",
        "passcode.mismatch": "Коди не збігаються — почніть знову", "passcode.saveErrorTitle": "Не вдалося зберегти код",
        "passcode.saveErrorBody": "Не вдалося надійно зберегти код. Спробуйте ще раз.",
        "passcode.wrongCurrent": "Цей код не збігається — спробуйте ще", "passcode.saveError2Title": "Не вдалося зберегти",
        "passcode.saveError2Body": "Не вдалося зберегти новий код. Спробуйте ще раз.",
        "passcode.changeTitle": "Змінити код", "passcode.newTitle": "Новий код",
        "passcode.verifySub": "Введіть поточний 6-значний код,\nщоб підтвердити особу.",
        "passcode.newSub": "Виберіть новий 6-значний код\nдля свого приватного сейфа.",
        "passcode.usePasscode": "Використати код", "passcode.enterTitle": "Введіть код", "passcode.wrong": "Невірний код — спробуйте ще",
        "paywall.unlockStorage": "Відкрийте більше пам’яті", "paywall.enableTrial": "Увімкнути безкоштовну пробу",
        "paywall.purchaseFailTitle": "Помилка покупки", "paywall.restore": "Відновити",
        "paywall.subtitle": "Залиште потрібне, приберіть зайве!", "paywall.photos": "Фото", "paywall.drive": "Drive",
        "paywall.of": " з ", "paywall.used": " використано", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "Premium",
        "paywall.features": "Розумне очищення, стиснення відео, без обмежень.", "paywall.perWeek": "/тиждень",
        "paywall.monthly": "Щомісяця", "paywall.monthlyDesc": "Повний доступ, скасуйте будь-коли", "paywall.continue": "Продовжити",
        "paywall.terms": "Умови використання", "paywall.privacy": "Політика конфіденційності",
        "paywall.unavailable": "Продукт підписки недоступний", "paywall.noRestore": "Немає покупок для відновлення.",
        "success.congrats": "Вітаємо!", "success.junkRemoved": "Сміттєві файли видалено", "success.perfect": "Чудово!",
        "success.cleaned": "Очищено", "success.photosOptimized": "Фото оптимізовано", "success.memoryBoosted": "Пам’ять звільнено",
        "success.totalCleaned": "Усього очищено", "success.junkRemoved2": "Сміття видалено",
        "quickclean.cleaning": "Очищення вашого телефону...", "quickclean.scanning": "Пошук схожих фото…",
        "quickclean.permBody": "Застосунку потрібен доступ до фотобібліотеки, щоб знайти що очистити.",
        "quickclean.emptyTitle": "Уже бездоганно чисто", "quickclean.emptyBody": "Наразі ми не знайшли схожих фото для очищення.",
        "cleaning.deleting": "Видалення вибраних фото...", "deleteconfirm.title": "Видалити %d фото?",
        "deleteconfirm.body": "Ці %@ фото буде\nвидалено назавжди.",
        "preview.delete": "ВИДАЛИТИ", "preview.keep": "ЗАЛИШИТИ",
    ]

    private static let ru: [String: String] = [
        "vault.title": "Личный сейф", "vault.addMore": "Добавить ещё", "vault.addToVault": "Добавить в сейф",
        "vault.addCamera": "Добавить с камеры", "vault.addPhotos": "Добавить из Фото",
        "vault.importError": "Не удалось импортировать", "vault.emptyTitle": "Пока нет личных фото",
        "vault.emptyBody": "Нажмите Добавить ещё, чтобы перенести фото сюда.\nОни шифруются AES-256 только на этом устройстве.",
        "vault.encrypting": "Шифрование…", "vault.deleteItemTitle": "Удалить этот элемент?",
        "vault.deleteItemBody": "Это навсегда удалит зашифрованную копию из вашего сейфа.",
        "vault.decryptFailTitle": "Не удалось расшифровать", "vault.decryptFailBody": "Не удалось расшифровать этот файл. Возможно, он повреждён.",
        "vault.aes": "Шифрование AES-256", "vault.share": "Поделиться",
        "vault.lockedTitle": "Личный сейф\nзаблокирован", "vault.lockedBody": "Ваши фото зашифрованы и\nзащищены.",
        "vault.unlockFaceID": "Разблокировать через %@", "vault.authFailTitle": "Не удалось аутентифицировать",
        "vault.unlockReason": "Разблокируйте личный сейф",
        "passcode.create": "Создать код", "passcode.reenter": "Введите код ещё раз",
        "passcode.createSub": "Выберите 6-значный код, чтобы\nзащитить личный сейф.",
        "passcode.confirmSub": "Введите те же 6 цифр снова,\nчтобы подтвердить новый код.",
        "passcode.mismatch": "Коды не совпадают — начните заново", "passcode.saveErrorTitle": "Не удалось сохранить код",
        "passcode.saveErrorBody": "Не удалось безопасно сохранить код. Попробуйте снова.",
        "passcode.wrongCurrent": "Этот код не совпадает — попробуйте снова", "passcode.saveError2Title": "Не удалось сохранить",
        "passcode.saveError2Body": "Не удалось сохранить новый код. Попробуйте снова.",
        "passcode.changeTitle": "Изменить код", "passcode.newTitle": "Новый код",
        "passcode.verifySub": "Введите текущий 6-значный код,\nчтобы подтвердить личность.",
        "passcode.newSub": "Выберите новый 6-значный код\nдля личного сейфа.",
        "passcode.usePasscode": "Ввести код", "passcode.enterTitle": "Введите код", "passcode.wrong": "Неверный код — попробуйте снова",
        "paywall.unlockStorage": "Откройте больше памяти", "paywall.enableTrial": "Включить пробный период",
        "paywall.purchaseFailTitle": "Покупка не удалась", "paywall.restore": "Восстановить",
        "paywall.subtitle": "Оставьте нужное, удалите лишнее!", "paywall.photos": "Фото", "paywall.drive": "Drive",
        "paywall.of": " из ", "paywall.used": " использовано", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "Premium",
        "paywall.features": "Умная очистка, сжатие видео, без ограничений.", "paywall.perWeek": "/неделя",
        "paywall.monthly": "Ежемесячно", "paywall.monthlyDesc": "Полный доступ, отмена в любое время", "paywall.continue": "Продолжить",
        "paywall.terms": "Условия использования", "paywall.privacy": "Политика конфиденциальности",
        "paywall.unavailable": "Продукт подписки недоступен", "paywall.noRestore": "Нет покупок для восстановления.",
        "success.congrats": "Поздравляем!", "success.junkRemoved": "Мусорные файлы удалены", "success.perfect": "Отлично!",
        "success.cleaned": "Очищено", "success.photosOptimized": "Фото оптимизированы", "success.memoryBoosted": "Память освобождена",
        "success.totalCleaned": "Всего очищено", "success.junkRemoved2": "Мусор удалён",
        "quickclean.cleaning": "Очистка вашего телефона...", "quickclean.scanning": "Поиск похожих фото…",
        "quickclean.permBody": "Приложению нужен доступ к фотогалерее, чтобы найти, что очистить.",
        "quickclean.emptyTitle": "Уже идеально чисто", "quickclean.emptyBody": "Сейчас мы не нашли похожих фото для очистки.",
        "cleaning.deleting": "Удаление выбранных фото...", "deleteconfirm.title": "Удалить %d фото?",
        "deleteconfirm.body": "Эти %@ фото будут\nудалены навсегда.",
        "preview.delete": "УДАЛИТЬ", "preview.keep": "ОСТАВИТЬ",
    ]

    private static let he: [String: String] = [
        "vault.title": "כספת פרטית", "vault.addMore": "הוסף עוד", "vault.addToVault": "הוסף לכספת",
        "vault.addCamera": "הוסף מהמצלמה", "vault.addPhotos": "הוסף מהתמונות",
        "vault.importError": "הייבוא נכשל", "vault.emptyTitle": "אין עדיין תמונות פרטיות",
        "vault.emptyBody": "הקש על הוסף עוד כדי להביא תמונות לכאן.\nהן מוצפנות AES-256 במכשיר הזה בלבד.",
        "vault.encrypting": "מצפין…", "vault.deleteItemTitle": "למחוק את הפריט הזה?",
        "vault.deleteItemBody": "פעולה זו מסירה לצמיתות את העותק המוצפן מהכספת שלך.",
        "vault.decryptFailTitle": "פענוח נכשל", "vault.decryptFailBody": "לא ניתן לפענח את הקובץ. ייתכן שהוא פגום.",
        "vault.aes": "מוצפן AES-256", "vault.share": "שתף",
        "vault.lockedTitle": "הכספת הפרטית\nנעולה", "vault.lockedBody": "התמונות שלך מוצפנות\nומוגנות.",
        "vault.unlockFaceID": "פתח עם %@", "vault.authFailTitle": "האימות נכשל",
        "vault.unlockReason": "פתח את הכספת הפרטית שלך",
        "passcode.create": "צור קוד גישה", "passcode.reenter": "הזן שוב את הקוד",
        "passcode.createSub": "בחר קוד בן 6 ספרות כדי\nלהגן על הכספת הפרטית שלך.",
        "passcode.confirmSub": "הזן שוב את אותן 6 הספרות\nכדי לאשר את הקוד החדש.",
        "passcode.mismatch": "הקודים לא תואמים — התחל מחדש", "passcode.saveErrorTitle": "לא ניתן לשמור את הקוד",
        "passcode.saveErrorBody": "שמירת הקוד בצורה מאובטחת נכשלה. נסה שוב.",
        "passcode.wrongCurrent": "הקוד הזה לא תואם — נסה שוב", "passcode.saveError2Title": "השמירה נכשלה",
        "passcode.saveError2Body": "שמירת הקוד החדש נכשלה. נסה שוב.",
        "passcode.changeTitle": "שנה קוד גישה", "passcode.newTitle": "קוד חדש",
        "passcode.verifySub": "הזן את קוד 6 הספרות הנוכחי שלך\nכדי לאמת את זהותך.",
        "passcode.newSub": "בחר קוד חדש בן 6 ספרות\nלכספת הפרטית שלך.",
        "passcode.usePasscode": "השתמש בקוד", "passcode.enterTitle": "הזן קוד", "passcode.wrong": "קוד שגוי — נסה שוב",
        "paywall.unlockStorage": "פנה עוד אחסון", "paywall.enableTrial": "הפעל ניסיון חינם",
        "paywall.purchaseFailTitle": "הרכישה נכשלה", "paywall.restore": "שחזר",
        "paywall.subtitle": "שמור את מה שאתה רוצה, הסר את המיותר!", "paywall.photos": "תמונות", "paywall.drive": "Drive",
        "paywall.of": " מתוך ", "paywall.used": " בשימוש", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "פרימיום",
        "paywall.features": "ניקוי חכם, דחיסת וידאו, ללא הגבלות.", "paywall.perWeek": "/שבוע",
        "paywall.monthly": "חודשי", "paywall.monthlyDesc": "גישה מלאה, ביטול בכל עת", "paywall.continue": "המשך",
        "paywall.terms": "תנאי שימוש", "paywall.privacy": "מדיניות פרטיות",
        "paywall.unavailable": "מוצר המנוי אינו זמין", "paywall.noRestore": "אין רכישות לשחזור.",
        "success.congrats": "מזל טוב!", "success.junkRemoved": "קבצי זבל הוסרו", "success.perfect": "מושלם!",
        "success.cleaned": "נוקה", "success.photosOptimized": "תמונות עברו אופטימיזציה", "success.memoryBoosted": "זיכרון פונה",
        "success.totalCleaned": "סך הכול נוקה", "success.junkRemoved2": "זבל הוסר",
        "quickclean.cleaning": "מנקה את הטלפון שלך...", "quickclean.scanning": "מחפש תמונות דומות…",
        "quickclean.permBody": "האפליקציה צריכה גישה לספריית התמונות כדי לסרוק מה לנקות.",
        "quickclean.emptyTitle": "כבר נקי לגמרי", "quickclean.emptyBody": "לא מצאנו כרגע תמונות דומות לניקוי.",
        "cleaning.deleting": "מוחק את התמונות שנבחרו...", "deleteconfirm.title": "למחוק %d תמונות?",
        "deleteconfirm.body": "%@ אלה של תמונות\nיוסרו לצמיתות.",
        "preview.delete": "מחק", "preview.keep": "שמור",
    ]

    private static let ar: [String: String] = [
        "vault.title": "الخزنة الخاصة", "vault.addMore": "إضافة المزيد", "vault.addToVault": "إضافة إلى الخزنة",
        "vault.addCamera": "إضافة من الكاميرا", "vault.addPhotos": "إضافة من الصور",
        "vault.importError": "تعذّر الاستيراد", "vault.emptyTitle": "لا صور خاصة بعد",
        "vault.emptyBody": "اضغط على إضافة المزيد لجلب الصور هنا.\nتُشفّر بـ AES-256 على هذا الجهاز فقط.",
        "vault.encrypting": "جارٍ التشفير…", "vault.deleteItemTitle": "حذف هذا العنصر؟",
        "vault.deleteItemBody": "سيؤدي هذا إلى إزالة النسخة المشفّرة نهائيًا من خزنتك.",
        "vault.decryptFailTitle": "فشل فك التشفير", "vault.decryptFailBody": "تعذّر فك تشفير هذا الملف. قد يكون تالفًا.",
        "vault.aes": "مشفّر AES-256", "vault.share": "مشاركة",
        "vault.lockedTitle": "الخزنة الخاصة\nمقفلة", "vault.lockedBody": "صورك مشفّرة\nومحمية.",
        "vault.unlockFaceID": "فتح بـ %@", "vault.authFailTitle": "تعذّر المصادقة",
        "vault.unlockReason": "افتح خزنتك الخاصة",
        "passcode.create": "إنشاء رمز مرور", "passcode.reenter": "أعد إدخال الرمز",
        "passcode.createSub": "اختر رمزًا من 6 أرقام\nلحماية خزنتك الخاصة.",
        "passcode.confirmSub": "أدخل الأرقام الستة نفسها مرة أخرى\nلتأكيد رمزك الجديد.",
        "passcode.mismatch": "الرموز غير متطابقة — ابدأ من جديد", "passcode.saveErrorTitle": "تعذّر حفظ الرمز",
        "passcode.saveErrorBody": "فشل حفظ الرمز بأمان. حاول مرة أخرى.",
        "passcode.wrongCurrent": "هذا الرمز غير مطابق — حاول مرة أخرى", "passcode.saveError2Title": "تعذّر الحفظ",
        "passcode.saveError2Body": "فشل حفظ الرمز الجديد. حاول مرة أخرى.",
        "passcode.changeTitle": "تغيير رمز المرور", "passcode.newTitle": "رمز جديد",
        "passcode.verifySub": "أدخل رمزك الحالي المكوّن من 6 أرقام\nللتحقق من هويتك.",
        "passcode.newSub": "اختر رمزًا جديدًا من 6 أرقام\nلخزنتك الخاصة.",
        "passcode.usePasscode": "استخدام الرمز", "passcode.enterTitle": "أدخل الرمز", "passcode.wrong": "رمز خاطئ — حاول مرة أخرى",
        "paywall.unlockStorage": "افتح مساحة أكبر", "paywall.enableTrial": "تفعيل النسخة التجريبية",
        "paywall.purchaseFailTitle": "فشل الشراء", "paywall.restore": "استعادة",
        "paywall.subtitle": "احتفظ بما تريد، واحذف غير الضروري!", "paywall.photos": "الصور", "paywall.drive": "Drive",
        "paywall.of": " من ", "paywall.used": " مستخدمة", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "بريميوم",
        "paywall.features": "تنظيف ذكي، ضغط فيديو، بلا حدود.", "paywall.perWeek": "/أسبوع",
        "paywall.monthly": "شهري", "paywall.monthlyDesc": "وصول كامل، ألغِ في أي وقت", "paywall.continue": "متابعة",
        "paywall.terms": "شروط الاستخدام", "paywall.privacy": "سياسة الخصوصية",
        "paywall.unavailable": "منتج الاشتراك غير متوفر", "paywall.noRestore": "لا توجد مشتريات للاستعادة.",
        "success.congrats": "تهانينا!", "success.junkRemoved": "تمت إزالة الملفات غير المرغوبة", "success.perfect": "ممتاز!",
        "success.cleaned": "تم التنظيف", "success.photosOptimized": "تم تحسين الصور", "success.memoryBoosted": "تم تحرير الذاكرة",
        "success.totalCleaned": "إجمالي ما تم تنظيفه", "success.junkRemoved2": "تمت إزالة غير المرغوب",
        "quickclean.cleaning": "جارٍ تنظيف هاتفك...", "quickclean.scanning": "البحث عن صور متشابهة…",
        "quickclean.permBody": "يحتاج التطبيق إلى الوصول إلى مكتبة صورك للبحث عمّا يمكن تنظيفه.",
        "quickclean.emptyTitle": "نظيف تمامًا بالفعل", "quickclean.emptyBody": "لم نعثر على صور متشابهة لتنظيفها الآن.",
        "cleaning.deleting": "جارٍ حذف الصور المحددة...", "deleteconfirm.title": "حذف %d صورة؟",
        "deleteconfirm.body": "ستتم إزالة هذه الـ %@ من الصور\nنهائيًا.",
        "preview.delete": "حذف", "preview.keep": "احتفاظ",
    ]

    private static let fa: [String: String] = [
        "vault.title": "گاوصندوق خصوصی", "vault.addMore": "افزودن بیشتر", "vault.addToVault": "افزودن به گاوصندوق",
        "vault.addCamera": "افزودن از دوربین", "vault.addPhotos": "افزودن از عکس‌ها",
        "vault.importError": "وارد کردن ممکن نشد", "vault.emptyTitle": "هنوز عکس خصوصی نیست",
        "vault.emptyBody": "برای آوردن عکس‌ها به اینجا روی افزودن بیشتر بزنید.\nفقط روی این دستگاه با AES-256 رمزگذاری می‌شوند.",
        "vault.encrypting": "در حال رمزگذاری…", "vault.deleteItemTitle": "این مورد حذف شود؟",
        "vault.deleteItemBody": "این کار نسخه رمزگذاری‌شده را برای همیشه از گاوصندوق شما حذف می‌کند.",
        "vault.decryptFailTitle": "رمزگشایی ناموفق", "vault.decryptFailBody": "این فایل رمزگشایی نشد. ممکن است خراب باشد.",
        "vault.aes": "رمزگذاری AES-256", "vault.share": "اشتراک‌گذاری",
        "vault.lockedTitle": "گاوصندوق خصوصی\nقفل است", "vault.lockedBody": "عکس‌های شما رمزگذاری و\nمحافظت شده‌اند.",
        "vault.unlockFaceID": "باز کردن با %@", "vault.authFailTitle": "احراز هویت ناموفق",
        "vault.unlockReason": "گاوصندوق خصوصی خود را باز کنید",
        "passcode.create": "ایجاد رمز عبور", "passcode.reenter": "رمز را دوباره وارد کنید",
        "passcode.createSub": "یک کد ۶ رقمی برای محافظت از\nگاوصندوق خصوصی خود انتخاب کنید.",
        "passcode.confirmSub": "همان ۶ رقم را دوباره وارد کنید\nتا رمز جدید تأیید شود.",
        "passcode.mismatch": "کدها مطابقت ندارند — از نو شروع کنید", "passcode.saveErrorTitle": "ذخیره رمز ناموفق بود",
        "passcode.saveErrorBody": "ذخیره ایمن رمز ناموفق بود. دوباره تلاش کنید.",
        "passcode.wrongCurrent": "این رمز مطابقت ندارد — دوباره تلاش کنید", "passcode.saveError2Title": "ذخیره ناموفق",
        "passcode.saveError2Body": "ذخیره رمز جدید ناموفق بود. دوباره تلاش کنید.",
        "passcode.changeTitle": "تغییر رمز عبور", "passcode.newTitle": "رمز جدید",
        "passcode.verifySub": "برای تأیید هویت، رمز ۶ رقمی\nفعلی خود را وارد کنید.",
        "passcode.newSub": "یک کد ۶ رقمی جدید برای\nگاوصندوق خصوصی خود انتخاب کنید.",
        "passcode.usePasscode": "استفاده از رمز", "passcode.enterTitle": "رمز را وارد کنید", "passcode.wrong": "رمز اشتباه — دوباره تلاش کنید",
        "paywall.unlockStorage": "فضای بیشتری باز کنید", "paywall.enableTrial": "فعال‌سازی نسخه آزمایشی رایگان",
        "paywall.purchaseFailTitle": "خرید ناموفق", "paywall.restore": "بازیابی",
        "paywall.subtitle": "آنچه می‌خواهید نگه دارید، غیرضروری را حذف کنید!", "paywall.photos": "عکس‌ها", "paywall.drive": "Drive",
        "paywall.of": " از ", "paywall.used": " استفاده‌شده", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "ویژه",
        "paywall.features": "پاک‌سازی هوشمند، فشرده‌ساز ویدیو، بدون محدودیت.", "paywall.perWeek": "/هفته",
        "paywall.monthly": "ماهانه", "paywall.monthlyDesc": "دسترسی کامل، لغو در هر زمان", "paywall.continue": "ادامه",
        "paywall.terms": "شرایط استفاده", "paywall.privacy": "سیاست حریم خصوصی",
        "paywall.unavailable": "محصول اشتراک در دسترس نیست", "paywall.noRestore": "خریدی برای بازیابی نیست.",
        "success.congrats": "تبریک!", "success.junkRemoved": "فایل‌های زائد حذف شدند", "success.perfect": "عالی!",
        "success.cleaned": "پاک شد", "success.photosOptimized": "عکس‌ها بهینه شدند", "success.memoryBoosted": "حافظه آزاد شد",
        "success.totalCleaned": "مجموع پاک‌شده", "success.junkRemoved2": "زائدات حذف شد",
        "quickclean.cleaning": "در حال پاک‌سازی تلفن شما...", "quickclean.scanning": "در حال جستجوی عکس‌های مشابه…",
        "quickclean.permBody": "برنامه برای بررسی موارد قابل پاک‌سازی به دسترسی به کتابخانه عکس نیاز دارد.",
        "quickclean.emptyTitle": "همین حالا کاملاً تمیز است", "quickclean.emptyBody": "در حال حاضر عکس مشابهی برای پاک‌سازی پیدا نکردیم.",
        "cleaning.deleting": "در حال حذف عکس‌های انتخاب‌شده...", "deleteconfirm.title": "%d عکس حذف شود؟",
        "deleteconfirm.body": "این %@ عکس برای همیشه\nحذف خواهند شد.",
        "preview.delete": "حذف", "preview.keep": "نگه‌داشتن",
    ]

    private static let id: [String: String] = [
        "vault.title": "Brankas pribadi", "vault.addMore": "Tambah lagi", "vault.addToVault": "Tambah ke brankas",
        "vault.addCamera": "Tambah dari kamera", "vault.addPhotos": "Tambah dari Foto",
        "vault.importError": "Tidak dapat mengimpor", "vault.emptyTitle": "Belum ada foto pribadi",
        "vault.emptyBody": "Ketuk Tambah lagi untuk membawa foto ke sini.\nDienkripsi AES-256 hanya di perangkat ini.",
        "vault.encrypting": "Mengenkripsi…", "vault.deleteItemTitle": "Hapus item ini?",
        "vault.deleteItemBody": "Ini menghapus permanen salinan terenkripsi dari brankasmu.",
        "vault.decryptFailTitle": "Dekripsi gagal", "vault.decryptFailBody": "Tidak dapat mendekripsi file ini. Mungkin rusak.",
        "vault.aes": "Terenkripsi AES-256", "vault.share": "Bagikan",
        "vault.lockedTitle": "Brankas pribadi\nterkunci", "vault.lockedBody": "Fotomu dienkripsi dan\ndilindungi.",
        "vault.unlockFaceID": "Buka dengan %@", "vault.authFailTitle": "Tidak dapat autentikasi",
        "vault.unlockReason": "Buka brankas pribadimu",
        "passcode.create": "Buat kode sandi", "passcode.reenter": "Masukkan ulang kode",
        "passcode.createSub": "Pilih kode 6 digit untuk\nmelindungi brankas pribadimu.",
        "passcode.confirmSub": "Masukkan 6 digit yang sama lagi\nuntuk mengonfirmasi kode barumu.",
        "passcode.mismatch": "Kode tidak cocok — ulangi", "passcode.saveErrorTitle": "Tidak dapat menyimpan kode",
        "passcode.saveErrorBody": "Gagal menyimpan kode dengan aman. Coba lagi.",
        "passcode.wrongCurrent": "Kode itu tidak cocok — coba lagi", "passcode.saveError2Title": "Tidak dapat menyimpan",
        "passcode.saveError2Body": "Gagal menyimpan kode baru. Coba lagi.",
        "passcode.changeTitle": "Ubah kode sandi", "passcode.newTitle": "Kode baru",
        "passcode.verifySub": "Masukkan kode 6 digit saat ini\nuntuk memverifikasi identitasmu.",
        "passcode.newSub": "Pilih kode 6 digit baru\nuntuk brankas pribadimu.",
        "passcode.usePasscode": "Gunakan kode", "passcode.enterTitle": "Masukkan kode", "passcode.wrong": "Kode salah — coba lagi",
        "paywall.unlockStorage": "Buka lebih banyak penyimpanan", "paywall.enableTrial": "Aktifkan uji coba gratis",
        "paywall.purchaseFailTitle": "Pembelian gagal", "paywall.restore": "Pulihkan",
        "paywall.subtitle": "Simpan yang kamu mau, hapus yang tak perlu!", "paywall.photos": "Foto", "paywall.drive": "Drive",
        "paywall.of": " dari ", "paywall.used": " terpakai", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "Premium",
        "paywall.features": "Pembersihan pintar, kompresor video, tanpa batas.", "paywall.perWeek": "/minggu",
        "paywall.monthly": "Bulanan", "paywall.monthlyDesc": "Akses penuh, batalkan kapan saja", "paywall.continue": "Lanjut",
        "paywall.terms": "Ketentuan penggunaan", "paywall.privacy": "Kebijakan privasi",
        "paywall.unavailable": "Produk langganan tidak tersedia", "paywall.noRestore": "Tidak ada pembelian untuk dipulihkan.",
        "success.congrats": "Selamat!", "success.junkRemoved": "File sampah dihapus", "success.perfect": "Sempurna!",
        "success.cleaned": "Dibersihkan", "success.photosOptimized": "Foto dioptimalkan", "success.memoryBoosted": "Memori dibebaskan",
        "success.totalCleaned": "Total dibersihkan", "success.junkRemoved2": "Sampah dihapus",
        "quickclean.cleaning": "Membersihkan ponselmu...", "quickclean.scanning": "Mencari foto serupa…",
        "quickclean.permBody": "Aplikasi perlu akses ke pustaka fotomu untuk memindai yang bisa dibersihkan.",
        "quickclean.emptyTitle": "Sudah bersih kinclong", "quickclean.emptyBody": "Saat ini kami tidak menemukan foto serupa untuk dibersihkan.",
        "cleaning.deleting": "Menghapus foto terpilih...", "deleteconfirm.title": "Hapus %d foto?",
        "deleteconfirm.body": "%@ foto ini akan\ndihapus permanen.",
        "preview.delete": "HAPUS", "preview.keep": "SIMPAN",
    ]

    private static let vi: [String: String] = [
        "vault.title": "Kho riêng tư", "vault.addMore": "Thêm", "vault.addToVault": "Thêm vào kho",
        "vault.addCamera": "Thêm từ Camera", "vault.addPhotos": "Thêm từ Ảnh",
        "vault.importError": "Không thể nhập", "vault.emptyTitle": "Chưa có ảnh riêng tư",
        "vault.emptyBody": "Chạm Thêm để đưa ảnh vào đây.\nChúng được mã hoá AES-256 chỉ trên thiết bị này.",
        "vault.encrypting": "Đang mã hoá…", "vault.deleteItemTitle": "Xoá mục này?",
        "vault.deleteItemBody": "Thao tác này xoá vĩnh viễn bản sao đã mã hoá khỏi kho của bạn.",
        "vault.decryptFailTitle": "Giải mã thất bại", "vault.decryptFailBody": "Không thể giải mã tệp này. Có thể tệp đã hỏng.",
        "vault.aes": "Mã hoá AES-256", "vault.share": "Chia sẻ",
        "vault.lockedTitle": "Kho riêng tư\nđang khoá", "vault.lockedBody": "Ảnh của bạn được mã hoá và\nbảo vệ.",
        "vault.unlockFaceID": "Mở khoá bằng %@", "vault.authFailTitle": "Không thể xác thực",
        "vault.unlockReason": "Mở khoá kho riêng tư của bạn",
        "passcode.create": "Tạo mật mã", "passcode.reenter": "Nhập lại mật mã",
        "passcode.createSub": "Chọn mã 6 chữ số để\nbảo vệ kho riêng tư của bạn.",
        "passcode.confirmSub": "Nhập lại đúng 6 chữ số\nđể xác nhận mật mã mới.",
        "passcode.mismatch": "Mã không khớp — làm lại", "passcode.saveErrorTitle": "Không lưu được mật mã",
        "passcode.saveErrorBody": "Không lưu được mật mã an toàn. Vui lòng thử lại.",
        "passcode.wrongCurrent": "Mật mã không khớp — thử lại", "passcode.saveError2Title": "Không lưu được",
        "passcode.saveError2Body": "Không lưu được mật mã mới. Vui lòng thử lại.",
        "passcode.changeTitle": "Đổi mật mã", "passcode.newTitle": "Mật mã mới",
        "passcode.verifySub": "Nhập mật mã 6 chữ số hiện tại\nđể xác minh danh tính.",
        "passcode.newSub": "Chọn mã 6 chữ số mới cho\nkho riêng tư của bạn.",
        "passcode.usePasscode": "Dùng mật mã", "passcode.enterTitle": "Nhập mật mã", "passcode.wrong": "Sai mật mã — thử lại",
        "paywall.unlockStorage": "Mở thêm dung lượng", "paywall.enableTrial": "Bật dùng thử miễn phí",
        "paywall.purchaseFailTitle": "Mua thất bại", "paywall.restore": "Khôi phục",
        "paywall.subtitle": "Giữ thứ bạn muốn, xoá thứ không cần!", "paywall.photos": "Ảnh", "paywall.drive": "Drive",
        "paywall.of": " trên ", "paywall.used": " đã dùng", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "Premium",
        "paywall.features": "Dọn dẹp thông minh, nén video, không giới hạn.", "paywall.perWeek": "/tuần",
        "paywall.monthly": "Hàng tháng", "paywall.monthlyDesc": "Toàn quyền, huỷ bất cứ lúc nào", "paywall.continue": "Tiếp tục",
        "paywall.terms": "Điều khoản sử dụng", "paywall.privacy": "Chính sách bảo mật",
        "paywall.unavailable": "Sản phẩm đăng ký không khả dụng", "paywall.noRestore": "Không có giao dịch để khôi phục.",
        "success.congrats": "Chúc mừng!", "success.junkRemoved": "Đã xoá tệp rác", "success.perfect": "Hoàn hảo!",
        "success.cleaned": "Đã dọn", "success.photosOptimized": "Ảnh đã tối ưu", "success.memoryBoosted": "Đã giải phóng bộ nhớ",
        "success.totalCleaned": "Tổng đã dọn", "success.junkRemoved2": "Đã xoá rác",
        "quickclean.cleaning": "Đang dọn dẹp điện thoại...", "quickclean.scanning": "Đang quét ảnh tương tự…",
        "quickclean.permBody": "Ứng dụng cần quyền truy cập thư viện ảnh để quét những thứ cần dọn.",
        "quickclean.emptyTitle": "Đã sạch bong", "quickclean.emptyBody": "Hiện chưa tìm thấy ảnh tương tự nào để dọn.",
        "cleaning.deleting": "Đang xoá ảnh đã chọn...", "deleteconfirm.title": "Xoá %d ảnh?",
        "deleteconfirm.body": "%@ ảnh này sẽ bị\nxoá vĩnh viễn.",
        "preview.delete": "XOÁ", "preview.keep": "GIỮ",
    ]

    private static let ja: [String: String] = [
        "vault.title": "プライベート金庫", "vault.addMore": "追加", "vault.addToVault": "金庫に追加",
        "vault.addCamera": "カメラから追加", "vault.addPhotos": "写真から追加",
        "vault.importError": "読み込めませんでした", "vault.emptyTitle": "まだプライベート写真がありません",
        "vault.emptyBody": "追加をタップして写真をここに入れましょう。\nこの端末でのみ AES-256 で暗号化されます。",
        "vault.encrypting": "暗号化中…", "vault.deleteItemTitle": "この項目を削除しますか？",
        "vault.deleteItemBody": "暗号化されたコピーが金庫から完全に削除されます。",
        "vault.decryptFailTitle": "復号に失敗しました", "vault.decryptFailBody": "このファイルを復号できませんでした。破損している可能性があります。",
        "vault.aes": "AES-256 暗号化", "vault.share": "共有",
        "vault.lockedTitle": "プライベート金庫は\nロックされています", "vault.lockedBody": "写真は暗号化され\n保護されています。",
        "vault.unlockFaceID": "%@ でロック解除", "vault.authFailTitle": "認証できませんでした",
        "vault.unlockReason": "プライベート金庫のロックを解除",
        "passcode.create": "パスコードを作成", "passcode.reenter": "パスコードを再入力",
        "passcode.createSub": "プライベート金庫を保護する\n6桁のコードを選んでください。",
        "passcode.confirmSub": "新しいパスコードを確認するため\n同じ6桁をもう一度入力してください。",
        "passcode.mismatch": "コードが一致しません — やり直してください", "passcode.saveErrorTitle": "パスコードを保存できませんでした",
        "passcode.saveErrorBody": "パスコードを安全に保存できませんでした。もう一度お試しください。",
        "passcode.wrongCurrent": "そのパスコードは一致しません — もう一度", "passcode.saveError2Title": "保存できませんでした",
        "passcode.saveError2Body": "新しいパスコードを保存できませんでした。もう一度お試しください。",
        "passcode.changeTitle": "パスコードを変更", "passcode.newTitle": "新しいパスコード",
        "passcode.verifySub": "本人確認のため、現在の\n6桁のパスコードを入力してください。",
        "passcode.newSub": "プライベート金庫用の\n新しい6桁コードを選んでください。",
        "passcode.usePasscode": "パスコードを使う", "passcode.enterTitle": "パスコードを入力", "passcode.wrong": "パスコードが違います — もう一度",
        "paywall.unlockStorage": "もっと容量を解放", "paywall.enableTrial": "無料トライアルを有効化",
        "paywall.purchaseFailTitle": "購入に失敗しました", "paywall.restore": "復元",
        "paywall.subtitle": "必要なものは残し、不要なものは削除！", "paywall.photos": "写真", "paywall.drive": "ドライブ",
        "paywall.of": " / ", "paywall.used": " 使用", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "プレミアム",
        "paywall.features": "スマート整理、動画圧縮、制限なし。", "paywall.perWeek": "/週",
        "paywall.monthly": "月額", "paywall.monthlyDesc": "フルアクセス、いつでも解約可", "paywall.continue": "続ける",
        "paywall.terms": "利用規約", "paywall.privacy": "プライバシーポリシー",
        "paywall.unavailable": "サブスク商品を利用できません", "paywall.noRestore": "復元する購入がありません。",
        "success.congrats": "おめでとうございます！", "success.junkRemoved": "不要ファイルを削除", "success.perfect": "完璧！",
        "success.cleaned": "クリーン", "success.photosOptimized": "写真を最適化", "success.memoryBoosted": "メモリを解放",
        "success.totalCleaned": "合計クリーン", "success.junkRemoved2": "ゴミを削除",
        "quickclean.cleaning": "スマホを整理中...", "quickclean.scanning": "類似写真を検索中…",
        "quickclean.permBody": "整理対象を探すため、写真ライブラリへのアクセスが必要です。",
        "quickclean.emptyTitle": "すでにピカピカ", "quickclean.emptyBody": "現在、整理できる類似写真は見つかりませんでした。",
        "cleaning.deleting": "選択した写真を削除中...", "deleteconfirm.title": "%d枚の写真を削除しますか？",
        "deleteconfirm.body": "これら %@ 分の写真は\n完全に削除されます。",
        "preview.delete": "削除", "preview.keep": "保持",
    ]

    private static let ko: [String: String] = [
        "vault.title": "비공개 보관함", "vault.addMore": "더 추가", "vault.addToVault": "보관함에 추가",
        "vault.addCamera": "카메라에서 추가", "vault.addPhotos": "사진에서 추가",
        "vault.importError": "가져올 수 없음", "vault.emptyTitle": "아직 비공개 사진이 없습니다",
        "vault.emptyBody": "더 추가를 눌러 사진을 가져오세요.\n이 기기에서만 AES-256으로 암호화됩니다.",
        "vault.encrypting": "암호화 중…", "vault.deleteItemTitle": "이 항목을 삭제할까요?",
        "vault.deleteItemBody": "암호화된 사본이 보관함에서 영구히 삭제됩니다.",
        "vault.decryptFailTitle": "복호화 실패", "vault.decryptFailBody": "이 파일을 복호화할 수 없습니다. 손상되었을 수 있습니다.",
        "vault.aes": "AES-256 암호화", "vault.share": "공유",
        "vault.lockedTitle": "비공개 보관함이\n잠겨 있습니다", "vault.lockedBody": "사진이 암호화되어\n보호됩니다.",
        "vault.unlockFaceID": "%@(으)로 잠금 해제", "vault.authFailTitle": "인증할 수 없음",
        "vault.unlockReason": "비공개 보관함 잠금 해제",
        "passcode.create": "암호 만들기", "passcode.reenter": "암호 다시 입력",
        "passcode.createSub": "비공개 보관함을 보호할\n6자리 코드를 선택하세요.",
        "passcode.confirmSub": "새 암호를 확인하려면\n같은 6자리를 다시 입력하세요.",
        "passcode.mismatch": "코드가 일치하지 않습니다 — 다시 시작", "passcode.saveErrorTitle": "암호를 저장할 수 없음",
        "passcode.saveErrorBody": "암호를 안전하게 저장하지 못했습니다. 다시 시도하세요.",
        "passcode.wrongCurrent": "암호가 일치하지 않습니다 — 다시 시도", "passcode.saveError2Title": "저장할 수 없음",
        "passcode.saveError2Body": "새 암호를 저장하지 못했습니다. 다시 시도하세요.",
        "passcode.changeTitle": "암호 변경", "passcode.newTitle": "새 암호",
        "passcode.verifySub": "본인 확인을 위해 현재\n6자리 암호를 입력하세요.",
        "passcode.newSub": "비공개 보관함용 새\n6자리 코드를 선택하세요.",
        "passcode.usePasscode": "암호 사용", "passcode.enterTitle": "암호 입력", "passcode.wrong": "잘못된 암호 — 다시 시도",
        "paywall.unlockStorage": "더 많은 저장 공간 잠금 해제", "paywall.enableTrial": "무료 체험 시작",
        "paywall.purchaseFailTitle": "구매 실패", "paywall.restore": "복원",
        "paywall.subtitle": "원하는 건 남기고, 불필요한 건 삭제!", "paywall.photos": "사진", "paywall.drive": "Drive",
        "paywall.of": " / ", "paywall.used": " 사용", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "프리미엄",
        "paywall.features": "스마트 정리, 동영상 압축, 무제한.", "paywall.perWeek": "/주",
        "paywall.monthly": "월간", "paywall.monthlyDesc": "전체 이용, 언제든 취소", "paywall.continue": "계속",
        "paywall.terms": "이용약관", "paywall.privacy": "개인정보 처리방침",
        "paywall.unavailable": "구독 상품을 사용할 수 없음", "paywall.noRestore": "복원할 구매가 없습니다.",
        "success.congrats": "축하합니다!", "success.junkRemoved": "정크 파일 삭제됨", "success.perfect": "완벽해요!",
        "success.cleaned": "정리됨", "success.photosOptimized": "사진 최적화됨", "success.memoryBoosted": "메모리 확보됨",
        "success.totalCleaned": "총 정리됨", "success.junkRemoved2": "정크 삭제됨",
        "quickclean.cleaning": "휴대폰 정리 중...", "quickclean.scanning": "유사한 사진 검색 중…",
        "quickclean.permBody": "정리할 항목을 검색하려면 사진 보관함 접근 권한이 필요합니다.",
        "quickclean.emptyTitle": "이미 아주 깨끗해요", "quickclean.emptyBody": "지금은 정리할 유사한 사진을 찾지 못했습니다.",
        "cleaning.deleting": "선택한 사진 삭제 중...", "deleteconfirm.title": "사진 %d장을 삭제할까요?",
        "deleteconfirm.body": "이 %@ 분량의 사진이\n영구히 삭제됩니다.",
        "preview.delete": "삭제", "preview.keep": "유지",
    ]

    private static let zhHans: [String: String] = [
        "vault.title": "私密保险库", "vault.addMore": "添加更多", "vault.addToVault": "添加到保险库",
        "vault.addCamera": "从相机添加", "vault.addPhotos": "从照片添加",
        "vault.importError": "无法导入", "vault.emptyTitle": "还没有私密照片",
        "vault.emptyBody": "点按添加更多以将照片放到这里。\n仅在本设备上使用 AES-256 加密。",
        "vault.encrypting": "加密中…", "vault.deleteItemTitle": "删除此项？",
        "vault.deleteItemBody": "这将从你的保险库中永久删除加密副本。",
        "vault.decryptFailTitle": "解密失败", "vault.decryptFailBody": "无法解密此文件，可能已损坏。",
        "vault.aes": "AES-256 加密", "vault.share": "分享",
        "vault.lockedTitle": "私密保险库\n已锁定", "vault.lockedBody": "你的照片已加密\n并受保护。",
        "vault.unlockFaceID": "用 %@ 解锁", "vault.authFailTitle": "无法验证",
        "vault.unlockReason": "解锁你的私密保险库",
        "passcode.create": "创建密码", "passcode.reenter": "再次输入密码",
        "passcode.createSub": "选择一个 6 位数字代码\n来保护你的私密保险库。",
        "passcode.confirmSub": "再次输入相同的 6 位数字\n以确认你的新密码。",
        "passcode.mismatch": "代码不匹配 — 重新开始", "passcode.saveErrorTitle": "无法保存密码",
        "passcode.saveErrorBody": "未能安全保存密码。请重试。",
        "passcode.wrongCurrent": "该密码不匹配 — 请重试", "passcode.saveError2Title": "无法保存",
        "passcode.saveError2Body": "未能保存新密码。请重试。",
        "passcode.changeTitle": "更改密码", "passcode.newTitle": "新密码",
        "passcode.verifySub": "输入你当前的 6 位密码\n以验证身份。",
        "passcode.newSub": "为你的私密保险库\n选择一个新的 6 位代码。",
        "passcode.usePasscode": "使用密码", "passcode.enterTitle": "输入密码", "passcode.wrong": "密码错误 — 请重试",
        "paywall.unlockStorage": "解锁更多空间", "paywall.enableTrial": "启用免费试用",
        "paywall.purchaseFailTitle": "购买失败", "paywall.restore": "恢复",
        "paywall.subtitle": "保留你想要的，删除不必要的！", "paywall.photos": "照片", "paywall.drive": "云盘",
        "paywall.of": " / ", "paywall.used": " 已用", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "高级版",
        "paywall.features": "智能清理、视频压缩、无限制。", "paywall.perWeek": "/周",
        "paywall.monthly": "每月", "paywall.monthlyDesc": "完整访问，随时取消", "paywall.continue": "继续",
        "paywall.terms": "使用条款", "paywall.privacy": "隐私政策",
        "paywall.unavailable": "订阅产品不可用", "paywall.noRestore": "没有可恢复的购买。",
        "success.congrats": "恭喜！", "success.junkRemoved": "垃圾文件已清除", "success.perfect": "完美！",
        "success.cleaned": "已清理", "success.photosOptimized": "照片已优化", "success.memoryBoosted": "内存已释放",
        "success.totalCleaned": "共清理", "success.junkRemoved2": "垃圾已清除",
        "quickclean.cleaning": "正在清理你的手机...", "quickclean.scanning": "正在扫描相似照片…",
        "quickclean.permBody": "应用需要访问你的照片图库，以扫描可清理的内容。",
        "quickclean.emptyTitle": "已经干干净净", "quickclean.emptyBody": "目前未找到可清理的相似照片。",
        "cleaning.deleting": "正在删除所选照片...", "deleteconfirm.title": "删除 %d 张照片？",
        "deleteconfirm.body": "这 %@ 的照片将被\n永久删除。",
        "preview.delete": "删除", "preview.keep": "保留",
    ]

    private static let zhHant: [String: String] = [
        "vault.title": "私密保險庫", "vault.addMore": "新增更多", "vault.addToVault": "加入保險庫",
        "vault.addCamera": "從相機新增", "vault.addPhotos": "從照片新增",
        "vault.importError": "無法匯入", "vault.emptyTitle": "尚無私密照片",
        "vault.emptyBody": "點按新增更多把照片放到這裡。\n僅在本裝置上以 AES-256 加密。",
        "vault.encrypting": "加密中…", "vault.deleteItemTitle": "刪除此項目？",
        "vault.deleteItemBody": "這會從你的保險庫永久移除加密副本。",
        "vault.decryptFailTitle": "解密失敗", "vault.decryptFailBody": "無法解密此檔案，可能已損毀。",
        "vault.aes": "AES-256 加密", "vault.share": "分享",
        "vault.lockedTitle": "私密保險庫\n已鎖定", "vault.lockedBody": "你的照片已加密\n並受保護。",
        "vault.unlockFaceID": "用 %@ 解鎖", "vault.authFailTitle": "無法驗證",
        "vault.unlockReason": "解鎖你的私密保險庫",
        "passcode.create": "建立密碼", "passcode.reenter": "再次輸入密碼",
        "passcode.createSub": "選擇一組 6 位數字代碼\n來保護你的私密保險庫。",
        "passcode.confirmSub": "再次輸入相同的 6 位數字\n以確認你的新密碼。",
        "passcode.mismatch": "代碼不符 — 重新開始", "passcode.saveErrorTitle": "無法儲存密碼",
        "passcode.saveErrorBody": "無法安全儲存密碼。請再試一次。",
        "passcode.wrongCurrent": "該密碼不符 — 請再試一次", "passcode.saveError2Title": "無法儲存",
        "passcode.saveError2Body": "無法儲存新密碼。請再試一次。",
        "passcode.changeTitle": "變更密碼", "passcode.newTitle": "新密碼",
        "passcode.verifySub": "輸入你目前的 6 位密碼\n以驗證身分。",
        "passcode.newSub": "為你的私密保險庫\n選擇一組新的 6 位代碼。",
        "passcode.usePasscode": "使用密碼", "passcode.enterTitle": "輸入密碼", "passcode.wrong": "密碼錯誤 — 請再試一次",
        "paywall.unlockStorage": "解鎖更多空間", "paywall.enableTrial": "啟用免費試用",
        "paywall.purchaseFailTitle": "購買失敗", "paywall.restore": "還原",
        "paywall.subtitle": "保留你想要的，刪除不必要的！", "paywall.photos": "照片", "paywall.drive": "雲端硬碟",
        "paywall.of": " / ", "paywall.used": " 已用", "paywall.proTitle": "Cleaner Pro", "paywall.premium": "進階版",
        "paywall.features": "智慧清理、影片壓縮、無限制。", "paywall.perWeek": "/週",
        "paywall.monthly": "每月", "paywall.monthlyDesc": "完整存取，隨時取消", "paywall.continue": "繼續",
        "paywall.terms": "使用條款", "paywall.privacy": "隱私權政策",
        "paywall.unavailable": "訂閱產品無法使用", "paywall.noRestore": "沒有可還原的購買。",
        "success.congrats": "恭喜！", "success.junkRemoved": "垃圾檔案已清除", "success.perfect": "完美！",
        "success.cleaned": "已清理", "success.photosOptimized": "照片已最佳化", "success.memoryBoosted": "記憶體已釋放",
        "success.totalCleaned": "共清理", "success.junkRemoved2": "垃圾已清除",
        "quickclean.cleaning": "正在清理你的手機...", "quickclean.scanning": "正在掃描相似照片…",
        "quickclean.permBody": "應用程式需要存取你的照片圖庫，以掃描可清理的內容。",
        "quickclean.emptyTitle": "已經乾乾淨淨", "quickclean.emptyBody": "目前找不到可清理的相似照片。",
        "cleaning.deleting": "正在刪除所選照片...", "deleteconfirm.title": "刪除 %d 張照片？",
        "deleteconfirm.body": "這 %@ 的照片將被\n永久移除。",
        "preview.delete": "刪除", "preview.keep": "保留",
    ]
}
