import Foundation

// Second translation table (Localizer checks this in addition to LocalizedStrings).
// Covers: Home card subtitles, the Similar review/detail screen, and the Filter sheet.
// Kept separate so the main table's per-language constants stay small/fast to compile.
enum LocalizedStrings2 {
    static let table: [String: [String: String]] = [
        "en": en, "es": es, "pt": pt, "fr": fr, "de": de, "it": it, "nl": nl,
        "tr": tr, "uk": uk, "ru": ru, "he": he, "ar": ar, "fa": fa, "id": id,
        "vi": vi, "ja": ja, "ko": ko, "zh-Hans": zhHans, "zh-Hant": zhHant,
    ]

    private static let en: [String: String] = [
        "home.sub.similar": "Yesterday", "home.sub.duplicates": "Last week", "home.sub.similarScreenshots": "Today",
        "home.sub.similarVideos": "Last month", "home.sub.otherScreenshots": "All time", "home.sub.chatPhotos": "Messages",
        "home.sub.videosOrganizer": "All videos", "home.sub.other": "Misc photos",
        "common.back": "Back", "common.done": "Done",
        "filter.title": "Filter", "filter.clearAll": "Clear All", "filter.dateRange": "DATE RANGE",
        "filter.sortBySize": "SORT BY SIZE", "filter.source": "SOURCE", "filter.apply": "Apply",
        "filter.date.7d": "7 days", "filter.date.30d": "30 days", "filter.date.all": "All time",
        "filter.sort.large": "Large to Small", "filter.sort.small": "Small to Large",
        "filter.src.camera": "Camera", "filter.src.screenshots": "Screenshots", "filter.src.download": "Download",
        "review.selectAll": "Select All", "review.deselect": "Deselect", "review.deleteSelected": "Delete Selected",
        "review.deleteN": "Delete %d Selected (%@)", "review.groupTitle": "%d %@",
        "review.noun.similar": "Similar", "review.noun.duplicates": "Duplicates",
        "review.noun.screenshots": "Screenshots", "review.noun.videos": "Videos",
        "flow.permBody": "The app needs access to your photo library to find similar photos and duplicates you can clean up.",
        "flow.emptyTitle": "Nothing to clean",
        "flow.emptyBody": "We didn’t find any similar photos in your library right now.",
        "flow.deleteErrorTitle": "Couldn’t delete",
    ]

    private static let es: [String: String] = [
        "home.sub.similar": "Ayer", "home.sub.duplicates": "La semana pasada", "home.sub.similarScreenshots": "Hoy",
        "home.sub.similarVideos": "El mes pasado", "home.sub.otherScreenshots": "Todo el tiempo", "home.sub.chatPhotos": "Mensajes",
        "home.sub.videosOrganizer": "Todos los videos", "home.sub.other": "Otras fotos",
        "common.back": "Atrás", "common.done": "Listo",
        "filter.title": "Filtro", "filter.clearAll": "Borrar todo", "filter.dateRange": "RANGO DE FECHAS",
        "filter.sortBySize": "ORDENAR POR TAMAÑO", "filter.source": "ORIGEN", "filter.apply": "Aplicar",
        "filter.date.7d": "7 días", "filter.date.30d": "30 días", "filter.date.all": "Todo el tiempo",
        "filter.sort.large": "Mayor a menor", "filter.sort.small": "Menor a mayor",
        "filter.src.camera": "Cámara", "filter.src.screenshots": "Capturas", "filter.src.download": "Descargas",
        "review.selectAll": "Seleccionar todo", "review.deselect": "Deseleccionar", "review.deleteSelected": "Eliminar selección",
        "review.deleteN": "Eliminar %d seleccionadas (%@)", "review.groupTitle": "%d %@",
        "review.noun.similar": "similares", "review.noun.duplicates": "duplicadas",
        "review.noun.screenshots": "capturas", "review.noun.videos": "videos",
        "flow.permBody": "La app necesita acceso a tu fototeca para encontrar fotos similares y duplicadas que puedes limpiar.",
        "flow.emptyTitle": "Nada que limpiar",
        "flow.emptyBody": "No encontramos fotos similares en tu biblioteca por ahora.",
        "flow.deleteErrorTitle": "No se pudo eliminar",
    ]

    private static let pt: [String: String] = [
        "home.sub.similar": "Ontem", "home.sub.duplicates": "Semana passada", "home.sub.similarScreenshots": "Hoje",
        "home.sub.similarVideos": "Mês passado", "home.sub.otherScreenshots": "Todo o período", "home.sub.chatPhotos": "Mensagens",
        "home.sub.videosOrganizer": "Todos os vídeos", "home.sub.other": "Outras fotos",
        "common.back": "Voltar", "common.done": "Concluir",
        "filter.title": "Filtro", "filter.clearAll": "Limpar tudo", "filter.dateRange": "INTERVALO DE DATAS",
        "filter.sortBySize": "ORDENAR POR TAMANHO", "filter.source": "ORIGEM", "filter.apply": "Aplicar",
        "filter.date.7d": "7 dias", "filter.date.30d": "30 dias", "filter.date.all": "Todo o período",
        "filter.sort.large": "Maior para menor", "filter.sort.small": "Menor para maior",
        "filter.src.camera": "Câmera", "filter.src.screenshots": "Capturas", "filter.src.download": "Downloads",
        "review.selectAll": "Selecionar tudo", "review.deselect": "Desmarcar", "review.deleteSelected": "Excluir seleção",
        "review.deleteN": "Excluir %d selecionadas (%@)", "review.groupTitle": "%d %@",
        "review.noun.similar": "semelhantes", "review.noun.duplicates": "duplicadas",
        "review.noun.screenshots": "capturas", "review.noun.videos": "vídeos",
        "flow.permBody": "O app precisa de acesso à sua fototeca para encontrar fotos semelhantes e duplicadas que você pode limpar.",
        "flow.emptyTitle": "Nada para limpar",
        "flow.emptyBody": "Não encontramos fotos semelhantes na sua biblioteca agora.",
        "flow.deleteErrorTitle": "Não foi possível excluir",
    ]

    private static let fr: [String: String] = [
        "home.sub.similar": "Hier", "home.sub.duplicates": "La semaine dernière", "home.sub.similarScreenshots": "Aujourd’hui",
        "home.sub.similarVideos": "Le mois dernier", "home.sub.otherScreenshots": "Tout", "home.sub.chatPhotos": "Messages",
        "home.sub.videosOrganizer": "Toutes les vidéos", "home.sub.other": "Autres photos",
        "common.back": "Retour", "common.done": "Terminé",
        "filter.title": "Filtre", "filter.clearAll": "Tout effacer", "filter.dateRange": "PLAGE DE DATES",
        "filter.sortBySize": "TRIER PAR TAILLE", "filter.source": "SOURCE", "filter.apply": "Appliquer",
        "filter.date.7d": "7 jours", "filter.date.30d": "30 jours", "filter.date.all": "Tout",
        "filter.sort.large": "Du plus grand au plus petit", "filter.sort.small": "Du plus petit au plus grand",
        "filter.src.camera": "Appareil photo", "filter.src.screenshots": "Captures", "filter.src.download": "Téléchargements",
        "review.selectAll": "Tout sélectionner", "review.deselect": "Désélectionner", "review.deleteSelected": "Supprimer la sélection",
        "review.deleteN": "Supprimer %d sélectionnées (%@)", "review.groupTitle": "%d %@",
        "review.noun.similar": "similaires", "review.noun.duplicates": "doublons",
        "review.noun.screenshots": "captures", "review.noun.videos": "vidéos",
        "flow.permBody": "L’app a besoin d’accéder à votre photothèque pour trouver les photos similaires et les doublons à nettoyer.",
        "flow.emptyTitle": "Rien à nettoyer",
        "flow.emptyBody": "Nous n’avons trouvé aucune photo similaire dans votre bibliothèque pour le moment.",
        "flow.deleteErrorTitle": "Suppression impossible",
    ]

    private static let de: [String: String] = [
        "home.sub.similar": "Gestern", "home.sub.duplicates": "Letzte Woche", "home.sub.similarScreenshots": "Heute",
        "home.sub.similarVideos": "Letzter Monat", "home.sub.otherScreenshots": "Gesamter Zeitraum", "home.sub.chatPhotos": "Nachrichten",
        "home.sub.videosOrganizer": "Alle Videos", "home.sub.other": "Sonstige Fotos",
        "common.back": "Zurück", "common.done": "Fertig",
        "filter.title": "Filter", "filter.clearAll": "Alle löschen", "filter.dateRange": "ZEITRAUM",
        "filter.sortBySize": "NACH GRÖSSE SORTIEREN", "filter.source": "QUELLE", "filter.apply": "Anwenden",
        "filter.date.7d": "7 Tage", "filter.date.30d": "30 Tage", "filter.date.all": "Gesamter Zeitraum",
        "filter.sort.large": "Groß zu klein", "filter.sort.small": "Klein zu groß",
        "filter.src.camera": "Kamera", "filter.src.screenshots": "Screenshots", "filter.src.download": "Downloads",
        "review.selectAll": "Alle auswählen", "review.deselect": "Abwählen", "review.deleteSelected": "Auswahl löschen",
        "review.deleteN": "%d ausgewählte löschen (%@)", "review.groupTitle": "%d %@",
        "review.noun.similar": "ähnliche", "review.noun.duplicates": "Duplikate",
        "review.noun.screenshots": "Screenshots", "review.noun.videos": "Videos",
        "flow.permBody": "Die App benötigt Zugriff auf deine Fotomediathek, um ähnliche Fotos und Duplikate zum Aufräumen zu finden.",
        "flow.emptyTitle": "Nichts aufzuräumen",
        "flow.emptyBody": "Wir haben gerade keine ähnlichen Fotos in deiner Mediathek gefunden.",
        "flow.deleteErrorTitle": "Löschen fehlgeschlagen",
    ]

    private static let it: [String: String] = [
        "home.sub.similar": "Ieri", "home.sub.duplicates": "Settimana scorsa", "home.sub.similarScreenshots": "Oggi",
        "home.sub.similarVideos": "Mese scorso", "home.sub.otherScreenshots": "Sempre", "home.sub.chatPhotos": "Messaggi",
        "home.sub.videosOrganizer": "Tutti i video", "home.sub.other": "Altre foto",
        "common.back": "Indietro", "common.done": "Fine",
        "filter.title": "Filtro", "filter.clearAll": "Cancella tutto", "filter.dateRange": "INTERVALLO DI DATE",
        "filter.sortBySize": "ORDINA PER DIMENSIONE", "filter.source": "ORIGINE", "filter.apply": "Applica",
        "filter.date.7d": "7 giorni", "filter.date.30d": "30 giorni", "filter.date.all": "Sempre",
        "filter.sort.large": "Dal più grande al più piccolo", "filter.sort.small": "Dal più piccolo al più grande",
        "filter.src.camera": "Fotocamera", "filter.src.screenshots": "Screenshot", "filter.src.download": "Download",
        "review.selectAll": "Seleziona tutto", "review.deselect": "Deseleziona", "review.deleteSelected": "Elimina selezione",
        "review.deleteN": "Elimina %d selezionate (%@)", "review.groupTitle": "%d %@",
        "review.noun.similar": "simili", "review.noun.duplicates": "duplicate",
        "review.noun.screenshots": "screenshot", "review.noun.videos": "video",
        "flow.permBody": "L’app ha bisogno di accedere alla tua libreria foto per trovare foto simili e duplicati da ripulire.",
        "flow.emptyTitle": "Niente da pulire",
        "flow.emptyBody": "Al momento non abbiamo trovato foto simili nella tua libreria.",
        "flow.deleteErrorTitle": "Impossibile eliminare",
    ]

    private static let nl: [String: String] = [
        "home.sub.similar": "Gisteren", "home.sub.duplicates": "Vorige week", "home.sub.similarScreenshots": "Vandaag",
        "home.sub.similarVideos": "Vorige maand", "home.sub.otherScreenshots": "Altijd", "home.sub.chatPhotos": "Berichten",
        "home.sub.videosOrganizer": "Alle video’s", "home.sub.other": "Overige foto’s",
        "common.back": "Terug", "common.done": "Klaar",
        "filter.title": "Filter", "filter.clearAll": "Alles wissen", "filter.dateRange": "DATUMBEREIK",
        "filter.sortBySize": "SORTEREN OP GROOTTE", "filter.source": "BRON", "filter.apply": "Toepassen",
        "filter.date.7d": "7 dagen", "filter.date.30d": "30 dagen", "filter.date.all": "Altijd",
        "filter.sort.large": "Groot naar klein", "filter.sort.small": "Klein naar groot",
        "filter.src.camera": "Camera", "filter.src.screenshots": "Schermafbeeldingen", "filter.src.download": "Downloads",
        "review.selectAll": "Alles selecteren", "review.deselect": "Deselecteren", "review.deleteSelected": "Selectie verwijderen",
        "review.deleteN": "%d geselecteerde verwijderen (%@)", "review.groupTitle": "%d %@",
        "review.noun.similar": "vergelijkbare", "review.noun.duplicates": "duplicaten",
        "review.noun.screenshots": "schermafbeeldingen", "review.noun.videos": "video’s",
        "flow.permBody": "De app heeft toegang tot je fotobibliotheek nodig om vergelijkbare foto’s en duplicaten te vinden om op te ruimen.",
        "flow.emptyTitle": "Niets om op te ruimen",
        "flow.emptyBody": "We hebben nu geen vergelijkbare foto’s in je bibliotheek gevonden.",
        "flow.deleteErrorTitle": "Verwijderen mislukt",
    ]

    private static let tr: [String: String] = [
        "home.sub.similar": "Dün", "home.sub.duplicates": "Geçen hafta", "home.sub.similarScreenshots": "Bugün",
        "home.sub.similarVideos": "Geçen ay", "home.sub.otherScreenshots": "Tüm zamanlar", "home.sub.chatPhotos": "Mesajlar",
        "home.sub.videosOrganizer": "Tüm videolar", "home.sub.other": "Diğer fotoğraflar",
        "common.back": "Geri", "common.done": "Bitti",
        "filter.title": "Filtre", "filter.clearAll": "Tümünü temizle", "filter.dateRange": "TARİH ARALIĞI",
        "filter.sortBySize": "BOYUTA GÖRE SIRALA", "filter.source": "KAYNAK", "filter.apply": "Uygula",
        "filter.date.7d": "7 gün", "filter.date.30d": "30 gün", "filter.date.all": "Tüm zamanlar",
        "filter.sort.large": "Büyükten küçüğe", "filter.sort.small": "Küçükten büyüğe",
        "filter.src.camera": "Kamera", "filter.src.screenshots": "Ekran görüntüleri", "filter.src.download": "İndirilenler",
        "review.selectAll": "Tümünü seç", "review.deselect": "Seçimi kaldır", "review.deleteSelected": "Seçileni sil",
        "review.deleteN": "%d seçileni sil (%@)", "review.groupTitle": "%d %@",
        "review.noun.similar": "benzer", "review.noun.duplicates": "kopya",
        "review.noun.screenshots": "ekran görüntüsü", "review.noun.videos": "video",
        "flow.permBody": "Uygulamanın, temizleyebileceğin benzer ve kopya fotoğrafları bulması için fotoğraf kitaplığına erişmesi gerekir.",
        "flow.emptyTitle": "Temizlenecek bir şey yok",
        "flow.emptyBody": "Şu anda kitaplığında benzer fotoğraf bulamadık.",
        "flow.deleteErrorTitle": "Silinemedi",
    ]

    private static let uk: [String: String] = [
        "home.sub.similar": "Учора", "home.sub.duplicates": "Минулого тижня", "home.sub.similarScreenshots": "Сьогодні",
        "home.sub.similarVideos": "Минулого місяця", "home.sub.otherScreenshots": "Увесь час", "home.sub.chatPhotos": "Повідомлення",
        "home.sub.videosOrganizer": "Усі відео", "home.sub.other": "Інші фото",
        "common.back": "Назад", "common.done": "Готово",
        "filter.title": "Фільтр", "filter.clearAll": "Очистити все", "filter.dateRange": "ДІАПАЗОН ДАТ",
        "filter.sortBySize": "СОРТУВАТИ ЗА РОЗМІРОМ", "filter.source": "ДЖЕРЕЛО", "filter.apply": "Застосувати",
        "filter.date.7d": "7 днів", "filter.date.30d": "30 днів", "filter.date.all": "Увесь час",
        "filter.sort.large": "Від більшого до меншого", "filter.sort.small": "Від меншого до більшого",
        "filter.src.camera": "Камера", "filter.src.screenshots": "Знімки екрана", "filter.src.download": "Завантаження",
        "review.selectAll": "Вибрати все", "review.deselect": "Зняти вибір", "review.deleteSelected": "Видалити вибране",
        "review.deleteN": "Видалити %d вибраних (%@)", "review.groupTitle": "%d %@",
        "review.noun.similar": "схожих", "review.noun.duplicates": "дублікатів",
        "review.noun.screenshots": "знімків екрана", "review.noun.videos": "відео",
        "flow.permBody": "Застосунку потрібен доступ до фотобібліотеки, щоб знайти схожі фото та дублікати, які можна очистити.",
        "flow.emptyTitle": "Немає чого очищати",
        "flow.emptyBody": "Наразі ми не знайшли схожих фото у вашій бібліотеці.",
        "flow.deleteErrorTitle": "Не вдалося видалити",
    ]

    private static let ru: [String: String] = [
        "home.sub.similar": "Вчера", "home.sub.duplicates": "На прошлой неделе", "home.sub.similarScreenshots": "Сегодня",
        "home.sub.similarVideos": "В прошлом месяце", "home.sub.otherScreenshots": "За всё время", "home.sub.chatPhotos": "Сообщения",
        "home.sub.videosOrganizer": "Все видео", "home.sub.other": "Другие фото",
        "common.back": "Назад", "common.done": "Готово",
        "filter.title": "Фильтр", "filter.clearAll": "Очистить всё", "filter.dateRange": "ДИАПАЗОН ДАТ",
        "filter.sortBySize": "СОРТИРОВКА ПО РАЗМЕРУ", "filter.source": "ИСТОЧНИК", "filter.apply": "Применить",
        "filter.date.7d": "7 дней", "filter.date.30d": "30 дней", "filter.date.all": "За всё время",
        "filter.sort.large": "От большего к меньшему", "filter.sort.small": "От меньшего к большему",
        "filter.src.camera": "Камера", "filter.src.screenshots": "Снимки экрана", "filter.src.download": "Загрузки",
        "review.selectAll": "Выбрать всё", "review.deselect": "Снять выбор", "review.deleteSelected": "Удалить выбранное",
        "review.deleteN": "Удалить %d выбранных (%@)", "review.groupTitle": "%d %@",
        "review.noun.similar": "похожих", "review.noun.duplicates": "дубликатов",
        "review.noun.screenshots": "снимков экрана", "review.noun.videos": "видео",
        "flow.permBody": "Приложению нужен доступ к фотогалерее, чтобы найти похожие фото и дубликаты для очистки.",
        "flow.emptyTitle": "Нечего очищать",
        "flow.emptyBody": "Сейчас мы не нашли похожих фото в вашей библиотеке.",
        "flow.deleteErrorTitle": "Не удалось удалить",
    ]

    private static let he: [String: String] = [
        "home.sub.similar": "אתמול", "home.sub.duplicates": "בשבוע שעבר", "home.sub.similarScreenshots": "היום",
        "home.sub.similarVideos": "בחודש שעבר", "home.sub.otherScreenshots": "כל הזמן", "home.sub.chatPhotos": "הודעות",
        "home.sub.videosOrganizer": "כל הסרטונים", "home.sub.other": "תמונות שונות",
        "common.back": "חזרה", "common.done": "סיום",
        "filter.title": "סינון", "filter.clearAll": "נקה הכול", "filter.dateRange": "טווח תאריכים",
        "filter.sortBySize": "מיון לפי גודל", "filter.source": "מקור", "filter.apply": "החל",
        "filter.date.7d": "7 ימים", "filter.date.30d": "30 ימים", "filter.date.all": "כל הזמן",
        "filter.sort.large": "מהגדול לקטן", "filter.sort.small": "מהקטן לגדול",
        "filter.src.camera": "מצלמה", "filter.src.screenshots": "צילומי מסך", "filter.src.download": "הורדות",
        "review.selectAll": "בחר הכול", "review.deselect": "בטל בחירה", "review.deleteSelected": "מחק נבחרים",
        "review.deleteN": "מחק %d נבחרים (%@)", "review.groupTitle": "%d %@",
        "review.noun.similar": "דומות", "review.noun.duplicates": "כפילויות",
        "review.noun.screenshots": "צילומי מסך", "review.noun.videos": "סרטונים",
        "flow.permBody": "האפליקציה צריכה גישה לספריית התמונות כדי למצוא תמונות דומות וכפילויות שאפשר לנקות.",
        "flow.emptyTitle": "אין מה לנקות",
        "flow.emptyBody": "לא מצאנו כרגע תמונות דומות בספרייה שלך.",
        "flow.deleteErrorTitle": "לא ניתן למחוק",
    ]

    private static let ar: [String: String] = [
        "home.sub.similar": "أمس", "home.sub.duplicates": "الأسبوع الماضي", "home.sub.similarScreenshots": "اليوم",
        "home.sub.similarVideos": "الشهر الماضي", "home.sub.otherScreenshots": "كل الأوقات", "home.sub.chatPhotos": "الرسائل",
        "home.sub.videosOrganizer": "كل الفيديوهات", "home.sub.other": "صور متنوعة",
        "common.back": "رجوع", "common.done": "تم",
        "filter.title": "تصفية", "filter.clearAll": "مسح الكل", "filter.dateRange": "نطاق التاريخ",
        "filter.sortBySize": "الفرز حسب الحجم", "filter.source": "المصدر", "filter.apply": "تطبيق",
        "filter.date.7d": "7 أيام", "filter.date.30d": "30 يومًا", "filter.date.all": "كل الأوقات",
        "filter.sort.large": "من الأكبر إلى الأصغر", "filter.sort.small": "من الأصغر إلى الأكبر",
        "filter.src.camera": "الكاميرا", "filter.src.screenshots": "لقطات الشاشة", "filter.src.download": "التنزيلات",
        "review.selectAll": "تحديد الكل", "review.deselect": "إلغاء التحديد", "review.deleteSelected": "حذف المحدد",
        "review.deleteN": "حذف %d محددة (%@)", "review.groupTitle": "%d %@",
        "review.noun.similar": "متشابهة", "review.noun.duplicates": "مكررة",
        "review.noun.screenshots": "لقطات شاشة", "review.noun.videos": "فيديوهات",
        "flow.permBody": "يحتاج التطبيق إلى الوصول إلى مكتبة صورك للعثور على الصور المتشابهة والمكررة التي يمكنك تنظيفها.",
        "flow.emptyTitle": "لا شيء للتنظيف",
        "flow.emptyBody": "لم نعثر على صور متشابهة في مكتبتك الآن.",
        "flow.deleteErrorTitle": "تعذّر الحذف",
    ]

    private static let fa: [String: String] = [
        "home.sub.similar": "دیروز", "home.sub.duplicates": "هفته گذشته", "home.sub.similarScreenshots": "امروز",
        "home.sub.similarVideos": "ماه گذشته", "home.sub.otherScreenshots": "همه زمان‌ها", "home.sub.chatPhotos": "پیام‌ها",
        "home.sub.videosOrganizer": "همه ویدیوها", "home.sub.other": "عکس‌های متفرقه",
        "common.back": "بازگشت", "common.done": "تمام",
        "filter.title": "فیلتر", "filter.clearAll": "پاک کردن همه", "filter.dateRange": "بازه تاریخ",
        "filter.sortBySize": "مرتب‌سازی بر اساس اندازه", "filter.source": "منبع", "filter.apply": "اعمال",
        "filter.date.7d": "۷ روز", "filter.date.30d": "۳۰ روز", "filter.date.all": "همه زمان‌ها",
        "filter.sort.large": "بزرگ به کوچک", "filter.sort.small": "کوچک به بزرگ",
        "filter.src.camera": "دوربین", "filter.src.screenshots": "اسکرین‌شات‌ها", "filter.src.download": "دانلودها",
        "review.selectAll": "انتخاب همه", "review.deselect": "لغو انتخاب", "review.deleteSelected": "حذف انتخاب‌شده‌ها",
        "review.deleteN": "حذف %d مورد انتخاب‌شده (%@)", "review.groupTitle": "%d %@",
        "review.noun.similar": "مشابه", "review.noun.duplicates": "تکراری",
        "review.noun.screenshots": "اسکرین‌شات", "review.noun.videos": "ویدیو",
        "flow.permBody": "برنامه برای یافتن عکس‌های مشابه و تکراری قابل پاک‌سازی به دسترسی به کتابخانه عکس شما نیاز دارد.",
        "flow.emptyTitle": "چیزی برای پاک‌سازی نیست",
        "flow.emptyBody": "در حال حاضر عکس مشابهی در کتابخانه شما پیدا نکردیم.",
        "flow.deleteErrorTitle": "حذف ممکن نشد",
    ]

    private static let id: [String: String] = [
        "home.sub.similar": "Kemarin", "home.sub.duplicates": "Minggu lalu", "home.sub.similarScreenshots": "Hari ini",
        "home.sub.similarVideos": "Bulan lalu", "home.sub.otherScreenshots": "Sepanjang waktu", "home.sub.chatPhotos": "Pesan",
        "home.sub.videosOrganizer": "Semua video", "home.sub.other": "Foto lainnya",
        "common.back": "Kembali", "common.done": "Selesai",
        "filter.title": "Filter", "filter.clearAll": "Hapus semua", "filter.dateRange": "RENTANG TANGGAL",
        "filter.sortBySize": "URUTKAN BERDASARKAN UKURAN", "filter.source": "SUMBER", "filter.apply": "Terapkan",
        "filter.date.7d": "7 hari", "filter.date.30d": "30 hari", "filter.date.all": "Sepanjang waktu",
        "filter.sort.large": "Besar ke kecil", "filter.sort.small": "Kecil ke besar",
        "filter.src.camera": "Kamera", "filter.src.screenshots": "Tangkapan layar", "filter.src.download": "Unduhan",
        "review.selectAll": "Pilih semua", "review.deselect": "Batalkan pilihan", "review.deleteSelected": "Hapus pilihan",
        "review.deleteN": "Hapus %d terpilih (%@)", "review.groupTitle": "%d %@",
        "review.noun.similar": "serupa", "review.noun.duplicates": "duplikat",
        "review.noun.screenshots": "tangkapan layar", "review.noun.videos": "video",
        "flow.permBody": "Aplikasi perlu akses ke pustaka fotomu untuk menemukan foto serupa dan duplikat yang bisa dibersihkan.",
        "flow.emptyTitle": "Tidak ada yang perlu dibersihkan",
        "flow.emptyBody": "Saat ini kami tidak menemukan foto serupa di pustakamu.",
        "flow.deleteErrorTitle": "Tidak dapat menghapus",
    ]

    private static let vi: [String: String] = [
        "home.sub.similar": "Hôm qua", "home.sub.duplicates": "Tuần trước", "home.sub.similarScreenshots": "Hôm nay",
        "home.sub.similarVideos": "Tháng trước", "home.sub.otherScreenshots": "Mọi lúc", "home.sub.chatPhotos": "Tin nhắn",
        "home.sub.videosOrganizer": "Tất cả video", "home.sub.other": "Ảnh khác",
        "common.back": "Quay lại", "common.done": "Xong",
        "filter.title": "Bộ lọc", "filter.clearAll": "Xoá tất cả", "filter.dateRange": "KHOẢNG THỜI GIAN",
        "filter.sortBySize": "SẮP XẾP THEO DUNG LƯỢNG", "filter.source": "NGUỒN", "filter.apply": "Áp dụng",
        "filter.date.7d": "7 ngày", "filter.date.30d": "30 ngày", "filter.date.all": "Mọi lúc",
        "filter.sort.large": "Lớn đến nhỏ", "filter.sort.small": "Nhỏ đến lớn",
        "filter.src.camera": "Máy ảnh", "filter.src.screenshots": "Ảnh chụp màn hình", "filter.src.download": "Tải xuống",
        "review.selectAll": "Chọn tất cả", "review.deselect": "Bỏ chọn", "review.deleteSelected": "Xoá mục đã chọn",
        "review.deleteN": "Xoá %d mục đã chọn (%@)", "review.groupTitle": "%d ảnh %@",
        "review.noun.similar": "tương tự", "review.noun.duplicates": "trùng lặp",
        "review.noun.screenshots": "ảnh màn hình", "review.noun.videos": "video",
        "flow.permBody": "Ứng dụng cần quyền truy cập thư viện ảnh để tìm ảnh tương tự và trùng lặp mà bạn có thể dọn dẹp.",
        "flow.emptyTitle": "Không có gì để dọn",
        "flow.emptyBody": "Hiện chưa tìm thấy ảnh tương tự nào trong thư viện của bạn.",
        "flow.deleteErrorTitle": "Không thể xoá",
    ]

    private static let ja: [String: String] = [
        "home.sub.similar": "昨日", "home.sub.duplicates": "先週", "home.sub.similarScreenshots": "今日",
        "home.sub.similarVideos": "先月", "home.sub.otherScreenshots": "すべての期間", "home.sub.chatPhotos": "メッセージ",
        "home.sub.videosOrganizer": "すべての動画", "home.sub.other": "その他の写真",
        "common.back": "戻る", "common.done": "完了",
        "filter.title": "フィルタ", "filter.clearAll": "すべてクリア", "filter.dateRange": "期間",
        "filter.sortBySize": "サイズ順", "filter.source": "ソース", "filter.apply": "適用",
        "filter.date.7d": "7日間", "filter.date.30d": "30日間", "filter.date.all": "すべての期間",
        "filter.sort.large": "大きい順", "filter.sort.small": "小さい順",
        "filter.src.camera": "カメラ", "filter.src.screenshots": "スクショ", "filter.src.download": "ダウンロード",
        "review.selectAll": "すべて選択", "review.deselect": "選択解除", "review.deleteSelected": "選択を削除",
        "review.deleteN": "選択した%d件を削除 (%@)", "review.groupTitle": "%@ %d件",
        "review.noun.similar": "類似", "review.noun.duplicates": "重複",
        "review.noun.screenshots": "スクショ", "review.noun.videos": "動画",
        "flow.permBody": "整理できる類似写真や重複を見つけるため、写真ライブラリへのアクセスが必要です。",
        "flow.emptyTitle": "整理するものはありません",
        "flow.emptyBody": "現在、ライブラリに類似写真は見つかりませんでした。",
        "flow.deleteErrorTitle": "削除できませんでした",
    ]

    private static let ko: [String: String] = [
        "home.sub.similar": "어제", "home.sub.duplicates": "지난주", "home.sub.similarScreenshots": "오늘",
        "home.sub.similarVideos": "지난달", "home.sub.otherScreenshots": "전체 기간", "home.sub.chatPhotos": "메시지",
        "home.sub.videosOrganizer": "모든 동영상", "home.sub.other": "기타 사진",
        "common.back": "뒤로", "common.done": "완료",
        "filter.title": "필터", "filter.clearAll": "모두 지우기", "filter.dateRange": "날짜 범위",
        "filter.sortBySize": "크기순 정렬", "filter.source": "소스", "filter.apply": "적용",
        "filter.date.7d": "7일", "filter.date.30d": "30일", "filter.date.all": "전체 기간",
        "filter.sort.large": "큰 순서", "filter.sort.small": "작은 순서",
        "filter.src.camera": "카메라", "filter.src.screenshots": "스크린샷", "filter.src.download": "다운로드",
        "review.selectAll": "모두 선택", "review.deselect": "선택 해제", "review.deleteSelected": "선택 삭제",
        "review.deleteN": "선택한 %d개 삭제 (%@)", "review.groupTitle": "%@ %d개",
        "review.noun.similar": "유사", "review.noun.duplicates": "중복",
        "review.noun.screenshots": "스크린샷", "review.noun.videos": "동영상",
        "flow.permBody": "정리할 수 있는 유사한 사진과 중복을 찾으려면 사진 보관함 접근 권한이 필요합니다.",
        "flow.emptyTitle": "정리할 항목 없음",
        "flow.emptyBody": "지금은 보관함에서 유사한 사진을 찾지 못했습니다.",
        "flow.deleteErrorTitle": "삭제할 수 없음",
    ]

    private static let zhHans: [String: String] = [
        "home.sub.similar": "昨天", "home.sub.duplicates": "上周", "home.sub.similarScreenshots": "今天",
        "home.sub.similarVideos": "上个月", "home.sub.otherScreenshots": "全部时间", "home.sub.chatPhotos": "消息",
        "home.sub.videosOrganizer": "所有视频", "home.sub.other": "其他照片",
        "common.back": "返回", "common.done": "完成",
        "filter.title": "筛选", "filter.clearAll": "全部清除", "filter.dateRange": "日期范围",
        "filter.sortBySize": "按大小排序", "filter.source": "来源", "filter.apply": "应用",
        "filter.date.7d": "7 天", "filter.date.30d": "30 天", "filter.date.all": "全部时间",
        "filter.sort.large": "从大到小", "filter.sort.small": "从小到大",
        "filter.src.camera": "相机", "filter.src.screenshots": "截图", "filter.src.download": "下载",
        "review.selectAll": "全选", "review.deselect": "取消选择", "review.deleteSelected": "删除所选",
        "review.deleteN": "删除所选 %d 项 (%@)", "review.groupTitle": "%d 张%@",
        "review.noun.similar": "相似", "review.noun.duplicates": "重复",
        "review.noun.screenshots": "截图", "review.noun.videos": "视频",
        "flow.permBody": "应用需要访问你的照片图库，以查找可清理的相似照片和重复项。",
        "flow.emptyTitle": "没有可清理的内容",
        "flow.emptyBody": "目前未在你的图库中找到相似照片。",
        "flow.deleteErrorTitle": "无法删除",
    ]

    private static let zhHant: [String: String] = [
        "home.sub.similar": "昨天", "home.sub.duplicates": "上週", "home.sub.similarScreenshots": "今天",
        "home.sub.similarVideos": "上個月", "home.sub.otherScreenshots": "全部時間", "home.sub.chatPhotos": "訊息",
        "home.sub.videosOrganizer": "所有影片", "home.sub.other": "其他照片",
        "common.back": "返回", "common.done": "完成",
        "filter.title": "篩選", "filter.clearAll": "全部清除", "filter.dateRange": "日期範圍",
        "filter.sortBySize": "依大小排序", "filter.source": "來源", "filter.apply": "套用",
        "filter.date.7d": "7 天", "filter.date.30d": "30 天", "filter.date.all": "全部時間",
        "filter.sort.large": "從大到小", "filter.sort.small": "從小到大",
        "filter.src.camera": "相機", "filter.src.screenshots": "截圖", "filter.src.download": "下載",
        "review.selectAll": "全選", "review.deselect": "取消選取", "review.deleteSelected": "刪除所選",
        "review.deleteN": "刪除所選 %d 項 (%@)", "review.groupTitle": "%d 張%@",
        "review.noun.similar": "相似", "review.noun.duplicates": "重複",
        "review.noun.screenshots": "截圖", "review.noun.videos": "影片",
        "flow.permBody": "應用程式需要存取你的照片圖庫，以尋找可清理的相似照片和重複項目。",
        "flow.emptyTitle": "沒有可清理的內容",
        "flow.emptyBody": "目前未在你的圖庫中找到相似照片。",
        "flow.deleteErrorTitle": "無法刪除",
    ]
}
