import Foundation

// Translation table: [languageKey: [stringKey: value]]. Language keys are produced
// by Localizer.langKey(for:) and cover every entry in the in-app picker. Add keys
// here as more screens are localized; missing keys fall back to English.
//
// Phase 1 covers: Tab bar, Language screen, Settings. ("Cleaner Ultimate" and "FAQ"
// are product/proper names kept identical across languages.)
enum LocalizedStrings {
    static let table: [String: [String: String]] = [
        "en": [
            "tab.home": "Home", "tab.vault": "Vault", "tab.contacts": "Contacts", "tab.compress": "Compress",
            "lang.title": "Language", "lang.selected": "Selected", "lang.all": "All language",
            "lang.search": "Enter name of Language...", "lang.start": "Let’s Start",
            "settings.title": "Settings", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "Instantly Detect Similar Photos",
            "settings.feature.noads": "No Ads and Limits",
            "settings.feature.storage": "Save Both Storage & Time",
            "settings.getPremium": "Get Premium", "settings.stayInTouch": "Stay in Touch",
            "settings.share": "Share Cleanup", "settings.rate": "Rate Us", "settings.language": "Language",
            "settings.support": "Support", "settings.faq": "FAQ", "settings.contact": "Contact Us",
            "settings.restore": "Restore Purchase", "settings.terms": "Terms of Service",
            "settings.privacy": "Privacy Policy",
        ],
        "es": [
            "tab.home": "Inicio", "tab.vault": "Bóveda", "tab.contacts": "Contactos", "tab.compress": "Comprimir",
            "lang.title": "Idioma", "lang.selected": "Seleccionado", "lang.all": "Todos los idiomas",
            "lang.search": "Escribe el nombre del idioma...", "lang.start": "Comenzar",
            "settings.title": "Ajustes", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "Detecta fotos similares al instante",
            "settings.feature.noads": "Sin anuncios ni límites",
            "settings.feature.storage": "Ahorra almacenamiento y tiempo",
            "settings.getPremium": "Obtener Premium", "settings.stayInTouch": "Mantente en contacto",
            "settings.share": "Compartir la app", "settings.rate": "Califícanos", "settings.language": "Idioma",
            "settings.support": "Soporte", "settings.faq": "FAQ", "settings.contact": "Contáctanos",
            "settings.restore": "Restaurar compra", "settings.terms": "Términos del servicio",
            "settings.privacy": "Política de privacidad",
        ],
        "pt": [
            "tab.home": "Início", "tab.vault": "Cofre", "tab.contacts": "Contatos", "tab.compress": "Comprimir",
            "lang.title": "Idioma", "lang.selected": "Selecionado", "lang.all": "Todos os idiomas",
            "lang.search": "Digite o nome do idioma...", "lang.start": "Começar",
            "settings.title": "Configurações", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "Detecte fotos semelhantes na hora",
            "settings.feature.noads": "Sem anúncios e limites",
            "settings.feature.storage": "Economize armazenamento e tempo",
            "settings.getPremium": "Obter Premium", "settings.stayInTouch": "Fique por dentro",
            "settings.share": "Compartilhar app", "settings.rate": "Avalie-nos", "settings.language": "Idioma",
            "settings.support": "Suporte", "settings.faq": "FAQ", "settings.contact": "Fale conosco",
            "settings.restore": "Restaurar compra", "settings.terms": "Termos de serviço",
            "settings.privacy": "Política de privacidade",
        ],
        "fr": [
            "tab.home": "Accueil", "tab.vault": "Coffre", "tab.contacts": "Contacts", "tab.compress": "Compresser",
            "lang.title": "Langue", "lang.selected": "Sélectionné", "lang.all": "Toutes les langues",
            "lang.search": "Entrez le nom de la langue...", "lang.start": "Commencer",
            "settings.title": "Réglages", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "Détectez les photos similaires instantanément",
            "settings.feature.noads": "Sans pubs ni limites",
            "settings.feature.storage": "Gagnez du stockage et du temps",
            "settings.getPremium": "Passer Premium", "settings.stayInTouch": "Restez en contact",
            "settings.share": "Partager l’app", "settings.rate": "Évaluez-nous", "settings.language": "Langue",
            "settings.support": "Assistance", "settings.faq": "FAQ", "settings.contact": "Nous contacter",
            "settings.restore": "Restaurer l’achat", "settings.terms": "Conditions d’utilisation",
            "settings.privacy": "Politique de confidentialité",
        ],
        "de": [
            "tab.home": "Start", "tab.vault": "Tresor", "tab.contacts": "Kontakte", "tab.compress": "Komprimieren",
            "lang.title": "Sprache", "lang.selected": "Ausgewählt", "lang.all": "Alle Sprachen",
            "lang.search": "Sprachnamen eingeben...", "lang.start": "Loslegen",
            "settings.title": "Einstellungen", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "Ähnliche Fotos sofort erkennen",
            "settings.feature.noads": "Keine Werbung und Limits",
            "settings.feature.storage": "Speicher und Zeit sparen",
            "settings.getPremium": "Premium holen", "settings.stayInTouch": "In Kontakt bleiben",
            "settings.share": "App teilen", "settings.rate": "Bewerten", "settings.language": "Sprache",
            "settings.support": "Support", "settings.faq": "FAQ", "settings.contact": "Kontakt",
            "settings.restore": "Kauf wiederherstellen", "settings.terms": "Nutzungsbedingungen",
            "settings.privacy": "Datenschutzrichtlinie",
        ],
        "it": [
            "tab.home": "Home", "tab.vault": "Cassaforte", "tab.contacts": "Contatti", "tab.compress": "Comprimi",
            "lang.title": "Lingua", "lang.selected": "Selezionata", "lang.all": "Tutte le lingue",
            "lang.search": "Inserisci il nome della lingua...", "lang.start": "Inizia",
            "settings.title": "Impostazioni", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "Rileva subito le foto simili",
            "settings.feature.noads": "Senza pubblicità e limiti",
            "settings.feature.storage": "Risparmia spazio e tempo",
            "settings.getPremium": "Passa a Premium", "settings.stayInTouch": "Resta in contatto",
            "settings.share": "Condividi l’app", "settings.rate": "Valutaci", "settings.language": "Lingua",
            "settings.support": "Supporto", "settings.faq": "FAQ", "settings.contact": "Contattaci",
            "settings.restore": "Ripristina acquisto", "settings.terms": "Termini di servizio",
            "settings.privacy": "Informativa sulla privacy",
        ],
        "nl": [
            "tab.home": "Start", "tab.vault": "Kluis", "tab.contacts": "Contacten", "tab.compress": "Comprimeren",
            "lang.title": "Taal", "lang.selected": "Geselecteerd", "lang.all": "Alle talen",
            "lang.search": "Voer de naam van de taal in...", "lang.start": "Beginnen",
            "settings.title": "Instellingen", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "Vind direct vergelijkbare foto’s",
            "settings.feature.noads": "Geen advertenties en limieten",
            "settings.feature.storage": "Bespaar opslag en tijd",
            "settings.getPremium": "Premium halen", "settings.stayInTouch": "Blijf in contact",
            "settings.share": "App delen", "settings.rate": "Beoordeel ons", "settings.language": "Taal",
            "settings.support": "Ondersteuning", "settings.faq": "FAQ", "settings.contact": "Contact",
            "settings.restore": "Aankoop herstellen", "settings.terms": "Servicevoorwaarden",
            "settings.privacy": "Privacybeleid",
        ],
        "tr": [
            "tab.home": "Ana Sayfa", "tab.vault": "Kasa", "tab.contacts": "Kişiler", "tab.compress": "Sıkıştır",
            "lang.title": "Dil", "lang.selected": "Seçili", "lang.all": "Tüm diller",
            "lang.search": "Dil adını girin...", "lang.start": "Başla",
            "settings.title": "Ayarlar", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "Benzer fotoğrafları anında bul",
            "settings.feature.noads": "Reklam ve sınır yok",
            "settings.feature.storage": "Hem depolama hem zaman kazan",
            "settings.getPremium": "Premium Al", "settings.stayInTouch": "İletişimde kal",
            "settings.share": "Uygulamayı paylaş", "settings.rate": "Bizi değerlendir", "settings.language": "Dil",
            "settings.support": "Destek", "settings.faq": "FAQ", "settings.contact": "Bize ulaşın",
            "settings.restore": "Satın almayı geri yükle", "settings.terms": "Hizmet şartları",
            "settings.privacy": "Gizlilik politikası",
        ],
        "uk": [
            "tab.home": "Головна", "tab.vault": "Сейф", "tab.contacts": "Контакти", "tab.compress": "Стиснути",
            "lang.title": "Мова", "lang.selected": "Вибрано", "lang.all": "Усі мови",
            "lang.search": "Введіть назву мови...", "lang.start": "Почати",
            "settings.title": "Налаштування", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "Миттєво знаходьте схожі фото",
            "settings.feature.noads": "Без реклами та обмежень",
            "settings.feature.storage": "Заощаджуйте пам’ять і час",
            "settings.getPremium": "Отримати Premium", "settings.stayInTouch": "Залишайтеся на зв’язку",
            "settings.share": "Поділитися застосунком", "settings.rate": "Оцініть нас", "settings.language": "Мова",
            "settings.support": "Підтримка", "settings.faq": "FAQ", "settings.contact": "Зв’язатися з нами",
            "settings.restore": "Відновити покупку", "settings.terms": "Умови використання",
            "settings.privacy": "Політика конфіденційності",
        ],
        "ru": [
            "tab.home": "Главная", "tab.vault": "Сейф", "tab.contacts": "Контакты", "tab.compress": "Сжать",
            "lang.title": "Язык", "lang.selected": "Выбрано", "lang.all": "Все языки",
            "lang.search": "Введите название языка...", "lang.start": "Начать",
            "settings.title": "Настройки", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "Мгновенно находите похожие фото",
            "settings.feature.noads": "Без рекламы и ограничений",
            "settings.feature.storage": "Экономьте память и время",
            "settings.getPremium": "Получить Premium", "settings.stayInTouch": "Оставайтесь на связи",
            "settings.share": "Поделиться приложением", "settings.rate": "Оцените нас", "settings.language": "Язык",
            "settings.support": "Поддержка", "settings.faq": "FAQ", "settings.contact": "Связаться с нами",
            "settings.restore": "Восстановить покупку", "settings.terms": "Условия использования",
            "settings.privacy": "Политика конфиденциальности",
        ],
        "he": [
            "tab.home": "בית", "tab.vault": "כספת", "tab.contacts": "אנשי קשר", "tab.compress": "כיווץ",
            "lang.title": "שפה", "lang.selected": "נבחר", "lang.all": "כל השפות",
            "lang.search": "הזינו שם של שפה...", "lang.start": "בואו נתחיל",
            "settings.title": "הגדרות", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "זיהוי מיידי של תמונות דומות",
            "settings.feature.noads": "ללא פרסומות והגבלות",
            "settings.feature.storage": "חיסכון באחסון ובזמן",
            "settings.getPremium": "קבלת פרימיום", "settings.stayInTouch": "נשארים בקשר",
            "settings.share": "שיתוף האפליקציה", "settings.rate": "דרגו אותנו", "settings.language": "שפה",
            "settings.support": "תמיכה", "settings.faq": "FAQ", "settings.contact": "צרו קשר",
            "settings.restore": "שחזור רכישה", "settings.terms": "תנאי שימוש",
            "settings.privacy": "מדיניות פרטיות",
        ],
        "ar": [
            "tab.home": "الرئيسية", "tab.vault": "الخزنة", "tab.contacts": "جهات الاتصال", "tab.compress": "ضغط",
            "lang.title": "اللغة", "lang.selected": "المحددة", "lang.all": "كل اللغات",
            "lang.search": "أدخل اسم اللغة...", "lang.start": "لنبدأ",
            "settings.title": "الإعدادات", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "اكتشف الصور المتشابهة فورًا",
            "settings.feature.noads": "بلا إعلانات ولا قيود",
            "settings.feature.storage": "وفّر المساحة والوقت",
            "settings.getPremium": "احصل على بريميوم", "settings.stayInTouch": "ابقَ على تواصل",
            "settings.share": "مشاركة التطبيق", "settings.rate": "قيّمنا", "settings.language": "اللغة",
            "settings.support": "الدعم", "settings.faq": "FAQ", "settings.contact": "تواصل معنا",
            "settings.restore": "استعادة الشراء", "settings.terms": "شروط الخدمة",
            "settings.privacy": "سياسة الخصوصية",
        ],
        "fa": [
            "tab.home": "خانه", "tab.vault": "گاوصندوق", "tab.contacts": "مخاطبین", "tab.compress": "فشرده‌سازی",
            "lang.title": "زبان", "lang.selected": "انتخاب‌شده", "lang.all": "همه زبان‌ها",
            "lang.search": "نام زبان را وارد کنید...", "lang.start": "شروع کنیم",
            "settings.title": "تنظیمات", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "تشخیص فوری عکس‌های مشابه",
            "settings.feature.noads": "بدون تبلیغات و محدودیت",
            "settings.feature.storage": "صرفه‌جویی در فضا و زمان",
            "settings.getPremium": "تهیه نسخه ویژه", "settings.stayInTouch": "در ارتباط بمانید",
            "settings.share": "اشتراک‌گذاری برنامه", "settings.rate": "به ما امتیاز دهید", "settings.language": "زبان",
            "settings.support": "پشتیبانی", "settings.faq": "FAQ", "settings.contact": "تماس با ما",
            "settings.restore": "بازیابی خرید", "settings.terms": "شرایط استفاده",
            "settings.privacy": "سیاست حفظ حریم خصوصی",
        ],
        "id": [
            "tab.home": "Beranda", "tab.vault": "Brankas", "tab.contacts": "Kontak", "tab.compress": "Kompres",
            "lang.title": "Bahasa", "lang.selected": "Dipilih", "lang.all": "Semua bahasa",
            "lang.search": "Masukkan nama bahasa...", "lang.start": "Mulai",
            "settings.title": "Pengaturan", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "Deteksi foto serupa secara instan",
            "settings.feature.noads": "Tanpa iklan dan batasan",
            "settings.feature.storage": "Hemat penyimpanan & waktu",
            "settings.getPremium": "Dapatkan Premium", "settings.stayInTouch": "Tetap terhubung",
            "settings.share": "Bagikan aplikasi", "settings.rate": "Beri nilai", "settings.language": "Bahasa",
            "settings.support": "Dukungan", "settings.faq": "FAQ", "settings.contact": "Hubungi kami",
            "settings.restore": "Pulihkan pembelian", "settings.terms": "Ketentuan layanan",
            "settings.privacy": "Kebijakan privasi",
        ],
        "vi": [
            "tab.home": "Trang chủ", "tab.vault": "Kho bảo mật", "tab.contacts": "Danh bạ", "tab.compress": "Nén",
            "lang.title": "Ngôn ngữ", "lang.selected": "Đã chọn", "lang.all": "Tất cả ngôn ngữ",
            "lang.search": "Nhập tên ngôn ngữ...", "lang.start": "Bắt đầu",
            "settings.title": "Cài đặt", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "Phát hiện ảnh trùng lặp tức thì",
            "settings.feature.noads": "Không quảng cáo & giới hạn",
            "settings.feature.storage": "Tiết kiệm dung lượng & thời gian",
            "settings.getPremium": "Nâng cấp Premium", "settings.stayInTouch": "Giữ liên lạc",
            "settings.share": "Chia sẻ ứng dụng", "settings.rate": "Đánh giá", "settings.language": "Ngôn ngữ",
            "settings.support": "Hỗ trợ", "settings.faq": "FAQ", "settings.contact": "Liên hệ",
            "settings.restore": "Khôi phục giao dịch", "settings.terms": "Điều khoản dịch vụ",
            "settings.privacy": "Chính sách bảo mật",
        ],
        "ja": [
            "tab.home": "ホーム", "tab.vault": "金庫", "tab.contacts": "連絡先", "tab.compress": "圧縮",
            "lang.title": "言語", "lang.selected": "選択中", "lang.all": "すべての言語",
            "lang.search": "言語名を入力...", "lang.start": "はじめる",
            "settings.title": "設定", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "似た写真をすぐに検出",
            "settings.feature.noads": "広告も制限もなし",
            "settings.feature.storage": "容量も時間も節約",
            "settings.getPremium": "プレミアムを取得", "settings.stayInTouch": "つながる",
            "settings.share": "アプリを共有", "settings.rate": "評価する", "settings.language": "言語",
            "settings.support": "サポート", "settings.faq": "FAQ", "settings.contact": "お問い合わせ",
            "settings.restore": "購入を復元", "settings.terms": "利用規約",
            "settings.privacy": "プライバシーポリシー",
        ],
        "ko": [
            "tab.home": "홈", "tab.vault": "보관함", "tab.contacts": "연락처", "tab.compress": "압축",
            "lang.title": "언어", "lang.selected": "선택됨", "lang.all": "모든 언어",
            "lang.search": "언어 이름 입력...", "lang.start": "시작하기",
            "settings.title": "설정", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "유사한 사진 즉시 감지",
            "settings.feature.noads": "광고와 제한 없음",
            "settings.feature.storage": "저장 공간과 시간 절약",
            "settings.getPremium": "프리미엄 받기", "settings.stayInTouch": "소통하기",
            "settings.share": "앱 공유", "settings.rate": "평가하기", "settings.language": "언어",
            "settings.support": "지원", "settings.faq": "FAQ", "settings.contact": "문의하기",
            "settings.restore": "구매 복원", "settings.terms": "서비스 약관",
            "settings.privacy": "개인정보 처리방침",
        ],
        "zh-Hans": [
            "tab.home": "首页", "tab.vault": "保险库", "tab.contacts": "通讯录", "tab.compress": "压缩",
            "lang.title": "语言", "lang.selected": "已选择", "lang.all": "所有语言",
            "lang.search": "输入语言名称...", "lang.start": "开始",
            "settings.title": "设置", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "即时检测相似照片",
            "settings.feature.noads": "无广告无限制",
            "settings.feature.storage": "节省空间和时间",
            "settings.getPremium": "获取高级版", "settings.stayInTouch": "保持联系",
            "settings.share": "分享应用", "settings.rate": "给我们评分", "settings.language": "语言",
            "settings.support": "支持", "settings.faq": "FAQ", "settings.contact": "联系我们",
            "settings.restore": "恢复购买", "settings.terms": "服务条款",
            "settings.privacy": "隐私政策",
        ],
        "zh-Hant": [
            "tab.home": "首頁", "tab.vault": "保險庫", "tab.contacts": "通訊錄", "tab.compress": "壓縮",
            "lang.title": "語言", "lang.selected": "已選擇", "lang.all": "所有語言",
            "lang.search": "輸入語言名稱...", "lang.start": "開始",
            "settings.title": "設定", "settings.ultimate": "Cleaner Ultimate",
            "settings.feature.similar": "即時偵測相似照片",
            "settings.feature.noads": "無廣告無限制",
            "settings.feature.storage": "節省空間與時間",
            "settings.getPremium": "取得進階版", "settings.stayInTouch": "保持聯絡",
            "settings.share": "分享應用程式", "settings.rate": "為我們評分", "settings.language": "語言",
            "settings.support": "支援", "settings.faq": "FAQ", "settings.contact": "聯絡我們",
            "settings.restore": "還原購買", "settings.terms": "服務條款",
            "settings.privacy": "隱私權政策",
        ],
    ]
}
