import Foundation

// Third translation table (Localizer checks all three). Covers the Contacts tab
// (dashboard + Duplicates/Incomplete/All/Backups + permission gate) and the
// Contact Us form. Kept separate so each language constant stays small.
enum LocalizedStrings3 {
    static let table: [String: [String: String]] = [
        "en": en, "es": es, "pt": pt, "fr": fr, "de": de, "it": it, "nl": nl,
        "tr": tr, "uk": uk, "ru": ru, "he": he, "ar": ar, "fa": fa, "id": id,
        "vi": vi, "ja": ja, "ko": ko, "zh-Hans": zhHans, "zh-Hant": zhHant,
    ]

    private static let en: [String: String] = [
        "contacts.card.duplicates": "Duplicates", "contacts.card.incomplete": "Incomplete contacts",
        "contacts.card.backup": "Backup", "contacts.card.all": "All contacts",
        "contacts.desc.duplicates": "Merge or delete duplicate…", "contacts.desc.incomplete": "Contacts missing name, phone…",
        "contacts.desc.backup": "Save and restore contacts when…", "contacts.desc.all": "View all contacts on device.",
        "contacts.count.duplicates": "%d duplicate groups", "contacts.count.incomplete": "%d contacts to check",
        "contacts.count.backups": "%d backups", "contacts.count": "%d contacts",
        "contacts.noName": "No name", "contacts.noNumber": "No number", "contacts.unknown": "Unknown",
        "contacts.selectAll": "Select all", "contacts.deselectAll": "Deselect all", "contacts.selectGroup": "Select group",
        "contacts.deleteSelected": "Delete selected", "contacts.deleteN": "Delete %d selected",
        "contacts.dup.title": "Duplicate Contacts", "contacts.dup.scanning": "Scanning for duplicates…",
        "contacts.dup.emptyTitle": "No duplicates found", "contacts.dup.emptyBody": "Your contacts look clean.",
        "contacts.dup.groupCount": "%d duplicate contacts", "contacts.dup.merge": "Merge contacts",
        "contacts.merged.title": "Contacts merged", "contacts.merged.one": "Merged into \"%@\".",
        "contacts.merged.many": "Merged into: %@",
        "contacts.inc.title": "Incomplete Contacts", "contacts.inc.missingName": "Missing contact name",
        "contacts.inc.missingPhone": "Missing phone number", "contacts.inc.missingBoth": "Missing name & phone number",
        "contacts.inc.edit": "Edit contacts", "contacts.inc.emptyTitle": "All contacts look complete",
        "contacts.inc.unnamed": "Unnamed contact",
        "contacts.all.title": "All Contacts", "contacts.all.search": "Search contacts",
        "contacts.backups.title": "Backups", "contacts.backups.count": "%d Backups", "contacts.backups.create": "Create backup",
        "contacts.backups.item": "Backup", "contacts.backups.restore": "Restore %d contacts", "contacts.backups.delete": "Delete backup",
        "contacts.backups.errorTitle": "Backup error", "contacts.backups.restoredTitle": "Restored",
        "contacts.backups.backing": "Backing up contacts…", "contacts.backups.emptyTitle": "No backups yet",
        "contacts.backups.emptyBody": "Tap Create backup to save a snapshot of every contact as a vCard file on this device.",
        "contacts.backups.restoredMsg": "Restored %d contacts",
        "contacts.permTitle": "Contacts access required",
        "contacts.permBody": "The app reads your contacts to find duplicates, incomplete entries, and back them up safely.",
        "contacts.somethingWrong": "Something went wrong",
        "contact.title": "Contact Us", "contact.hero": "Get in touch",
        "contact.intro": "We’d love to hear from you. Send us a message and we’ll respond as soon as possible.",
        "contact.name": "Name", "contact.namePh": "Enter your name", "contact.email": "Email Address",
        "contact.emailPh": "Enter your email address", "contact.message": "Your Message", "contact.send": "Send Message",
        "contact.errorTitle": "Couldn’t send", "contact.noMail": "No mail account is configured. Please email us directly at %@.",
    ]

    private static let es: [String: String] = [
        "contacts.card.duplicates": "Duplicados", "contacts.card.incomplete": "Contactos incompletos",
        "contacts.card.backup": "Copia de seguridad", "contacts.card.all": "Todos los contactos",
        "contacts.desc.duplicates": "Combina o elimina duplicados…", "contacts.desc.incomplete": "Contactos sin nombre, teléfono…",
        "contacts.desc.backup": "Guarda y restaura contactos cuando…", "contacts.desc.all": "Ver todos los contactos del dispositivo.",
        "contacts.count.duplicates": "%d grupos duplicados", "contacts.count.incomplete": "%d contactos por revisar",
        "contacts.count.backups": "%d copias", "contacts.count": "%d contactos",
        "contacts.noName": "Sin nombre", "contacts.noNumber": "Sin número", "contacts.unknown": "Desconocido",
        "contacts.selectAll": "Seleccionar todo", "contacts.deselectAll": "Deseleccionar todo", "contacts.selectGroup": "Seleccionar grupo",
        "contacts.deleteSelected": "Eliminar selección", "contacts.deleteN": "Eliminar %d seleccionados",
        "contacts.dup.title": "Contactos duplicados", "contacts.dup.scanning": "Buscando duplicados…",
        "contacts.dup.emptyTitle": "No se encontraron duplicados", "contacts.dup.emptyBody": "Tus contactos están limpios.",
        "contacts.dup.groupCount": "%d contactos duplicados", "contacts.dup.merge": "Combinar contactos",
        "contacts.inc.title": "Contactos incompletos", "contacts.inc.missingName": "Falta el nombre",
        "contacts.inc.missingPhone": "Falta el número", "contacts.inc.missingBoth": "Falta nombre y número",
        "contacts.inc.edit": "Editar contactos", "contacts.inc.emptyTitle": "Todos los contactos están completos",
        "contacts.inc.unnamed": "Contacto sin nombre",
        "contacts.all.title": "Todos los contactos", "contacts.all.search": "Buscar contactos",
        "contacts.backups.title": "Copias", "contacts.backups.count": "%d copias", "contacts.backups.create": "Crear copia",
        "contacts.backups.item": "Copia", "contacts.backups.restore": "Restaurar %d contactos", "contacts.backups.delete": "Eliminar copia",
        "contacts.backups.errorTitle": "Error de copia", "contacts.backups.restoredTitle": "Restaurado",
        "contacts.backups.backing": "Creando copia de contactos…", "contacts.backups.emptyTitle": "Aún no hay copias",
        "contacts.backups.emptyBody": "Toca Crear copia para guardar una instantánea de cada contacto como archivo vCard en este dispositivo.",
        "contacts.backups.restoredMsg": "Se restauraron %d contactos",
        "contacts.permTitle": "Se requiere acceso a Contactos",
        "contacts.permBody": "La app lee tus contactos para encontrar duplicados, entradas incompletas y respaldarlos de forma segura.",
        "contacts.somethingWrong": "Algo salió mal",
        "contact.title": "Contáctanos", "contact.hero": "Ponte en contacto",
        "contact.intro": "Nos encantaría saber de ti. Envíanos un mensaje y responderemos lo antes posible.",
        "contact.name": "Nombre", "contact.namePh": "Escribe tu nombre", "contact.email": "Correo electrónico",
        "contact.emailPh": "Escribe tu correo", "contact.message": "Tu mensaje", "contact.send": "Enviar mensaje",
        "contact.errorTitle": "No se pudo enviar", "contact.noMail": "No hay una cuenta de correo configurada. Escríbenos directamente a %@.",
    ]

    private static let pt: [String: String] = [
        "contacts.card.duplicates": "Duplicados", "contacts.card.incomplete": "Contatos incompletos",
        "contacts.card.backup": "Backup", "contacts.card.all": "Todos os contatos",
        "contacts.desc.duplicates": "Mesclar ou excluir duplicados…", "contacts.desc.incomplete": "Contatos sem nome, telefone…",
        "contacts.desc.backup": "Salve e restaure contatos quando…", "contacts.desc.all": "Ver todos os contatos do dispositivo.",
        "contacts.count.duplicates": "%d grupos duplicados", "contacts.count.incomplete": "%d contatos para verificar",
        "contacts.count.backups": "%d backups", "contacts.count": "%d contatos",
        "contacts.noName": "Sem nome", "contacts.noNumber": "Sem número", "contacts.unknown": "Desconhecido",
        "contacts.selectAll": "Selecionar tudo", "contacts.deselectAll": "Desmarcar tudo", "contacts.selectGroup": "Selecionar grupo",
        "contacts.deleteSelected": "Excluir seleção", "contacts.deleteN": "Excluir %d selecionados",
        "contacts.dup.title": "Contatos duplicados", "contacts.dup.scanning": "Procurando duplicados…",
        "contacts.dup.emptyTitle": "Nenhum duplicado encontrado", "contacts.dup.emptyBody": "Seus contatos estão limpos.",
        "contacts.dup.groupCount": "%d contatos duplicados", "contacts.dup.merge": "Mesclar contatos",
        "contacts.inc.title": "Contatos incompletos", "contacts.inc.missingName": "Falta o nome",
        "contacts.inc.missingPhone": "Falta o número", "contacts.inc.missingBoth": "Falta nome e número",
        "contacts.inc.edit": "Editar contatos", "contacts.inc.emptyTitle": "Todos os contatos estão completos",
        "contacts.inc.unnamed": "Contato sem nome",
        "contacts.all.title": "Todos os contatos", "contacts.all.search": "Buscar contatos",
        "contacts.backups.title": "Backups", "contacts.backups.count": "%d backups", "contacts.backups.create": "Criar backup",
        "contacts.backups.item": "Backup", "contacts.backups.restore": "Restaurar %d contatos", "contacts.backups.delete": "Excluir backup",
        "contacts.backups.errorTitle": "Erro de backup", "contacts.backups.restoredTitle": "Restaurado",
        "contacts.backups.backing": "Fazendo backup dos contatos…", "contacts.backups.emptyTitle": "Ainda sem backups",
        "contacts.backups.emptyBody": "Toque em Criar backup para salvar uma cópia de cada contato como arquivo vCard neste dispositivo.",
        "contacts.backups.restoredMsg": "%d contatos restaurados",
        "contacts.permTitle": "Acesso aos Contatos necessário",
        "contacts.permBody": "O app lê seus contatos para encontrar duplicados, entradas incompletas e fazer backup com segurança.",
        "contacts.somethingWrong": "Algo deu errado",
        "contact.title": "Fale conosco", "contact.hero": "Entre em contato",
        "contact.intro": "Adoraríamos ouvir você. Envie uma mensagem e responderemos o quanto antes.",
        "contact.name": "Nome", "contact.namePh": "Digite seu nome", "contact.email": "E-mail",
        "contact.emailPh": "Digite seu e-mail", "contact.message": "Sua mensagem", "contact.send": "Enviar mensagem",
        "contact.errorTitle": "Não foi possível enviar", "contact.noMail": "Nenhuma conta de e-mail configurada. Escreva diretamente para %@.",
    ]

    private static let fr: [String: String] = [
        "contacts.card.duplicates": "Doublons", "contacts.card.incomplete": "Contacts incomplets",
        "contacts.card.backup": "Sauvegarde", "contacts.card.all": "Tous les contacts",
        "contacts.desc.duplicates": "Fusionner ou supprimer les doublons…", "contacts.desc.incomplete": "Contacts sans nom, téléphone…",
        "contacts.desc.backup": "Sauvegardez et restaurez les contacts quand…", "contacts.desc.all": "Voir tous les contacts de l’appareil.",
        "contacts.count.duplicates": "%d groupes de doublons", "contacts.count.incomplete": "%d contacts à vérifier",
        "contacts.count.backups": "%d sauvegardes", "contacts.count": "%d contacts",
        "contacts.noName": "Sans nom", "contacts.noNumber": "Sans numéro", "contacts.unknown": "Inconnu",
        "contacts.selectAll": "Tout sélectionner", "contacts.deselectAll": "Tout désélectionner", "contacts.selectGroup": "Sélectionner le groupe",
        "contacts.deleteSelected": "Supprimer la sélection", "contacts.deleteN": "Supprimer %d sélectionnés",
        "contacts.dup.title": "Contacts en double", "contacts.dup.scanning": "Recherche de doublons…",
        "contacts.dup.emptyTitle": "Aucun doublon trouvé", "contacts.dup.emptyBody": "Vos contacts sont propres.",
        "contacts.dup.groupCount": "%d contacts en double", "contacts.dup.merge": "Fusionner les contacts",
        "contacts.inc.title": "Contacts incomplets", "contacts.inc.missingName": "Nom manquant",
        "contacts.inc.missingPhone": "Numéro manquant", "contacts.inc.missingBoth": "Nom et numéro manquants",
        "contacts.inc.edit": "Modifier les contacts", "contacts.inc.emptyTitle": "Tous les contacts sont complets",
        "contacts.inc.unnamed": "Contact sans nom",
        "contacts.all.title": "Tous les contacts", "contacts.all.search": "Rechercher des contacts",
        "contacts.backups.title": "Sauvegardes", "contacts.backups.count": "%d sauvegardes", "contacts.backups.create": "Créer une sauvegarde",
        "contacts.backups.item": "Sauvegarde", "contacts.backups.restore": "Restaurer %d contacts", "contacts.backups.delete": "Supprimer la sauvegarde",
        "contacts.backups.errorTitle": "Erreur de sauvegarde", "contacts.backups.restoredTitle": "Restauré",
        "contacts.backups.backing": "Sauvegarde des contacts…", "contacts.backups.emptyTitle": "Aucune sauvegarde",
        "contacts.backups.emptyBody": "Touchez Créer une sauvegarde pour enregistrer une copie de chaque contact en fichier vCard sur cet appareil.",
        "contacts.backups.restoredMsg": "%d contacts restaurés",
        "contacts.permTitle": "Accès aux Contacts requis",
        "contacts.permBody": "L’app lit vos contacts pour trouver les doublons, les entrées incomplètes et les sauvegarder en toute sécurité.",
        "contacts.somethingWrong": "Une erreur est survenue",
        "contact.title": "Nous contacter", "contact.hero": "Prenez contact",
        "contact.intro": "Nous serions ravis de vous lire. Envoyez-nous un message et nous répondrons dès que possible.",
        "contact.name": "Nom", "contact.namePh": "Entrez votre nom", "contact.email": "Adresse e-mail",
        "contact.emailPh": "Entrez votre e-mail", "contact.message": "Votre message", "contact.send": "Envoyer le message",
        "contact.errorTitle": "Envoi impossible", "contact.noMail": "Aucun compte e-mail configuré. Écrivez-nous directement à %@.",
    ]

    private static let de: [String: String] = [
        "contacts.card.duplicates": "Duplikate", "contacts.card.incomplete": "Unvollständige Kontakte",
        "contacts.card.backup": "Backup", "contacts.card.all": "Alle Kontakte",
        "contacts.desc.duplicates": "Duplikate zusammenführen oder löschen…", "contacts.desc.incomplete": "Kontakte ohne Name, Telefon…",
        "contacts.desc.backup": "Kontakte sichern und wiederherstellen, wenn…", "contacts.desc.all": "Alle Kontakte auf dem Gerät ansehen.",
        "contacts.count.duplicates": "%d Duplikatgruppen", "contacts.count.incomplete": "%d Kontakte zu prüfen",
        "contacts.count.backups": "%d Backups", "contacts.count": "%d Kontakte",
        "contacts.noName": "Kein Name", "contacts.noNumber": "Keine Nummer", "contacts.unknown": "Unbekannt",
        "contacts.selectAll": "Alle auswählen", "contacts.deselectAll": "Auswahl aufheben", "contacts.selectGroup": "Gruppe auswählen",
        "contacts.deleteSelected": "Auswahl löschen", "contacts.deleteN": "%d ausgewählte löschen",
        "contacts.dup.title": "Doppelte Kontakte", "contacts.dup.scanning": "Suche nach Duplikaten…",
        "contacts.dup.emptyTitle": "Keine Duplikate gefunden", "contacts.dup.emptyBody": "Deine Kontakte sind sauber.",
        "contacts.dup.groupCount": "%d doppelte Kontakte", "contacts.dup.merge": "Kontakte zusammenführen",
        "contacts.inc.title": "Unvollständige Kontakte", "contacts.inc.missingName": "Name fehlt",
        "contacts.inc.missingPhone": "Nummer fehlt", "contacts.inc.missingBoth": "Name und Nummer fehlen",
        "contacts.inc.edit": "Kontakte bearbeiten", "contacts.inc.emptyTitle": "Alle Kontakte sind vollständig",
        "contacts.inc.unnamed": "Unbenannter Kontakt",
        "contacts.all.title": "Alle Kontakte", "contacts.all.search": "Kontakte suchen",
        "contacts.backups.title": "Backups", "contacts.backups.count": "%d Backups", "contacts.backups.create": "Backup erstellen",
        "contacts.backups.item": "Backup", "contacts.backups.restore": "%d Kontakte wiederherstellen", "contacts.backups.delete": "Backup löschen",
        "contacts.backups.errorTitle": "Backup-Fehler", "contacts.backups.restoredTitle": "Wiederhergestellt",
        "contacts.backups.backing": "Kontakte werden gesichert…", "contacts.backups.emptyTitle": "Noch keine Backups",
        "contacts.backups.emptyBody": "Tippe auf Backup erstellen, um jeden Kontakt als vCard-Datei auf diesem Gerät zu sichern.",
        "contacts.backups.restoredMsg": "%d Kontakte wiederhergestellt",
        "contacts.permTitle": "Kontaktzugriff erforderlich",
        "contacts.permBody": "Die App liest deine Kontakte, um Duplikate und unvollständige Einträge zu finden und sie sicher zu sichern.",
        "contacts.somethingWrong": "Etwas ist schiefgelaufen",
        "contact.title": "Kontakt", "contact.hero": "Kontakt aufnehmen",
        "contact.intro": "Wir freuen uns von dir zu hören. Sende uns eine Nachricht und wir antworten so schnell wie möglich.",
        "contact.name": "Name", "contact.namePh": "Namen eingeben", "contact.email": "E-Mail-Adresse",
        "contact.emailPh": "E-Mail eingeben", "contact.message": "Deine Nachricht", "contact.send": "Nachricht senden",
        "contact.errorTitle": "Senden fehlgeschlagen", "contact.noMail": "Kein E-Mail-Konto eingerichtet. Schreib uns direkt an %@.",
    ]

    private static let it: [String: String] = [
        "contacts.card.duplicates": "Duplicati", "contacts.card.incomplete": "Contatti incompleti",
        "contacts.card.backup": "Backup", "contacts.card.all": "Tutti i contatti",
        "contacts.desc.duplicates": "Unisci o elimina i duplicati…", "contacts.desc.incomplete": "Contatti senza nome, telefono…",
        "contacts.desc.backup": "Salva e ripristina i contatti quando…", "contacts.desc.all": "Vedi tutti i contatti sul dispositivo.",
        "contacts.count.duplicates": "%d gruppi duplicati", "contacts.count.incomplete": "%d contatti da controllare",
        "contacts.count.backups": "%d backup", "contacts.count": "%d contatti",
        "contacts.noName": "Senza nome", "contacts.noNumber": "Senza numero", "contacts.unknown": "Sconosciuto",
        "contacts.selectAll": "Seleziona tutto", "contacts.deselectAll": "Deseleziona tutto", "contacts.selectGroup": "Seleziona gruppo",
        "contacts.deleteSelected": "Elimina selezione", "contacts.deleteN": "Elimina %d selezionati",
        "contacts.dup.title": "Contatti duplicati", "contacts.dup.scanning": "Ricerca duplicati…",
        "contacts.dup.emptyTitle": "Nessun duplicato trovato", "contacts.dup.emptyBody": "I tuoi contatti sono in ordine.",
        "contacts.dup.groupCount": "%d contatti duplicati", "contacts.dup.merge": "Unisci contatti",
        "contacts.inc.title": "Contatti incompleti", "contacts.inc.missingName": "Nome mancante",
        "contacts.inc.missingPhone": "Numero mancante", "contacts.inc.missingBoth": "Nome e numero mancanti",
        "contacts.inc.edit": "Modifica contatti", "contacts.inc.emptyTitle": "Tutti i contatti sono completi",
        "contacts.inc.unnamed": "Contatto senza nome",
        "contacts.all.title": "Tutti i contatti", "contacts.all.search": "Cerca contatti",
        "contacts.backups.title": "Backup", "contacts.backups.count": "%d backup", "contacts.backups.create": "Crea backup",
        "contacts.backups.item": "Backup", "contacts.backups.restore": "Ripristina %d contatti", "contacts.backups.delete": "Elimina backup",
        "contacts.backups.errorTitle": "Errore di backup", "contacts.backups.restoredTitle": "Ripristinato",
        "contacts.backups.backing": "Backup dei contatti…", "contacts.backups.emptyTitle": "Ancora nessun backup",
        "contacts.backups.emptyBody": "Tocca Crea backup per salvare una copia di ogni contatto come file vCard su questo dispositivo.",
        "contacts.backups.restoredMsg": "%d contatti ripristinati",
        "contacts.permTitle": "Accesso ai Contatti richiesto",
        "contacts.permBody": "L’app legge i tuoi contatti per trovare duplicati, voci incomplete ed eseguirne il backup in sicurezza.",
        "contacts.somethingWrong": "Qualcosa è andato storto",
        "contact.title": "Contattaci", "contact.hero": "Mettiti in contatto",
        "contact.intro": "Ci farebbe piacere sentirti. Inviaci un messaggio e risponderemo il prima possibile.",
        "contact.name": "Nome", "contact.namePh": "Inserisci il tuo nome", "contact.email": "Email",
        "contact.emailPh": "Inserisci la tua email", "contact.message": "Il tuo messaggio", "contact.send": "Invia messaggio",
        "contact.errorTitle": "Invio non riuscito", "contact.noMail": "Nessun account email configurato. Scrivici direttamente a %@.",
    ]

    private static let nl: [String: String] = [
        "contacts.card.duplicates": "Duplicaten", "contacts.card.incomplete": "Onvolledige contacten",
        "contacts.card.backup": "Back-up", "contacts.card.all": "Alle contacten",
        "contacts.desc.duplicates": "Duplicaten samenvoegen of verwijderen…", "contacts.desc.incomplete": "Contacten zonder naam, telefoon…",
        "contacts.desc.backup": "Contacten opslaan en herstellen wanneer…", "contacts.desc.all": "Alle contacten op het apparaat bekijken.",
        "contacts.count.duplicates": "%d dubbele groepen", "contacts.count.incomplete": "%d contacten om te controleren",
        "contacts.count.backups": "%d back-ups", "contacts.count": "%d contacten",
        "contacts.noName": "Geen naam", "contacts.noNumber": "Geen nummer", "contacts.unknown": "Onbekend",
        "contacts.selectAll": "Alles selecteren", "contacts.deselectAll": "Selectie opheffen", "contacts.selectGroup": "Groep selecteren",
        "contacts.deleteSelected": "Selectie verwijderen", "contacts.deleteN": "%d geselecteerde verwijderen",
        "contacts.dup.title": "Dubbele contacten", "contacts.dup.scanning": "Zoeken naar duplicaten…",
        "contacts.dup.emptyTitle": "Geen duplicaten gevonden", "contacts.dup.emptyBody": "Je contacten zien er schoon uit.",
        "contacts.dup.groupCount": "%d dubbele contacten", "contacts.dup.merge": "Contacten samenvoegen",
        "contacts.inc.title": "Onvolledige contacten", "contacts.inc.missingName": "Naam ontbreekt",
        "contacts.inc.missingPhone": "Nummer ontbreekt", "contacts.inc.missingBoth": "Naam en nummer ontbreken",
        "contacts.inc.edit": "Contacten bewerken", "contacts.inc.emptyTitle": "Alle contacten zijn compleet",
        "contacts.inc.unnamed": "Naamloos contact",
        "contacts.all.title": "Alle contacten", "contacts.all.search": "Contacten zoeken",
        "contacts.backups.title": "Back-ups", "contacts.backups.count": "%d back-ups", "contacts.backups.create": "Back-up maken",
        "contacts.backups.item": "Back-up", "contacts.backups.restore": "%d contacten herstellen", "contacts.backups.delete": "Back-up verwijderen",
        "contacts.backups.errorTitle": "Back-upfout", "contacts.backups.restoredTitle": "Hersteld",
        "contacts.backups.backing": "Contacten back-uppen…", "contacts.backups.emptyTitle": "Nog geen back-ups",
        "contacts.backups.emptyBody": "Tik op Back-up maken om elk contact als vCard-bestand op dit apparaat op te slaan.",
        "contacts.backups.restoredMsg": "%d contacten hersteld",
        "contacts.permTitle": "Toegang tot Contacten vereist",
        "contacts.permBody": "De app leest je contacten om duplicaten en onvolledige items te vinden en veilig te back-uppen.",
        "contacts.somethingWrong": "Er ging iets mis",
        "contact.title": "Contact", "contact.hero": "Neem contact op",
        "contact.intro": "We horen graag van je. Stuur ons een bericht en we reageren zo snel mogelijk.",
        "contact.name": "Naam", "contact.namePh": "Voer je naam in", "contact.email": "E-mailadres",
        "contact.emailPh": "Voer je e-mail in", "contact.message": "Je bericht", "contact.send": "Bericht verzenden",
        "contact.errorTitle": "Verzenden mislukt", "contact.noMail": "Geen e-mailaccount ingesteld. Mail ons rechtstreeks op %@.",
    ]

    private static let tr: [String: String] = [
        "contacts.card.duplicates": "Kopyalar", "contacts.card.incomplete": "Eksik kişiler",
        "contacts.card.backup": "Yedek", "contacts.card.all": "Tüm kişiler",
        "contacts.desc.duplicates": "Kopyaları birleştir veya sil…", "contacts.desc.incomplete": "Adı, telefonu eksik kişiler…",
        "contacts.desc.backup": "Kişileri yedekle ve geri yükle…", "contacts.desc.all": "Cihazdaki tüm kişileri gör.",
        "contacts.count.duplicates": "%d kopya grubu", "contacts.count.incomplete": "%d kişi kontrol edilecek",
        "contacts.count.backups": "%d yedek", "contacts.count": "%d kişi",
        "contacts.noName": "Ad yok", "contacts.noNumber": "Numara yok", "contacts.unknown": "Bilinmiyor",
        "contacts.selectAll": "Tümünü seç", "contacts.deselectAll": "Seçimi kaldır", "contacts.selectGroup": "Grubu seç",
        "contacts.deleteSelected": "Seçileni sil", "contacts.deleteN": "%d seçileni sil",
        "contacts.dup.title": "Yinelenen kişiler", "contacts.dup.scanning": "Kopyalar aranıyor…",
        "contacts.dup.emptyTitle": "Kopya bulunamadı", "contacts.dup.emptyBody": "Kişilerin temiz görünüyor.",
        "contacts.dup.groupCount": "%d yinelenen kişi", "contacts.dup.merge": "Kişileri birleştir",
        "contacts.inc.title": "Eksik kişiler", "contacts.inc.missingName": "Ad eksik",
        "contacts.inc.missingPhone": "Numara eksik", "contacts.inc.missingBoth": "Ad ve numara eksik",
        "contacts.inc.edit": "Kişileri düzenle", "contacts.inc.emptyTitle": "Tüm kişiler eksiksiz",
        "contacts.inc.unnamed": "Adsız kişi",
        "contacts.all.title": "Tüm kişiler", "contacts.all.search": "Kişi ara",
        "contacts.backups.title": "Yedekler", "contacts.backups.count": "%d yedek", "contacts.backups.create": "Yedek oluştur",
        "contacts.backups.item": "Yedek", "contacts.backups.restore": "%d kişiyi geri yükle", "contacts.backups.delete": "Yedeği sil",
        "contacts.backups.errorTitle": "Yedek hatası", "contacts.backups.restoredTitle": "Geri yüklendi",
        "contacts.backups.backing": "Kişiler yedekleniyor…", "contacts.backups.emptyTitle": "Henüz yedek yok",
        "contacts.backups.emptyBody": "Her kişiyi bu cihazda vCard dosyası olarak kaydetmek için Yedek oluştur’a dokun.",
        "contacts.backups.restoredMsg": "%d kişi geri yüklendi",
        "contacts.permTitle": "Kişi erişimi gerekli",
        "contacts.permBody": "Uygulama, kopyaları ve eksik kayıtları bulup güvenle yedeklemek için kişilerini okur.",
        "contacts.somethingWrong": "Bir şeyler ters gitti",
        "contact.title": "Bize ulaşın", "contact.hero": "İletişime geç",
        "contact.intro": "Senden haber almak isteriz. Bize bir mesaj gönder, en kısa sürede yanıtlayalım.",
        "contact.name": "Ad", "contact.namePh": "Adını gir", "contact.email": "E-posta adresi",
        "contact.emailPh": "E-postanı gir", "contact.message": "Mesajın", "contact.send": "Mesaj gönder",
        "contact.errorTitle": "Gönderilemedi", "contact.noMail": "Yapılandırılmış e-posta hesabı yok. Bize doğrudan %@ adresinden yaz.",
    ]

    private static let uk: [String: String] = [
        "contacts.card.duplicates": "Дублікати", "contacts.card.incomplete": "Неповні контакти",
        "contacts.card.backup": "Резервна копія", "contacts.card.all": "Усі контакти",
        "contacts.desc.duplicates": "Об’єднати або видалити дублікати…", "contacts.desc.incomplete": "Контакти без імені, телефону…",
        "contacts.desc.backup": "Зберігайте та відновлюйте контакти, коли…", "contacts.desc.all": "Переглянути всі контакти на пристрої.",
        "contacts.count.duplicates": "%d груп дублікатів", "contacts.count.incomplete": "%d контактів для перевірки",
        "contacts.count.backups": "%d копій", "contacts.count": "%d контактів",
        "contacts.noName": "Без імені", "contacts.noNumber": "Без номера", "contacts.unknown": "Невідомо",
        "contacts.selectAll": "Вибрати все", "contacts.deselectAll": "Зняти вибір", "contacts.selectGroup": "Вибрати групу",
        "contacts.deleteSelected": "Видалити вибране", "contacts.deleteN": "Видалити %d вибраних",
        "contacts.dup.title": "Дубльовані контакти", "contacts.dup.scanning": "Пошук дублікатів…",
        "contacts.dup.emptyTitle": "Дублікатів не знайдено", "contacts.dup.emptyBody": "Ваші контакти чисті.",
        "contacts.dup.groupCount": "%d дубльованих контактів", "contacts.dup.merge": "Об’єднати контакти",
        "contacts.inc.title": "Неповні контакти", "contacts.inc.missingName": "Немає імені",
        "contacts.inc.missingPhone": "Немає номера", "contacts.inc.missingBoth": "Немає імені та номера",
        "contacts.inc.edit": "Редагувати контакти", "contacts.inc.emptyTitle": "Усі контакти повні",
        "contacts.inc.unnamed": "Контакт без імені",
        "contacts.all.title": "Усі контакти", "contacts.all.search": "Пошук контактів",
        "contacts.backups.title": "Резервні копії", "contacts.backups.count": "%d копій", "contacts.backups.create": "Створити копію",
        "contacts.backups.item": "Копія", "contacts.backups.restore": "Відновити %d контактів", "contacts.backups.delete": "Видалити копію",
        "contacts.backups.errorTitle": "Помилка копіювання", "contacts.backups.restoredTitle": "Відновлено",
        "contacts.backups.backing": "Резервне копіювання контактів…", "contacts.backups.emptyTitle": "Ще немає копій",
        "contacts.backups.emptyBody": "Торкніться Створити копію, щоб зберегти кожен контакт як файл vCard на цьому пристрої.",
        "contacts.backups.restoredMsg": "Відновлено %d контактів",
        "contacts.permTitle": "Потрібен доступ до Контактів",
        "contacts.permBody": "Застосунок читає ваші контакти, щоб знайти дублікати, неповні записи й безпечно створити резервну копію.",
        "contacts.somethingWrong": "Щось пішло не так",
        "contact.title": "Зв’язатися з нами", "contact.hero": "Напишіть нам",
        "contact.intro": "Ми будемо раді вашому повідомленню. Напишіть нам, і ми відповімо якнайшвидше.",
        "contact.name": "Ім’я", "contact.namePh": "Введіть своє ім’я", "contact.email": "Електронна пошта",
        "contact.emailPh": "Введіть свою пошту", "contact.message": "Ваше повідомлення", "contact.send": "Надіслати",
        "contact.errorTitle": "Не вдалося надіслати", "contact.noMail": "Не налаштовано поштовий акаунт. Напишіть нам напряму на %@.",
    ]

    private static let ru: [String: String] = [
        "contacts.card.duplicates": "Дубликаты", "contacts.card.incomplete": "Неполные контакты",
        "contacts.card.backup": "Резервная копия", "contacts.card.all": "Все контакты",
        "contacts.desc.duplicates": "Объединить или удалить дубликаты…", "contacts.desc.incomplete": "Контакты без имени, телефона…",
        "contacts.desc.backup": "Сохраняйте и восстанавливайте контакты, когда…", "contacts.desc.all": "Показать все контакты на устройстве.",
        "contacts.count.duplicates": "%d групп дубликатов", "contacts.count.incomplete": "%d контактов для проверки",
        "contacts.count.backups": "%d копий", "contacts.count": "%d контактов",
        "contacts.noName": "Без имени", "contacts.noNumber": "Без номера", "contacts.unknown": "Неизвестно",
        "contacts.selectAll": "Выбрать все", "contacts.deselectAll": "Снять выбор", "contacts.selectGroup": "Выбрать группу",
        "contacts.deleteSelected": "Удалить выбранное", "contacts.deleteN": "Удалить %d выбранных",
        "contacts.dup.title": "Дубликаты контактов", "contacts.dup.scanning": "Поиск дубликатов…",
        "contacts.dup.emptyTitle": "Дубликаты не найдены", "contacts.dup.emptyBody": "Ваши контакты в порядке.",
        "contacts.dup.groupCount": "%d дубликатов контактов", "contacts.dup.merge": "Объединить контакты",
        "contacts.inc.title": "Неполные контакты", "contacts.inc.missingName": "Нет имени",
        "contacts.inc.missingPhone": "Нет номера", "contacts.inc.missingBoth": "Нет имени и номера",
        "contacts.inc.edit": "Редактировать контакты", "contacts.inc.emptyTitle": "Все контакты заполнены",
        "contacts.inc.unnamed": "Контакт без имени",
        "contacts.all.title": "Все контакты", "contacts.all.search": "Поиск контактов",
        "contacts.backups.title": "Резервные копии", "contacts.backups.count": "%d копий", "contacts.backups.create": "Создать копию",
        "contacts.backups.item": "Копия", "contacts.backups.restore": "Восстановить %d контактов", "contacts.backups.delete": "Удалить копию",
        "contacts.backups.errorTitle": "Ошибка копирования", "contacts.backups.restoredTitle": "Восстановлено",
        "contacts.backups.backing": "Резервное копирование контактов…", "contacts.backups.emptyTitle": "Пока нет копий",
        "contacts.backups.emptyBody": "Нажмите Создать копию, чтобы сохранить каждый контакт как файл vCard на этом устройстве.",
        "contacts.backups.restoredMsg": "Восстановлено %d контактов",
        "contacts.permTitle": "Требуется доступ к Контактам",
        "contacts.permBody": "Приложение читает ваши контакты, чтобы найти дубликаты, неполные записи и безопасно создать резервную копию.",
        "contacts.somethingWrong": "Что-то пошло не так",
        "contact.title": "Связаться с нами", "contact.hero": "Напишите нам",
        "contact.intro": "Будем рады вашему сообщению. Напишите нам, и мы ответим как можно скорее.",
        "contact.name": "Имя", "contact.namePh": "Введите имя", "contact.email": "Эл. почта",
        "contact.emailPh": "Введите почту", "contact.message": "Ваше сообщение", "contact.send": "Отправить",
        "contact.errorTitle": "Не удалось отправить", "contact.noMail": "Почтовый аккаунт не настроен. Напишите нам напрямую на %@.",
    ]

    private static let he: [String: String] = [
        "contacts.card.duplicates": "כפילויות", "contacts.card.incomplete": "אנשי קשר חסרים",
        "contacts.card.backup": "גיבוי", "contacts.card.all": "כל אנשי הקשר",
        "contacts.desc.duplicates": "מיזוג או מחיקה של כפילויות…", "contacts.desc.incomplete": "אנשי קשר ללא שם, טלפון…",
        "contacts.desc.backup": "גיבוי ושחזור של אנשי קשר כאשר…", "contacts.desc.all": "הצגת כל אנשי הקשר במכשיר.",
        "contacts.count.duplicates": "%d קבוצות כפילויות", "contacts.count.incomplete": "%d אנשי קשר לבדיקה",
        "contacts.count.backups": "%d גיבויים", "contacts.count": "%d אנשי קשר",
        "contacts.noName": "ללא שם", "contacts.noNumber": "ללא מספר", "contacts.unknown": "לא ידוע",
        "contacts.selectAll": "בחר הכול", "contacts.deselectAll": "בטל בחירה", "contacts.selectGroup": "בחר קבוצה",
        "contacts.deleteSelected": "מחק נבחרים", "contacts.deleteN": "מחק %d נבחרים",
        "contacts.dup.title": "אנשי קשר כפולים", "contacts.dup.scanning": "מחפש כפילויות…",
        "contacts.dup.emptyTitle": "לא נמצאו כפילויות", "contacts.dup.emptyBody": "אנשי הקשר שלך נקיים.",
        "contacts.dup.groupCount": "%d אנשי קשר כפולים", "contacts.dup.merge": "מזג אנשי קשר",
        "contacts.inc.title": "אנשי קשר חסרים", "contacts.inc.missingName": "חסר שם",
        "contacts.inc.missingPhone": "חסר מספר", "contacts.inc.missingBoth": "חסרים שם ומספר",
        "contacts.inc.edit": "ערוך אנשי קשר", "contacts.inc.emptyTitle": "כל אנשי הקשר מלאים",
        "contacts.inc.unnamed": "איש קשר ללא שם",
        "contacts.all.title": "כל אנשי הקשר", "contacts.all.search": "חיפוש אנשי קשר",
        "contacts.backups.title": "גיבויים", "contacts.backups.count": "%d גיבויים", "contacts.backups.create": "צור גיבוי",
        "contacts.backups.item": "גיבוי", "contacts.backups.restore": "שחזר %d אנשי קשר", "contacts.backups.delete": "מחק גיבוי",
        "contacts.backups.errorTitle": "שגיאת גיבוי", "contacts.backups.restoredTitle": "שוחזר",
        "contacts.backups.backing": "מגבה אנשי קשר…", "contacts.backups.emptyTitle": "אין עדיין גיבויים",
        "contacts.backups.emptyBody": "הקש על צור גיבוי כדי לשמור כל איש קשר כקובץ vCard במכשיר הזה.",
        "contacts.backups.restoredMsg": "%d אנשי קשר שוחזרו",
        "contacts.permTitle": "נדרשת גישה לאנשי קשר",
        "contacts.permBody": "האפליקציה קוראת את אנשי הקשר שלך כדי למצוא כפילויות ורשומות חסרות ולגבות אותן בבטחה.",
        "contacts.somethingWrong": "משהו השתבש",
        "contact.title": "צור קשר", "contact.hero": "דברו איתנו",
        "contact.intro": "נשמח לשמוע ממך. שלח לנו הודעה ונחזור אליך בהקדם האפשרי.",
        "contact.name": "שם", "contact.namePh": "הזן את שמך", "contact.email": "כתובת אימייל",
        "contact.emailPh": "הזן את האימייל שלך", "contact.message": "ההודעה שלך", "contact.send": "שלח הודעה",
        "contact.errorTitle": "השליחה נכשלה", "contact.noMail": "לא הוגדר חשבון אימייל. כתבו לנו ישירות אל %@.",
    ]

    private static let ar: [String: String] = [
        "contacts.card.duplicates": "المكررة", "contacts.card.incomplete": "جهات اتصال ناقصة",
        "contacts.card.backup": "نسخة احتياطية", "contacts.card.all": "كل جهات الاتصال",
        "contacts.desc.duplicates": "دمج أو حذف المكرر…", "contacts.desc.incomplete": "جهات بلا اسم أو هاتف…",
        "contacts.desc.backup": "احفظ واستعد جهات الاتصال عند…", "contacts.desc.all": "عرض كل جهات الاتصال على الجهاز.",
        "contacts.count.duplicates": "%d مجموعات مكررة", "contacts.count.incomplete": "%d جهة للمراجعة",
        "contacts.count.backups": "%d نسخة", "contacts.count": "%d جهة اتصال",
        "contacts.noName": "بلا اسم", "contacts.noNumber": "بلا رقم", "contacts.unknown": "غير معروف",
        "contacts.selectAll": "تحديد الكل", "contacts.deselectAll": "إلغاء التحديد", "contacts.selectGroup": "تحديد المجموعة",
        "contacts.deleteSelected": "حذف المحدد", "contacts.deleteN": "حذف %d محددة",
        "contacts.dup.title": "جهات الاتصال المكررة", "contacts.dup.scanning": "جارٍ البحث عن المكرر…",
        "contacts.dup.emptyTitle": "لا توجد جهات مكررة", "contacts.dup.emptyBody": "جهات اتصالك نظيفة.",
        "contacts.dup.groupCount": "%d جهة مكررة", "contacts.dup.merge": "دمج جهات الاتصال",
        "contacts.inc.title": "جهات اتصال ناقصة", "contacts.inc.missingName": "الاسم مفقود",
        "contacts.inc.missingPhone": "الرقم مفقود", "contacts.inc.missingBoth": "الاسم والرقم مفقودان",
        "contacts.inc.edit": "تعديل جهات الاتصال", "contacts.inc.emptyTitle": "كل جهات الاتصال مكتملة",
        "contacts.inc.unnamed": "جهة بلا اسم",
        "contacts.all.title": "كل جهات الاتصال", "contacts.all.search": "بحث في جهات الاتصال",
        "contacts.backups.title": "النسخ الاحتياطية", "contacts.backups.count": "%d نسخة", "contacts.backups.create": "إنشاء نسخة",
        "contacts.backups.item": "نسخة", "contacts.backups.restore": "استعادة %d جهة", "contacts.backups.delete": "حذف النسخة",
        "contacts.backups.errorTitle": "خطأ في النسخ", "contacts.backups.restoredTitle": "تمت الاستعادة",
        "contacts.backups.backing": "جارٍ نسخ جهات الاتصال…", "contacts.backups.emptyTitle": "لا توجد نسخ بعد",
        "contacts.backups.emptyBody": "اضغط على إنشاء نسخة لحفظ كل جهة اتصال كملف vCard على هذا الجهاز.",
        "contacts.backups.restoredMsg": "تمت استعادة %d جهة",
        "contacts.permTitle": "مطلوب الوصول إلى جهات الاتصال",
        "contacts.permBody": "يقرأ التطبيق جهات اتصالك للعثور على المكرر والسجلات الناقصة ونسخها احتياطيًا بأمان.",
        "contacts.somethingWrong": "حدث خطأ ما",
        "contact.title": "تواصل معنا", "contact.hero": "ابقَ على تواصل",
        "contact.intro": "يسعدنا سماع رأيك. أرسل لنا رسالة وسنرد بأسرع وقت.",
        "contact.name": "الاسم", "contact.namePh": "أدخل اسمك", "contact.email": "البريد الإلكتروني",
        "contact.emailPh": "أدخل بريدك", "contact.message": "رسالتك", "contact.send": "إرسال الرسالة",
        "contact.errorTitle": "تعذّر الإرسال", "contact.noMail": "لا يوجد حساب بريد مُهيأ. راسلنا مباشرة على %@.",
    ]

    private static let fa: [String: String] = [
        "contacts.card.duplicates": "تکراری‌ها", "contacts.card.incomplete": "مخاطبین ناقص",
        "contacts.card.backup": "پشتیبان", "contacts.card.all": "همه مخاطبین",
        "contacts.desc.duplicates": "ادغام یا حذف موارد تکراری…", "contacts.desc.incomplete": "مخاطبین بدون نام یا تلفن…",
        "contacts.desc.backup": "ذخیره و بازیابی مخاطبین هنگام…", "contacts.desc.all": "مشاهده همه مخاطبین دستگاه.",
        "contacts.count.duplicates": "%d گروه تکراری", "contacts.count.incomplete": "%d مخاطب برای بررسی",
        "contacts.count.backups": "%d پشتیبان", "contacts.count": "%d مخاطب",
        "contacts.noName": "بدون نام", "contacts.noNumber": "بدون شماره", "contacts.unknown": "نامشخص",
        "contacts.selectAll": "انتخاب همه", "contacts.deselectAll": "لغو انتخاب", "contacts.selectGroup": "انتخاب گروه",
        "contacts.deleteSelected": "حذف انتخاب‌شده", "contacts.deleteN": "حذف %d انتخاب‌شده",
        "contacts.dup.title": "مخاطبین تکراری", "contacts.dup.scanning": "در حال جستجوی تکراری‌ها…",
        "contacts.dup.emptyTitle": "تکراری‌ای یافت نشد", "contacts.dup.emptyBody": "مخاطبین شما تمیز هستند.",
        "contacts.dup.groupCount": "%d مخاطب تکراری", "contacts.dup.merge": "ادغام مخاطبین",
        "contacts.inc.title": "مخاطبین ناقص", "contacts.inc.missingName": "نام موجود نیست",
        "contacts.inc.missingPhone": "شماره موجود نیست", "contacts.inc.missingBoth": "نام و شماره موجود نیست",
        "contacts.inc.edit": "ویرایش مخاطبین", "contacts.inc.emptyTitle": "همه مخاطبین کامل‌اند",
        "contacts.inc.unnamed": "مخاطب بی‌نام",
        "contacts.all.title": "همه مخاطبین", "contacts.all.search": "جستجوی مخاطبین",
        "contacts.backups.title": "پشتیبان‌ها", "contacts.backups.count": "%d پشتیبان", "contacts.backups.create": "ایجاد پشتیبان",
        "contacts.backups.item": "پشتیبان", "contacts.backups.restore": "بازیابی %d مخاطب", "contacts.backups.delete": "حذف پشتیبان",
        "contacts.backups.errorTitle": "خطای پشتیبان", "contacts.backups.restoredTitle": "بازیابی شد",
        "contacts.backups.backing": "در حال پشتیبان‌گیری از مخاطبین…", "contacts.backups.emptyTitle": "هنوز پشتیبانی نیست",
        "contacts.backups.emptyBody": "برای ذخیره هر مخاطب به‌صورت فایل vCard روی این دستگاه، روی ایجاد پشتیبان بزنید.",
        "contacts.backups.restoredMsg": "%d مخاطب بازیابی شد",
        "contacts.permTitle": "دسترسی به مخاطبین لازم است",
        "contacts.permBody": "برنامه مخاطبین شما را می‌خواند تا تکراری‌ها و موارد ناقص را پیدا کند و ایمن پشتیبان بگیرد.",
        "contacts.somethingWrong": "مشکلی پیش آمد",
        "contact.title": "تماس با ما", "contact.hero": "در ارتباط باشید",
        "contact.intro": "خوشحال می‌شویم از شما بشنویم. پیام بدهید تا در اسرع وقت پاسخ دهیم.",
        "contact.name": "نام", "contact.namePh": "نام خود را وارد کنید", "contact.email": "ایمیل",
        "contact.emailPh": "ایمیل خود را وارد کنید", "contact.message": "پیام شما", "contact.send": "ارسال پیام",
        "contact.errorTitle": "ارسال نشد", "contact.noMail": "هیچ حساب ایمیلی تنظیم نشده. مستقیم به %@ ایمیل بزنید.",
    ]

    private static let id: [String: String] = [
        "contacts.card.duplicates": "Duplikat", "contacts.card.incomplete": "Kontak tidak lengkap",
        "contacts.card.backup": "Cadangan", "contacts.card.all": "Semua kontak",
        "contacts.desc.duplicates": "Gabung atau hapus duplikat…", "contacts.desc.incomplete": "Kontak tanpa nama, telepon…",
        "contacts.desc.backup": "Simpan dan pulihkan kontak saat…", "contacts.desc.all": "Lihat semua kontak di perangkat.",
        "contacts.count.duplicates": "%d grup duplikat", "contacts.count.incomplete": "%d kontak untuk diperiksa",
        "contacts.count.backups": "%d cadangan", "contacts.count": "%d kontak",
        "contacts.noName": "Tanpa nama", "contacts.noNumber": "Tanpa nomor", "contacts.unknown": "Tidak diketahui",
        "contacts.selectAll": "Pilih semua", "contacts.deselectAll": "Batalkan pilihan", "contacts.selectGroup": "Pilih grup",
        "contacts.deleteSelected": "Hapus pilihan", "contacts.deleteN": "Hapus %d terpilih",
        "contacts.dup.title": "Kontak duplikat", "contacts.dup.scanning": "Mencari duplikat…",
        "contacts.dup.emptyTitle": "Tidak ada duplikat", "contacts.dup.emptyBody": "Kontakmu terlihat bersih.",
        "contacts.dup.groupCount": "%d kontak duplikat", "contacts.dup.merge": "Gabungkan kontak",
        "contacts.inc.title": "Kontak tidak lengkap", "contacts.inc.missingName": "Nama tidak ada",
        "contacts.inc.missingPhone": "Nomor tidak ada", "contacts.inc.missingBoth": "Nama & nomor tidak ada",
        "contacts.inc.edit": "Edit kontak", "contacts.inc.emptyTitle": "Semua kontak lengkap",
        "contacts.inc.unnamed": "Kontak tanpa nama",
        "contacts.all.title": "Semua kontak", "contacts.all.search": "Cari kontak",
        "contacts.backups.title": "Cadangan", "contacts.backups.count": "%d cadangan", "contacts.backups.create": "Buat cadangan",
        "contacts.backups.item": "Cadangan", "contacts.backups.restore": "Pulihkan %d kontak", "contacts.backups.delete": "Hapus cadangan",
        "contacts.backups.errorTitle": "Galat cadangan", "contacts.backups.restoredTitle": "Dipulihkan",
        "contacts.backups.backing": "Mencadangkan kontak…", "contacts.backups.emptyTitle": "Belum ada cadangan",
        "contacts.backups.emptyBody": "Ketuk Buat cadangan untuk menyimpan setiap kontak sebagai file vCard di perangkat ini.",
        "contacts.backups.restoredMsg": "%d kontak dipulihkan",
        "contacts.permTitle": "Perlu akses Kontak",
        "contacts.permBody": "Aplikasi membaca kontakmu untuk menemukan duplikat, entri tidak lengkap, dan mencadangkannya dengan aman.",
        "contacts.somethingWrong": "Terjadi kesalahan",
        "contact.title": "Hubungi kami", "contact.hero": "Hubungi kami",
        "contact.intro": "Kami senang mendengar dari kamu. Kirim pesan dan kami akan membalas secepatnya.",
        "contact.name": "Nama", "contact.namePh": "Masukkan namamu", "contact.email": "Alamat email",
        "contact.emailPh": "Masukkan emailmu", "contact.message": "Pesanmu", "contact.send": "Kirim pesan",
        "contact.errorTitle": "Tidak dapat mengirim", "contact.noMail": "Tidak ada akun email yang diatur. Email kami langsung ke %@.",
    ]

    private static let vi: [String: String] = [
        "contacts.card.duplicates": "Trùng lặp", "contacts.card.incomplete": "Danh bạ thiếu thông tin",
        "contacts.card.backup": "Sao lưu", "contacts.card.all": "Tất cả danh bạ",
        "contacts.desc.duplicates": "Gộp hoặc xoá liên hệ trùng…", "contacts.desc.incomplete": "Liên hệ thiếu tên, số điện thoại…",
        "contacts.desc.backup": "Sao lưu và khôi phục danh bạ khi…", "contacts.desc.all": "Xem tất cả liên hệ trên máy.",
        "contacts.count.duplicates": "%d nhóm trùng lặp", "contacts.count.incomplete": "%d liên hệ cần kiểm tra",
        "contacts.count.backups": "%d bản sao lưu", "contacts.count": "%d liên hệ",
        "contacts.noName": "Không có tên", "contacts.noNumber": "Không có số", "contacts.unknown": "Không rõ",
        "contacts.selectAll": "Chọn tất cả", "contacts.deselectAll": "Bỏ chọn tất cả", "contacts.selectGroup": "Chọn nhóm",
        "contacts.deleteSelected": "Xoá mục đã chọn", "contacts.deleteN": "Xoá %d mục đã chọn",
        "contacts.dup.title": "Liên hệ trùng lặp", "contacts.dup.scanning": "Đang quét trùng lặp…",
        "contacts.dup.emptyTitle": "Không có liên hệ trùng", "contacts.dup.emptyBody": "Danh bạ của bạn gọn gàng.",
        "contacts.dup.groupCount": "%d liên hệ trùng lặp", "contacts.dup.merge": "Gộp liên hệ",
        "contacts.inc.title": "Liên hệ thiếu thông tin", "contacts.inc.missingName": "Thiếu tên liên hệ",
        "contacts.inc.missingPhone": "Thiếu số điện thoại", "contacts.inc.missingBoth": "Thiếu tên & số điện thoại",
        "contacts.inc.edit": "Sửa liên hệ", "contacts.inc.emptyTitle": "Mọi liên hệ đều đầy đủ",
        "contacts.inc.unnamed": "Liên hệ chưa đặt tên",
        "contacts.all.title": "Tất cả liên hệ", "contacts.all.search": "Tìm liên hệ",
        "contacts.backups.title": "Bản sao lưu", "contacts.backups.count": "%d bản sao lưu", "contacts.backups.create": "Tạo sao lưu",
        "contacts.backups.item": "Sao lưu", "contacts.backups.restore": "Khôi phục %d liên hệ", "contacts.backups.delete": "Xoá bản sao lưu",
        "contacts.backups.errorTitle": "Lỗi sao lưu", "contacts.backups.restoredTitle": "Đã khôi phục",
        "contacts.backups.backing": "Đang sao lưu danh bạ…", "contacts.backups.emptyTitle": "Chưa có bản sao lưu",
        "contacts.backups.emptyBody": "Chạm Tạo sao lưu để lưu toàn bộ liên hệ thành tệp vCard trên máy này.",
        "contacts.backups.restoredMsg": "Đã khôi phục %d liên hệ",
        "contacts.permTitle": "Cần quyền truy cập Danh bạ",
        "contacts.permBody": "Ứng dụng đọc danh bạ để tìm liên hệ trùng, mục thiếu thông tin và sao lưu an toàn.",
        "contacts.somethingWrong": "Đã xảy ra lỗi",
        "contact.title": "Liên hệ", "contact.hero": "Liên hệ với chúng tôi",
        "contact.intro": "Chúng tôi rất mong nhận tin từ bạn. Hãy gửi tin nhắn, chúng tôi sẽ phản hồi sớm nhất.",
        "contact.name": "Tên", "contact.namePh": "Nhập tên của bạn", "contact.email": "Địa chỉ email",
        "contact.emailPh": "Nhập email của bạn", "contact.message": "Tin nhắn của bạn", "contact.send": "Gửi tin nhắn",
        "contact.errorTitle": "Không gửi được", "contact.noMail": "Chưa thiết lập tài khoản email. Hãy email trực tiếp cho chúng tôi tại %@.",
    ]

    private static let ja: [String: String] = [
        "contacts.card.duplicates": "重複", "contacts.card.incomplete": "不完全な連絡先",
        "contacts.card.backup": "バックアップ", "contacts.card.all": "すべての連絡先",
        "contacts.desc.duplicates": "重複を結合または削除…", "contacts.desc.incomplete": "名前や電話がない連絡先…",
        "contacts.desc.backup": "連絡先を保存・復元…", "contacts.desc.all": "端末のすべての連絡先を表示。",
        "contacts.count.duplicates": "重複%dグループ", "contacts.count.incomplete": "確認する連絡先%d件",
        "contacts.count.backups": "バックアップ%d件", "contacts.count": "連絡先%d件",
        "contacts.noName": "名前なし", "contacts.noNumber": "番号なし", "contacts.unknown": "不明",
        "contacts.selectAll": "すべて選択", "contacts.deselectAll": "選択解除", "contacts.selectGroup": "グループを選択",
        "contacts.deleteSelected": "選択を削除", "contacts.deleteN": "選択した%d件を削除",
        "contacts.dup.title": "重複した連絡先", "contacts.dup.scanning": "重複を検索中…",
        "contacts.dup.emptyTitle": "重複は見つかりません", "contacts.dup.emptyBody": "連絡先はきれいです。",
        "contacts.dup.groupCount": "重複した連絡先%d件", "contacts.dup.merge": "連絡先を結合",
        "contacts.inc.title": "不完全な連絡先", "contacts.inc.missingName": "名前がありません",
        "contacts.inc.missingPhone": "番号がありません", "contacts.inc.missingBoth": "名前と番号がありません",
        "contacts.inc.edit": "連絡先を編集", "contacts.inc.emptyTitle": "すべての連絡先が完全です",
        "contacts.inc.unnamed": "名称未設定の連絡先",
        "contacts.all.title": "すべての連絡先", "contacts.all.search": "連絡先を検索",
        "contacts.backups.title": "バックアップ", "contacts.backups.count": "バックアップ%d件", "contacts.backups.create": "バックアップを作成",
        "contacts.backups.item": "バックアップ", "contacts.backups.restore": "%d件の連絡先を復元", "contacts.backups.delete": "バックアップを削除",
        "contacts.backups.errorTitle": "バックアップエラー", "contacts.backups.restoredTitle": "復元しました",
        "contacts.backups.backing": "連絡先をバックアップ中…", "contacts.backups.emptyTitle": "バックアップはまだありません",
        "contacts.backups.emptyBody": "バックアップを作成をタップして、各連絡先をvCardファイルとしてこの端末に保存します。",
        "contacts.backups.restoredMsg": "%d件の連絡先を復元しました",
        "contacts.permTitle": "連絡先へのアクセスが必要です",
        "contacts.permBody": "重複や不完全な項目を見つけて安全にバックアップするため、連絡先へのアクセスが必要です。",
        "contacts.somethingWrong": "問題が発生しました",
        "contact.title": "お問い合わせ", "contact.hero": "お問い合わせ",
        "contact.intro": "ぜひご意見をお聞かせください。メッセージをお送りいただければ、できるだけ早く返信します。",
        "contact.name": "名前", "contact.namePh": "名前を入力", "contact.email": "メールアドレス",
        "contact.emailPh": "メールを入力", "contact.message": "メッセージ", "contact.send": "メッセージを送信",
        "contact.errorTitle": "送信できませんでした", "contact.noMail": "メールアカウントが設定されていません。%@ まで直接ご連絡ください。",
    ]

    private static let ko: [String: String] = [
        "contacts.card.duplicates": "중복", "contacts.card.incomplete": "불완전한 연락처",
        "contacts.card.backup": "백업", "contacts.card.all": "모든 연락처",
        "contacts.desc.duplicates": "중복 병합 또는 삭제…", "contacts.desc.incomplete": "이름·전화가 없는 연락처…",
        "contacts.desc.backup": "연락처 저장 및 복원…", "contacts.desc.all": "기기의 모든 연락처 보기.",
        "contacts.count.duplicates": "중복 %d그룹", "contacts.count.incomplete": "확인할 연락처 %d개",
        "contacts.count.backups": "백업 %d개", "contacts.count": "연락처 %d개",
        "contacts.noName": "이름 없음", "contacts.noNumber": "번호 없음", "contacts.unknown": "알 수 없음",
        "contacts.selectAll": "모두 선택", "contacts.deselectAll": "선택 해제", "contacts.selectGroup": "그룹 선택",
        "contacts.deleteSelected": "선택 삭제", "contacts.deleteN": "선택한 %d개 삭제",
        "contacts.dup.title": "중복 연락처", "contacts.dup.scanning": "중복 검색 중…",
        "contacts.dup.emptyTitle": "중복이 없습니다", "contacts.dup.emptyBody": "연락처가 깔끔합니다.",
        "contacts.dup.groupCount": "중복 연락처 %d개", "contacts.dup.merge": "연락처 병합",
        "contacts.inc.title": "불완전한 연락처", "contacts.inc.missingName": "이름 없음",
        "contacts.inc.missingPhone": "번호 없음", "contacts.inc.missingBoth": "이름·번호 없음",
        "contacts.inc.edit": "연락처 편집", "contacts.inc.emptyTitle": "모든 연락처가 완전합니다",
        "contacts.inc.unnamed": "이름 없는 연락처",
        "contacts.all.title": "모든 연락처", "contacts.all.search": "연락처 검색",
        "contacts.backups.title": "백업", "contacts.backups.count": "백업 %d개", "contacts.backups.create": "백업 만들기",
        "contacts.backups.item": "백업", "contacts.backups.restore": "연락처 %d개 복원", "contacts.backups.delete": "백업 삭제",
        "contacts.backups.errorTitle": "백업 오류", "contacts.backups.restoredTitle": "복원됨",
        "contacts.backups.backing": "연락처 백업 중…", "contacts.backups.emptyTitle": "아직 백업이 없습니다",
        "contacts.backups.emptyBody": "백업 만들기를 눌러 각 연락처를 이 기기에 vCard 파일로 저장하세요.",
        "contacts.backups.restoredMsg": "연락처 %d개를 복원했습니다",
        "contacts.permTitle": "연락처 접근 권한 필요",
        "contacts.permBody": "앱은 중복과 불완전한 항목을 찾아 안전하게 백업하기 위해 연락처를 읽습니다.",
        "contacts.somethingWrong": "문제가 발생했습니다",
        "contact.title": "문의하기", "contact.hero": "문의하기",
        "contact.intro": "여러분의 의견을 기다립니다. 메시지를 보내주시면 최대한 빨리 답변드리겠습니다.",
        "contact.name": "이름", "contact.namePh": "이름 입력", "contact.email": "이메일 주소",
        "contact.emailPh": "이메일 입력", "contact.message": "메시지", "contact.send": "메시지 보내기",
        "contact.errorTitle": "보낼 수 없음", "contact.noMail": "설정된 메일 계정이 없습니다. %@ 로 직접 보내주세요.",
    ]

    private static let zhHans: [String: String] = [
        "contacts.card.duplicates": "重复", "contacts.card.incomplete": "不完整联系人",
        "contacts.card.backup": "备份", "contacts.card.all": "所有联系人",
        "contacts.desc.duplicates": "合并或删除重复项…", "contacts.desc.incomplete": "缺少姓名、电话的联系人…",
        "contacts.desc.backup": "在需要时备份和恢复联系人…", "contacts.desc.all": "查看设备上的所有联系人。",
        "contacts.count.duplicates": "%d 个重复组", "contacts.count.incomplete": "%d 个联系人待检查",
        "contacts.count.backups": "%d 个备份", "contacts.count": "%d 个联系人",
        "contacts.noName": "无姓名", "contacts.noNumber": "无号码", "contacts.unknown": "未知",
        "contacts.selectAll": "全选", "contacts.deselectAll": "取消全选", "contacts.selectGroup": "选择分组",
        "contacts.deleteSelected": "删除所选", "contacts.deleteN": "删除所选 %d 项",
        "contacts.dup.title": "重复联系人", "contacts.dup.scanning": "正在扫描重复项…",
        "contacts.dup.emptyTitle": "未找到重复项", "contacts.dup.emptyBody": "你的联系人很干净。",
        "contacts.dup.groupCount": "%d 个重复联系人", "contacts.dup.merge": "合并联系人",
        "contacts.inc.title": "不完整联系人", "contacts.inc.missingName": "缺少姓名",
        "contacts.inc.missingPhone": "缺少号码", "contacts.inc.missingBoth": "缺少姓名和号码",
        "contacts.inc.edit": "编辑联系人", "contacts.inc.emptyTitle": "所有联系人都完整",
        "contacts.inc.unnamed": "未命名联系人",
        "contacts.all.title": "所有联系人", "contacts.all.search": "搜索联系人",
        "contacts.backups.title": "备份", "contacts.backups.count": "%d 个备份", "contacts.backups.create": "创建备份",
        "contacts.backups.item": "备份", "contacts.backups.restore": "恢复 %d 个联系人", "contacts.backups.delete": "删除备份",
        "contacts.backups.errorTitle": "备份出错", "contacts.backups.restoredTitle": "已恢复",
        "contacts.backups.backing": "正在备份联系人…", "contacts.backups.emptyTitle": "暂无备份",
        "contacts.backups.emptyBody": "点按创建备份，将每个联系人保存为本设备上的 vCard 文件。",
        "contacts.backups.restoredMsg": "已恢复 %d 个联系人",
        "contacts.permTitle": "需要通讯录访问权限",
        "contacts.permBody": "应用读取你的通讯录，以查找重复项、不完整条目并安全备份。",
        "contacts.somethingWrong": "出了点问题",
        "contact.title": "联系我们", "contact.hero": "联系我们",
        "contact.intro": "我们很想听到你的声音。给我们留言，我们会尽快回复。",
        "contact.name": "姓名", "contact.namePh": "输入你的姓名", "contact.email": "电子邮件",
        "contact.emailPh": "输入你的邮箱", "contact.message": "你的留言", "contact.send": "发送留言",
        "contact.errorTitle": "无法发送", "contact.noMail": "未配置邮件账户。请直接发邮件至 %@。",
    ]

    private static let zhHant: [String: String] = [
        "contacts.card.duplicates": "重複", "contacts.card.incomplete": "不完整聯絡人",
        "contacts.card.backup": "備份", "contacts.card.all": "所有聯絡人",
        "contacts.desc.duplicates": "合併或刪除重複項…", "contacts.desc.incomplete": "缺少姓名、電話的聯絡人…",
        "contacts.desc.backup": "在需要時備份與還原聯絡人…", "contacts.desc.all": "查看裝置上的所有聯絡人。",
        "contacts.count.duplicates": "%d 個重複群組", "contacts.count.incomplete": "%d 位聯絡人待檢查",
        "contacts.count.backups": "%d 個備份", "contacts.count": "%d 位聯絡人",
        "contacts.noName": "無姓名", "contacts.noNumber": "無號碼", "contacts.unknown": "未知",
        "contacts.selectAll": "全選", "contacts.deselectAll": "取消全選", "contacts.selectGroup": "選擇群組",
        "contacts.deleteSelected": "刪除所選", "contacts.deleteN": "刪除所選 %d 項",
        "contacts.dup.title": "重複聯絡人", "contacts.dup.scanning": "正在掃描重複項…",
        "contacts.dup.emptyTitle": "找不到重複項", "contacts.dup.emptyBody": "你的聯絡人很乾淨。",
        "contacts.dup.groupCount": "%d 位重複聯絡人", "contacts.dup.merge": "合併聯絡人",
        "contacts.inc.title": "不完整聯絡人", "contacts.inc.missingName": "缺少姓名",
        "contacts.inc.missingPhone": "缺少號碼", "contacts.inc.missingBoth": "缺少姓名與號碼",
        "contacts.inc.edit": "編輯聯絡人", "contacts.inc.emptyTitle": "所有聯絡人都完整",
        "contacts.inc.unnamed": "未命名聯絡人",
        "contacts.all.title": "所有聯絡人", "contacts.all.search": "搜尋聯絡人",
        "contacts.backups.title": "備份", "contacts.backups.count": "%d 個備份", "contacts.backups.create": "建立備份",
        "contacts.backups.item": "備份", "contacts.backups.restore": "還原 %d 位聯絡人", "contacts.backups.delete": "刪除備份",
        "contacts.backups.errorTitle": "備份錯誤", "contacts.backups.restoredTitle": "已還原",
        "contacts.backups.backing": "正在備份聯絡人…", "contacts.backups.emptyTitle": "尚無備份",
        "contacts.backups.emptyBody": "點按建立備份，將每位聯絡人儲存為本裝置上的 vCard 檔案。",
        "contacts.backups.restoredMsg": "已還原 %d 位聯絡人",
        "contacts.permTitle": "需要聯絡人存取權限",
        "contacts.permBody": "應用程式讀取你的聯絡人，以尋找重複項、不完整項目並安全備份。",
        "contacts.somethingWrong": "發生錯誤",
        "contact.title": "聯絡我們", "contact.hero": "聯絡我們",
        "contact.intro": "我們很想聽到你的意見。傳訊息給我們，我們會盡快回覆。",
        "contact.name": "姓名", "contact.namePh": "輸入你的姓名", "contact.email": "電子郵件",
        "contact.emailPh": "輸入你的電子郵件", "contact.message": "你的訊息", "contact.send": "傳送訊息",
        "contact.errorTitle": "無法傳送", "contact.noMail": "未設定郵件帳號。請直接寄信至 %@。",
    ]
}
