import Foundation

// Translation table: [languageKey: [stringKey: value]]. Language keys come from
// Localizer.langKey(for:) and cover every entry in the in-app picker. Each language
// is a separate explicitly-typed constant so the Swift type-checker stays fast
// (one giant nested literal compiles very slowly). Missing keys fall back to English.
//
// Covered: Tab bar, Language, Settings, Home, Compress. Add more screens by adding
// keys to every language constant below.
enum LocalizedStrings {
    static let table: [String: [String: String]] = [
        "en": en, "es": es, "pt": pt, "fr": fr, "de": de, "it": it, "nl": nl,
        "tr": tr, "uk": uk, "ru": ru, "he": he, "ar": ar, "fa": fa, "id": id,
        "vi": vi, "ja": ja, "ko": ko, "zh-Hans": zhHans, "zh-Hant": zhHant,
    ]

    private static let en: [String: String] = [
        "tab.home": "Home", "tab.vault": "Vault", "tab.contacts": "Contacts", "tab.compress": "Compress",
        "lang.title": "Language", "lang.selected": "Selected", "lang.all": "All language",
        "lang.search": "Enter name of Language...", "lang.start": "Let’s Start",
        "settings.title": "Settings", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "Instantly Detect Similar Photos", "settings.feature.noads": "No Ads and Limits",
        "settings.feature.storage": "Save Both Storage & Time", "settings.getPremium": "Get Premium",
        "settings.stayInTouch": "Stay in Touch", "settings.share": "Share Cleanup", "settings.rate": "Rate Us",
        "settings.language": "Language", "settings.support": "Support", "settings.faq": "FAQ",
        "settings.contact": "Contact Us", "settings.restore": "Restore Purchase",
        "settings.terms": "Terms of Service", "settings.privacy": "Privacy Policy",
        "common.delete": "Delete", "common.cancel": "Cancel", "common.great": "Great!", "common.openSettings": "Open Settings",
        "home.storage": "Your Storage", "home.quickClean": "Quick Clean (%@)", "home.reviewGroup": "Review Group",
        "home.bestMatch": "Best Match", "home.photos": "%d Photos", "home.videos": "%d Videos",
        "home.tapToScan": "Tap to scan", "home.scanning": "Scanning…",
        "home.cat.similar": "Similar", "home.cat.duplicates": "Duplicates",
        "home.cat.similarScreenshots": "Similar Screenshots", "home.cat.similarVideos": "Similar Videos",
        "home.cat.otherScreenshots": "Other Screenshots", "home.cat.chatPhotos": "Chat Photos",
        "home.cat.videosOrganizer": "Videos Organizer", "home.cat.other": "Other",
        "compress.title": "Compress", "compress.videosCount": "%d Videos", "compress.noVideos": "No videos found",
        "compress.sortBy": "Sort by", "compress.sortNewest": "Newest", "compress.sortLargest": "Largest", "compress.sortLongest": "Longest",
        "compress.downloadingICloud": "Downloading from iCloud… %d%%",
        "compress.permTitle": "Photos access required",
        "compress.permBody": "Allow access so the app can list your videos to compress.",
        "compress.videoCompress": "Video Compress", "compress.selectedFile": "Selected File",
        "compress.changeFile": "Change File", "compress.quality": "Compression Quality",
        "compress.qBest": "Best Quality", "compress.qBalanced": "Balanced", "compress.qSavings": "Maximum Savings",
        "compress.qBestSub": "Up to 1080p — best quality", "compress.qBalancedSub": "Up to 720p — recommended for sharing",
        "compress.qSavingsSub": "Up to 540p — smallest file", "compress.recommended": "Recommended",
        "compress.potentialSavings": "POTENTIAL SAVINGS", "compress.original": "ORIGINAL", "compress.estimated": "ESTIMATED",
        "compress.start": "Start Compression", "compress.confirmTitle": "Confirm Compression?",
        "compress.confirmBody": "The video will be compressed. You will save %@ of storage.",
        "compress.todaysUses": "Today’s uses: %d/%d", "compress.compressNow": "Compress Now",
        "compress.compressing": "Compressing your video…", "compress.cancelProcess": "Cancel Process",
        "compress.cancelTitle": "Are you sure?",
        "compress.cancelBody": "Do you really want to cancel the current process? Any unsaved progress will be lost.",
        "compress.yesCancel": "Yes, Cancel", "compress.noGoBack": "No, Go Back",
        "compress.complete": "Compression Complete!", "compress.compressed": "COMPRESSED",
        "compress.savedPct": "SAVED %d%%", "compress.replaceOriginal": "Replace Original", "compress.keepBoth": "Keep Both",
        "compress.qualityNote": "The video quality has been preserved while reducing the file size by half.",
        "compress.notification": "Notification", "compress.successTitle": "Successfully Compressed!",
        "compress.successBody": "Your file has been fully optimized to save storage space without losing quality.",
        "compress.saved": "SAVED", "compress.cleared": "CLEARED", "compress.fileDetails": "File Details",
        "compress.originalSize": "Original Size", "compress.newSize": "New Size",
        "compress.errorTitle": "Compress error", "compress.errorOpen": "Couldn’t open this video.",
    ]

    private static let es: [String: String] = [
        "tab.home": "Inicio", "tab.vault": "Bóveda", "tab.contacts": "Contactos", "tab.compress": "Comprimir",
        "lang.title": "Idioma", "lang.selected": "Seleccionado", "lang.all": "Todos los idiomas",
        "lang.search": "Escribe el nombre del idioma...", "lang.start": "Comenzar",
        "settings.title": "Ajustes", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "Detecta fotos similares al instante", "settings.feature.noads": "Sin anuncios ni límites",
        "settings.feature.storage": "Ahorra almacenamiento y tiempo", "settings.getPremium": "Obtener Premium",
        "settings.stayInTouch": "Mantente en contacto", "settings.share": "Compartir la app", "settings.rate": "Califícanos",
        "settings.language": "Idioma", "settings.support": "Soporte", "settings.faq": "FAQ",
        "settings.contact": "Contáctanos", "settings.restore": "Restaurar compra",
        "settings.terms": "Términos del servicio", "settings.privacy": "Política de privacidad",
        "common.delete": "Eliminar", "common.cancel": "Cancelar", "common.great": "¡Genial!", "common.openSettings": "Abrir Ajustes",
        "home.storage": "Tu almacenamiento", "home.quickClean": "Limpieza rápida (%@)", "home.reviewGroup": "Revisar grupo",
        "home.bestMatch": "Mejor opción", "home.photos": "%d fotos", "home.videos": "%d videos",
        "home.tapToScan": "Toca para escanear",
        "home.cat.similar": "Similares", "home.cat.duplicates": "Duplicados",
        "home.cat.similarScreenshots": "Capturas similares", "home.cat.similarVideos": "Videos similares",
        "home.cat.otherScreenshots": "Otras capturas", "home.cat.chatPhotos": "Fotos de chats",
        "home.cat.videosOrganizer": "Organizar videos", "home.cat.other": "Otros",
        "compress.title": "Comprimir", "compress.videosCount": "%d videos", "compress.noVideos": "No se encontraron videos",
        "compress.permTitle": "Se requiere acceso a Fotos",
        "compress.permBody": "Permite el acceso para que la app muestre tus videos para comprimir.",
        "compress.videoCompress": "Comprimir video", "compress.selectedFile": "Archivo seleccionado",
        "compress.changeFile": "Cambiar archivo", "compress.quality": "Calidad de compresión",
        "compress.qBest": "Mejor calidad", "compress.qBalanced": "Equilibrada", "compress.qSavings": "Máximo ahorro",
        "compress.qBestSub": "Hasta 1080p — mejor calidad", "compress.qBalancedSub": "Hasta 720p — ideal para compartir",
        "compress.qSavingsSub": "Hasta 540p — archivo más pequeño", "compress.recommended": "Recomendado",
        "compress.potentialSavings": "AHORRO POSIBLE", "compress.original": "ORIGINAL", "compress.estimated": "ESTIMADO",
        "compress.start": "Iniciar compresión", "compress.confirmTitle": "¿Confirmar compresión?",
        "compress.confirmBody": "El video se comprimirá. Ahorrarás %@ de almacenamiento.",
        "compress.todaysUses": "Usos de hoy: %d/%d", "compress.compressNow": "Comprimir ahora",
        "compress.compressing": "Comprimiendo tu video…", "compress.cancelProcess": "Cancelar proceso",
        "compress.cancelTitle": "¿Estás seguro?",
        "compress.cancelBody": "¿Seguro que quieres cancelar el proceso actual? Se perderá el progreso no guardado.",
        "compress.yesCancel": "Sí, cancelar", "compress.noGoBack": "No, volver",
        "compress.complete": "¡Compresión completa!", "compress.compressed": "COMPRIMIDO",
        "compress.savedPct": "AHORRO %d%%", "compress.replaceOriginal": "Reemplazar original", "compress.keepBoth": "Conservar ambos",
        "compress.qualityNote": "La calidad del video se mantuvo mientras se redujo el tamaño a la mitad.",
        "compress.notification": "Notificación", "compress.successTitle": "¡Comprimido con éxito!",
        "compress.successBody": "Tu archivo se optimizó por completo para ahorrar espacio sin perder calidad.",
        "compress.saved": "AHORRADO", "compress.cleared": "LIBERADO", "compress.fileDetails": "Detalles del archivo",
        "compress.originalSize": "Tamaño original", "compress.newSize": "Tamaño nuevo",
        "compress.errorTitle": "Error de compresión", "compress.errorOpen": "No se pudo abrir este video.",
    ]

    private static let pt: [String: String] = [
        "tab.home": "Início", "tab.vault": "Cofre", "tab.contacts": "Contatos", "tab.compress": "Comprimir",
        "lang.title": "Idioma", "lang.selected": "Selecionado", "lang.all": "Todos os idiomas",
        "lang.search": "Digite o nome do idioma...", "lang.start": "Começar",
        "settings.title": "Configurações", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "Detecte fotos semelhantes na hora", "settings.feature.noads": "Sem anúncios e limites",
        "settings.feature.storage": "Economize armazenamento e tempo", "settings.getPremium": "Obter Premium",
        "settings.stayInTouch": "Fique por dentro", "settings.share": "Compartilhar app", "settings.rate": "Avalie-nos",
        "settings.language": "Idioma", "settings.support": "Suporte", "settings.faq": "FAQ",
        "settings.contact": "Fale conosco", "settings.restore": "Restaurar compra",
        "settings.terms": "Termos de serviço", "settings.privacy": "Política de privacidade",
        "common.delete": "Excluir", "common.cancel": "Cancelar", "common.great": "Ótimo!", "common.openSettings": "Abrir Ajustes",
        "home.storage": "Seu armazenamento", "home.quickClean": "Limpeza rápida (%@)", "home.reviewGroup": "Revisar grupo",
        "home.bestMatch": "Melhor opção", "home.photos": "%d fotos", "home.videos": "%d vídeos",
        "home.tapToScan": "Toque para escanear",
        "home.cat.similar": "Semelhantes", "home.cat.duplicates": "Duplicadas",
        "home.cat.similarScreenshots": "Capturas semelhantes", "home.cat.similarVideos": "Vídeos semelhantes",
        "home.cat.otherScreenshots": "Outras capturas", "home.cat.chatPhotos": "Fotos de conversas",
        "home.cat.videosOrganizer": "Organizar vídeos", "home.cat.other": "Outros",
        "compress.title": "Comprimir", "compress.videosCount": "%d vídeos", "compress.noVideos": "Nenhum vídeo encontrado",
        "compress.permTitle": "Acesso às Fotos necessário",
        "compress.permBody": "Permita o acesso para o app listar seus vídeos para comprimir.",
        "compress.videoCompress": "Comprimir vídeo", "compress.selectedFile": "Arquivo selecionado",
        "compress.changeFile": "Trocar arquivo", "compress.quality": "Qualidade da compressão",
        "compress.qBest": "Melhor qualidade", "compress.qBalanced": "Equilibrada", "compress.qSavings": "Economia máxima",
        "compress.qBestSub": "Até 1080p — melhor qualidade", "compress.qBalancedSub": "Até 720p — ideal para compartilhar",
        "compress.qSavingsSub": "Até 540p — menor arquivo", "compress.recommended": "Recomendado",
        "compress.potentialSavings": "ECONOMIA POSSÍVEL", "compress.original": "ORIGINAL", "compress.estimated": "ESTIMADO",
        "compress.start": "Iniciar compressão", "compress.confirmTitle": "Confirmar compressão?",
        "compress.confirmBody": "O vídeo será comprimido. Você vai economizar %@ de armazenamento.",
        "compress.todaysUses": "Usos de hoje: %d/%d", "compress.compressNow": "Comprimir agora",
        "compress.compressing": "Comprimindo seu vídeo…", "compress.cancelProcess": "Cancelar processo",
        "compress.cancelTitle": "Tem certeza?",
        "compress.cancelBody": "Deseja mesmo cancelar o processo atual? Todo progresso não salvo será perdido.",
        "compress.yesCancel": "Sim, cancelar", "compress.noGoBack": "Não, voltar",
        "compress.complete": "Compressão concluída!", "compress.compressed": "COMPRIMIDO",
        "compress.savedPct": "ECONOMIA %d%%", "compress.replaceOriginal": "Substituir original", "compress.keepBoth": "Manter ambos",
        "compress.qualityNote": "A qualidade do vídeo foi preservada e o tamanho do arquivo reduzido pela metade.",
        "compress.notification": "Notificação", "compress.successTitle": "Comprimido com sucesso!",
        "compress.successBody": "Seu arquivo foi totalmente otimizado para economizar espaço sem perder qualidade.",
        "compress.saved": "ECONOMIA", "compress.cleared": "LIBERADO", "compress.fileDetails": "Detalhes do arquivo",
        "compress.originalSize": "Tamanho original", "compress.newSize": "Novo tamanho",
        "compress.errorTitle": "Erro de compressão", "compress.errorOpen": "Não foi possível abrir este vídeo.",
    ]

    private static let fr: [String: String] = [
        "tab.home": "Accueil", "tab.vault": "Coffre", "tab.contacts": "Contacts", "tab.compress": "Compresser",
        "lang.title": "Langue", "lang.selected": "Sélectionné", "lang.all": "Toutes les langues",
        "lang.search": "Entrez le nom de la langue...", "lang.start": "Commencer",
        "settings.title": "Réglages", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "Détectez les photos similaires instantanément", "settings.feature.noads": "Sans pubs ni limites",
        "settings.feature.storage": "Gagnez du stockage et du temps", "settings.getPremium": "Passer Premium",
        "settings.stayInTouch": "Restez en contact", "settings.share": "Partager l’app", "settings.rate": "Évaluez-nous",
        "settings.language": "Langue", "settings.support": "Assistance", "settings.faq": "FAQ",
        "settings.contact": "Nous contacter", "settings.restore": "Restaurer l’achat",
        "settings.terms": "Conditions d’utilisation", "settings.privacy": "Politique de confidentialité",
        "common.delete": "Supprimer", "common.cancel": "Annuler", "common.great": "Super !", "common.openSettings": "Ouvrir Réglages",
        "home.storage": "Votre stockage", "home.quickClean": "Nettoyage rapide (%@)", "home.reviewGroup": "Vérifier le groupe",
        "home.bestMatch": "Meilleur choix", "home.photos": "%d photos", "home.videos": "%d vidéos",
        "home.tapToScan": "Touchez pour analyser",
        "home.cat.similar": "Similaires", "home.cat.duplicates": "Doublons",
        "home.cat.similarScreenshots": "Captures similaires", "home.cat.similarVideos": "Vidéos similaires",
        "home.cat.otherScreenshots": "Autres captures", "home.cat.chatPhotos": "Photos de discussions",
        "home.cat.videosOrganizer": "Organiser les vidéos", "home.cat.other": "Autres",
        "compress.title": "Compresser", "compress.videosCount": "%d vidéos", "compress.noVideos": "Aucune vidéo trouvée",
        "compress.permTitle": "Accès aux Photos requis",
        "compress.permBody": "Autorisez l’accès pour que l’app liste vos vidéos à compresser.",
        "compress.videoCompress": "Compresser la vidéo", "compress.selectedFile": "Fichier sélectionné",
        "compress.changeFile": "Changer de fichier", "compress.quality": "Qualité de compression",
        "compress.qBest": "Meilleure qualité", "compress.qBalanced": "Équilibrée", "compress.qSavings": "Économie maximale",
        "compress.qBestSub": "Jusqu’à 1080p — meilleure qualité", "compress.qBalancedSub": "Jusqu’à 720p — idéal pour partager",
        "compress.qSavingsSub": "Jusqu’à 540p — fichier le plus léger", "compress.recommended": "Recommandé",
        "compress.potentialSavings": "ÉCONOMIE POSSIBLE", "compress.original": "ORIGINAL", "compress.estimated": "ESTIMÉ",
        "compress.start": "Lancer la compression", "compress.confirmTitle": "Confirmer la compression ?",
        "compress.confirmBody": "La vidéo sera compressée. Vous économiserez %@ de stockage.",
        "compress.todaysUses": "Utilisations du jour : %d/%d", "compress.compressNow": "Compresser",
        "compress.compressing": "Compression de votre vidéo…", "compress.cancelProcess": "Annuler le processus",
        "compress.cancelTitle": "Êtes-vous sûr ?",
        "compress.cancelBody": "Voulez-vous vraiment annuler le processus en cours ? La progression non enregistrée sera perdue.",
        "compress.yesCancel": "Oui, annuler", "compress.noGoBack": "Non, revenir",
        "compress.complete": "Compression terminée !", "compress.compressed": "COMPRESSÉ",
        "compress.savedPct": "ÉCONOMIE %d%%", "compress.replaceOriginal": "Remplacer l’original", "compress.keepBoth": "Garder les deux",
        "compress.qualityNote": "La qualité de la vidéo a été préservée tout en réduisant la taille de moitié.",
        "compress.notification": "Notification", "compress.successTitle": "Compression réussie !",
        "compress.successBody": "Votre fichier a été entièrement optimisé pour gagner de l’espace sans perte de qualité.",
        "compress.saved": "ÉCONOMISÉ", "compress.cleared": "LIBÉRÉ", "compress.fileDetails": "Détails du fichier",
        "compress.originalSize": "Taille d’origine", "compress.newSize": "Nouvelle taille",
        "compress.errorTitle": "Erreur de compression", "compress.errorOpen": "Impossible d’ouvrir cette vidéo.",
    ]

    private static let de: [String: String] = [
        "tab.home": "Start", "tab.vault": "Tresor", "tab.contacts": "Kontakte", "tab.compress": "Komprimieren",
        "lang.title": "Sprache", "lang.selected": "Ausgewählt", "lang.all": "Alle Sprachen",
        "lang.search": "Sprachnamen eingeben...", "lang.start": "Loslegen",
        "settings.title": "Einstellungen", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "Ähnliche Fotos sofort erkennen", "settings.feature.noads": "Keine Werbung und Limits",
        "settings.feature.storage": "Speicher und Zeit sparen", "settings.getPremium": "Premium holen",
        "settings.stayInTouch": "In Kontakt bleiben", "settings.share": "App teilen", "settings.rate": "Bewerten",
        "settings.language": "Sprache", "settings.support": "Support", "settings.faq": "FAQ",
        "settings.contact": "Kontakt", "settings.restore": "Kauf wiederherstellen",
        "settings.terms": "Nutzungsbedingungen", "settings.privacy": "Datenschutzrichtlinie",
        "common.delete": "Löschen", "common.cancel": "Abbrechen", "common.great": "Super!", "common.openSettings": "Einstellungen öffnen",
        "home.storage": "Dein Speicher", "home.quickClean": "Schnellreinigung (%@)", "home.reviewGroup": "Gruppe prüfen",
        "home.bestMatch": "Beste Auswahl", "home.photos": "%d Fotos", "home.videos": "%d Videos",
        "home.tapToScan": "Zum Scannen tippen",
        "home.cat.similar": "Ähnliche", "home.cat.duplicates": "Duplikate",
        "home.cat.similarScreenshots": "Ähnliche Screenshots", "home.cat.similarVideos": "Ähnliche Videos",
        "home.cat.otherScreenshots": "Andere Screenshots", "home.cat.chatPhotos": "Chat-Fotos",
        "home.cat.videosOrganizer": "Videos organisieren", "home.cat.other": "Andere",
        "compress.title": "Komprimieren", "compress.videosCount": "%d Videos", "compress.noVideos": "Keine Videos gefunden",
        "compress.permTitle": "Fotozugriff erforderlich",
        "compress.permBody": "Erlaube den Zugriff, damit die App deine Videos zum Komprimieren auflisten kann.",
        "compress.videoCompress": "Video komprimieren", "compress.selectedFile": "Ausgewählte Datei",
        "compress.changeFile": "Datei ändern", "compress.quality": "Komprimierungsqualität",
        "compress.qBest": "Beste Qualität", "compress.qBalanced": "Ausgewogen", "compress.qSavings": "Maximale Ersparnis",
        "compress.qBestSub": "Bis 1080p — beste Qualität", "compress.qBalancedSub": "Bis 720p — ideal zum Teilen",
        "compress.qSavingsSub": "Bis 540p — kleinste Datei", "compress.recommended": "Empfohlen",
        "compress.potentialSavings": "MÖGLICHE ERSPARNIS", "compress.original": "ORIGINAL", "compress.estimated": "GESCHÄTZT",
        "compress.start": "Komprimierung starten", "compress.confirmTitle": "Komprimierung bestätigen?",
        "compress.confirmBody": "Das Video wird komprimiert. Du sparst %@ Speicher.",
        "compress.todaysUses": "Heutige Nutzungen: %d/%d", "compress.compressNow": "Jetzt komprimieren",
        "compress.compressing": "Video wird komprimiert…", "compress.cancelProcess": "Vorgang abbrechen",
        "compress.cancelTitle": "Bist du sicher?",
        "compress.cancelBody": "Möchtest du den aktuellen Vorgang wirklich abbrechen? Nicht gespeicherter Fortschritt geht verloren.",
        "compress.yesCancel": "Ja, abbrechen", "compress.noGoBack": "Nein, zurück",
        "compress.complete": "Komprimierung abgeschlossen!", "compress.compressed": "KOMPRIMIERT",
        "compress.savedPct": "GESPART %d%%", "compress.replaceOriginal": "Original ersetzen", "compress.keepBoth": "Beide behalten",
        "compress.qualityNote": "Die Videoqualität blieb erhalten, während die Dateigröße halbiert wurde.",
        "compress.notification": "Mitteilung", "compress.successTitle": "Erfolgreich komprimiert!",
        "compress.successBody": "Deine Datei wurde vollständig optimiert, um Speicher zu sparen, ohne Qualität zu verlieren.",
        "compress.saved": "GESPART", "compress.cleared": "FREIGEGEBEN", "compress.fileDetails": "Dateidetails",
        "compress.originalSize": "Ursprüngliche Größe", "compress.newSize": "Neue Größe",
        "compress.errorTitle": "Komprimierungsfehler", "compress.errorOpen": "Dieses Video konnte nicht geöffnet werden.",
    ]

    private static let it: [String: String] = [
        "tab.home": "Home", "tab.vault": "Cassaforte", "tab.contacts": "Contatti", "tab.compress": "Comprimi",
        "lang.title": "Lingua", "lang.selected": "Selezionata", "lang.all": "Tutte le lingue",
        "lang.search": "Inserisci il nome della lingua...", "lang.start": "Inizia",
        "settings.title": "Impostazioni", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "Rileva subito le foto simili", "settings.feature.noads": "Senza pubblicità e limiti",
        "settings.feature.storage": "Risparmia spazio e tempo", "settings.getPremium": "Passa a Premium",
        "settings.stayInTouch": "Resta in contatto", "settings.share": "Condividi l’app", "settings.rate": "Valutaci",
        "settings.language": "Lingua", "settings.support": "Supporto", "settings.faq": "FAQ",
        "settings.contact": "Contattaci", "settings.restore": "Ripristina acquisto",
        "settings.terms": "Termini di servizio", "settings.privacy": "Informativa sulla privacy",
        "common.delete": "Elimina", "common.cancel": "Annulla", "common.great": "Ottimo!", "common.openSettings": "Apri Impostazioni",
        "home.storage": "Il tuo spazio", "home.quickClean": "Pulizia rapida (%@)", "home.reviewGroup": "Rivedi gruppo",
        "home.bestMatch": "Scelta migliore", "home.photos": "%d foto", "home.videos": "%d video",
        "home.tapToScan": "Tocca per scansionare",
        "home.cat.similar": "Simili", "home.cat.duplicates": "Duplicati",
        "home.cat.similarScreenshots": "Screenshot simili", "home.cat.similarVideos": "Video simili",
        "home.cat.otherScreenshots": "Altri screenshot", "home.cat.chatPhotos": "Foto delle chat",
        "home.cat.videosOrganizer": "Organizza video", "home.cat.other": "Altro",
        "compress.title": "Comprimi", "compress.videosCount": "%d video", "compress.noVideos": "Nessun video trovato",
        "compress.permTitle": "Accesso alle Foto richiesto",
        "compress.permBody": "Consenti l’accesso così l’app può elencare i tuoi video da comprimere.",
        "compress.videoCompress": "Comprimi video", "compress.selectedFile": "File selezionato",
        "compress.changeFile": "Cambia file", "compress.quality": "Qualità di compressione",
        "compress.qBest": "Qualità migliore", "compress.qBalanced": "Bilanciata", "compress.qSavings": "Massimo risparmio",
        "compress.qBestSub": "Fino a 1080p — qualità migliore", "compress.qBalancedSub": "Fino a 720p — ideale per condividere",
        "compress.qSavingsSub": "Fino a 540p — file più piccolo", "compress.recommended": "Consigliata",
        "compress.potentialSavings": "RISPARMIO POSSIBILE", "compress.original": "ORIGINALE", "compress.estimated": "STIMATO",
        "compress.start": "Avvia compressione", "compress.confirmTitle": "Confermare la compressione?",
        "compress.confirmBody": "Il video verrà compresso. Risparmierai %@ di spazio.",
        "compress.todaysUses": "Usi di oggi: %d/%d", "compress.compressNow": "Comprimi ora",
        "compress.compressing": "Compressione del video…", "compress.cancelProcess": "Annulla processo",
        "compress.cancelTitle": "Sei sicuro?",
        "compress.cancelBody": "Vuoi davvero annullare il processo in corso? I progressi non salvati andranno persi.",
        "compress.yesCancel": "Sì, annulla", "compress.noGoBack": "No, torna indietro",
        "compress.complete": "Compressione completata!", "compress.compressed": "COMPRESSO",
        "compress.savedPct": "RISPARMIO %d%%", "compress.replaceOriginal": "Sostituisci originale", "compress.keepBoth": "Tieni entrambi",
        "compress.qualityNote": "La qualità del video è stata mantenuta dimezzando la dimensione del file.",
        "compress.notification": "Notifica", "compress.successTitle": "Compresso con successo!",
        "compress.successBody": "Il tuo file è stato ottimizzato per risparmiare spazio senza perdere qualità.",
        "compress.saved": "RISPARMIATO", "compress.cleared": "LIBERATO", "compress.fileDetails": "Dettagli del file",
        "compress.originalSize": "Dimensione originale", "compress.newSize": "Nuova dimensione",
        "compress.errorTitle": "Errore di compressione", "compress.errorOpen": "Impossibile aprire questo video.",
    ]

    private static let nl: [String: String] = [
        "tab.home": "Start", "tab.vault": "Kluis", "tab.contacts": "Contacten", "tab.compress": "Comprimeren",
        "lang.title": "Taal", "lang.selected": "Geselecteerd", "lang.all": "Alle talen",
        "lang.search": "Voer de naam van de taal in...", "lang.start": "Beginnen",
        "settings.title": "Instellingen", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "Vind direct vergelijkbare foto’s", "settings.feature.noads": "Geen advertenties en limieten",
        "settings.feature.storage": "Bespaar opslag en tijd", "settings.getPremium": "Premium halen",
        "settings.stayInTouch": "Blijf in contact", "settings.share": "App delen", "settings.rate": "Beoordeel ons",
        "settings.language": "Taal", "settings.support": "Ondersteuning", "settings.faq": "FAQ",
        "settings.contact": "Contact", "settings.restore": "Aankoop herstellen",
        "settings.terms": "Servicevoorwaarden", "settings.privacy": "Privacybeleid",
        "common.delete": "Verwijderen", "common.cancel": "Annuleren", "common.great": "Top!", "common.openSettings": "Instellingen openen",
        "home.storage": "Jouw opslag", "home.quickClean": "Snel opschonen (%@)", "home.reviewGroup": "Groep bekijken",
        "home.bestMatch": "Beste keuze", "home.photos": "%d foto’s", "home.videos": "%d video’s",
        "home.tapToScan": "Tik om te scannen",
        "home.cat.similar": "Vergelijkbaar", "home.cat.duplicates": "Duplicaten",
        "home.cat.similarScreenshots": "Vergelijkbare schermafbeeldingen", "home.cat.similarVideos": "Vergelijkbare video’s",
        "home.cat.otherScreenshots": "Andere schermafbeeldingen", "home.cat.chatPhotos": "Chatfoto’s",
        "home.cat.videosOrganizer": "Video’s ordenen", "home.cat.other": "Overig",
        "compress.title": "Comprimeren", "compress.videosCount": "%d video’s", "compress.noVideos": "Geen video’s gevonden",
        "compress.permTitle": "Toegang tot Foto’s vereist",
        "compress.permBody": "Geef toegang zodat de app je video’s kan tonen om te comprimeren.",
        "compress.videoCompress": "Video comprimeren", "compress.selectedFile": "Geselecteerd bestand",
        "compress.changeFile": "Bestand wijzigen", "compress.quality": "Compressiekwaliteit",
        "compress.qBest": "Beste kwaliteit", "compress.qBalanced": "Gebalanceerd", "compress.qSavings": "Maximale besparing",
        "compress.qBestSub": "Tot 1080p — beste kwaliteit", "compress.qBalancedSub": "Tot 720p — ideaal om te delen",
        "compress.qSavingsSub": "Tot 540p — kleinste bestand", "compress.recommended": "Aanbevolen",
        "compress.potentialSavings": "MOGELIJKE BESPARING", "compress.original": "ORIGINEEL", "compress.estimated": "GESCHAT",
        "compress.start": "Compressie starten", "compress.confirmTitle": "Compressie bevestigen?",
        "compress.confirmBody": "De video wordt gecomprimeerd. Je bespaart %@ aan opslag.",
        "compress.todaysUses": "Gebruik vandaag: %d/%d", "compress.compressNow": "Nu comprimeren",
        "compress.compressing": "Je video wordt gecomprimeerd…", "compress.cancelProcess": "Proces annuleren",
        "compress.cancelTitle": "Weet je het zeker?",
        "compress.cancelBody": "Wil je het huidige proces echt annuleren? Niet-opgeslagen voortgang gaat verloren.",
        "compress.yesCancel": "Ja, annuleren", "compress.noGoBack": "Nee, terug",
        "compress.complete": "Compressie voltooid!", "compress.compressed": "GECOMPRIMEERD",
        "compress.savedPct": "BESPAARD %d%%", "compress.replaceOriginal": "Origineel vervangen", "compress.keepBoth": "Beide behouden",
        "compress.qualityNote": "De videokwaliteit is behouden terwijl de bestandsgrootte is gehalveerd.",
        "compress.notification": "Melding", "compress.successTitle": "Succesvol gecomprimeerd!",
        "compress.successBody": "Je bestand is volledig geoptimaliseerd om opslag te besparen zonder kwaliteitsverlies.",
        "compress.saved": "BESPAARD", "compress.cleared": "VRIJGEMAAKT", "compress.fileDetails": "Bestandsdetails",
        "compress.originalSize": "Oorspronkelijke grootte", "compress.newSize": "Nieuwe grootte",
        "compress.errorTitle": "Compressiefout", "compress.errorOpen": "Kan deze video niet openen.",
    ]

    private static let tr: [String: String] = [
        "tab.home": "Ana Sayfa", "tab.vault": "Kasa", "tab.contacts": "Kişiler", "tab.compress": "Sıkıştır",
        "lang.title": "Dil", "lang.selected": "Seçili", "lang.all": "Tüm diller",
        "lang.search": "Dil adını girin...", "lang.start": "Başla",
        "settings.title": "Ayarlar", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "Benzer fotoğrafları anında bul", "settings.feature.noads": "Reklam ve sınır yok",
        "settings.feature.storage": "Hem depolama hem zaman kazan", "settings.getPremium": "Premium Al",
        "settings.stayInTouch": "İletişimde kal", "settings.share": "Uygulamayı paylaş", "settings.rate": "Bizi değerlendir",
        "settings.language": "Dil", "settings.support": "Destek", "settings.faq": "FAQ",
        "settings.contact": "Bize ulaşın", "settings.restore": "Satın almayı geri yükle",
        "settings.terms": "Hizmet şartları", "settings.privacy": "Gizlilik politikası",
        "common.delete": "Sil", "common.cancel": "İptal", "common.great": "Harika!", "common.openSettings": "Ayarları aç",
        "home.storage": "Depolaman", "home.quickClean": "Hızlı Temizlik (%@)", "home.reviewGroup": "Grubu incele",
        "home.bestMatch": "En iyi eşleşme", "home.photos": "%d fotoğraf", "home.videos": "%d video",
        "home.tapToScan": "Taramak için dokun",
        "home.cat.similar": "Benzer", "home.cat.duplicates": "Kopyalar",
        "home.cat.similarScreenshots": "Benzer ekran görüntüleri", "home.cat.similarVideos": "Benzer videolar",
        "home.cat.otherScreenshots": "Diğer ekran görüntüleri", "home.cat.chatPhotos": "Sohbet fotoğrafları",
        "home.cat.videosOrganizer": "Videoları düzenle", "home.cat.other": "Diğer",
        "compress.title": "Sıkıştır", "compress.videosCount": "%d video", "compress.noVideos": "Video bulunamadı",
        "compress.permTitle": "Fotoğraf erişimi gerekli",
        "compress.permBody": "Uygulamanın sıkıştırmak için videolarını listeleyebilmesi için erişime izin ver.",
        "compress.videoCompress": "Video sıkıştır", "compress.selectedFile": "Seçilen dosya",
        "compress.changeFile": "Dosyayı değiştir", "compress.quality": "Sıkıştırma kalitesi",
        "compress.qBest": "En iyi kalite", "compress.qBalanced": "Dengeli", "compress.qSavings": "Maksimum tasarruf",
        "compress.qBestSub": "1080p’ye kadar — en iyi kalite", "compress.qBalancedSub": "720p’ye kadar — paylaşım için ideal",
        "compress.qSavingsSub": "540p’ye kadar — en küçük dosya", "compress.recommended": "Önerilen",
        "compress.potentialSavings": "OLASI TASARRUF", "compress.original": "ORİJİNAL", "compress.estimated": "TAHMİNİ",
        "compress.start": "Sıkıştırmayı başlat", "compress.confirmTitle": "Sıkıştırma onaylansın mı?",
        "compress.confirmBody": "Video sıkıştırılacak. %@ depolama tasarruf edeceksin.",
        "compress.todaysUses": "Bugünkü kullanım: %d/%d", "compress.compressNow": "Şimdi sıkıştır",
        "compress.compressing": "Videon sıkıştırılıyor…", "compress.cancelProcess": "İşlemi iptal et",
        "compress.cancelTitle": "Emin misin?",
        "compress.cancelBody": "Mevcut işlemi iptal etmek istediğine emin misin? Kaydedilmemiş ilerleme kaybolacak.",
        "compress.yesCancel": "Evet, iptal et", "compress.noGoBack": "Hayır, geri dön",
        "compress.complete": "Sıkıştırma tamamlandı!", "compress.compressed": "SIKIŞTIRILDI",
        "compress.savedPct": "TASARRUF %d%%", "compress.replaceOriginal": "Orijinali değiştir", "compress.keepBoth": "İkisini de tut",
        "compress.qualityNote": "Dosya boyutu yarıya inerken video kalitesi korundu.",
        "compress.notification": "Bildirim", "compress.successTitle": "Başarıyla sıkıştırıldı!",
        "compress.successBody": "Dosyan, kaliteden ödün vermeden yer kazanmak için tamamen optimize edildi.",
        "compress.saved": "TASARRUF", "compress.cleared": "TEMİZLENDİ", "compress.fileDetails": "Dosya ayrıntıları",
        "compress.originalSize": "Orijinal boyut", "compress.newSize": "Yeni boyut",
        "compress.errorTitle": "Sıkıştırma hatası", "compress.errorOpen": "Bu video açılamadı.",
    ]

    private static let uk: [String: String] = [
        "tab.home": "Головна", "tab.vault": "Сейф", "tab.contacts": "Контакти", "tab.compress": "Стиснути",
        "lang.title": "Мова", "lang.selected": "Вибрано", "lang.all": "Усі мови",
        "lang.search": "Введіть назву мови...", "lang.start": "Почати",
        "settings.title": "Налаштування", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "Миттєво знаходьте схожі фото", "settings.feature.noads": "Без реклами та обмежень",
        "settings.feature.storage": "Заощаджуйте пам’ять і час", "settings.getPremium": "Отримати Premium",
        "settings.stayInTouch": "Залишайтеся на зв’язку", "settings.share": "Поділитися застосунком", "settings.rate": "Оцініть нас",
        "settings.language": "Мова", "settings.support": "Підтримка", "settings.faq": "FAQ",
        "settings.contact": "Зв’язатися з нами", "settings.restore": "Відновити покупку",
        "settings.terms": "Умови використання", "settings.privacy": "Політика конфіденційності",
        "common.delete": "Видалити", "common.cancel": "Скасувати", "common.great": "Чудово!", "common.openSettings": "Відкрити налаштування",
        "home.storage": "Ваше сховище", "home.quickClean": "Швидке очищення (%@)", "home.reviewGroup": "Переглянути групу",
        "home.bestMatch": "Найкращий збіг", "home.photos": "%d фото", "home.videos": "%d відео",
        "home.tapToScan": "Торкніться, щоб сканувати",
        "home.cat.similar": "Схожі", "home.cat.duplicates": "Дублікати",
        "home.cat.similarScreenshots": "Схожі скріншоти", "home.cat.similarVideos": "Схожі відео",
        "home.cat.otherScreenshots": "Інші скріншоти", "home.cat.chatPhotos": "Фото з чатів",
        "home.cat.videosOrganizer": "Упорядкувати відео", "home.cat.other": "Інше",
        "compress.title": "Стиснути", "compress.videosCount": "%d відео", "compress.noVideos": "Відео не знайдено",
        "compress.permTitle": "Потрібен доступ до Фото",
        "compress.permBody": "Надайте доступ, щоб застосунок міг показати ваші відео для стиснення.",
        "compress.videoCompress": "Стиснути відео", "compress.selectedFile": "Вибраний файл",
        "compress.changeFile": "Змінити файл", "compress.quality": "Якість стиснення",
        "compress.qBest": "Найкраща якість", "compress.qBalanced": "Збалансована", "compress.qSavings": "Максимальна економія",
        "compress.qBestSub": "До 1080p — найкраща якість", "compress.qBalancedSub": "До 720p — ідеально для надсилання",
        "compress.qSavingsSub": "До 540p — найменший файл", "compress.recommended": "Рекомендовано",
        "compress.potentialSavings": "МОЖЛИВА ЕКОНОМІЯ", "compress.original": "ОРИГІНАЛ", "compress.estimated": "ОЦІНКА",
        "compress.start": "Почати стиснення", "compress.confirmTitle": "Підтвердити стиснення?",
        "compress.confirmBody": "Відео буде стиснуто. Ви заощадите %@ пам’яті.",
        "compress.todaysUses": "Сьогодні використано: %d/%d", "compress.compressNow": "Стиснути зараз",
        "compress.compressing": "Стиснення вашого відео…", "compress.cancelProcess": "Скасувати процес",
        "compress.cancelTitle": "Ви впевнені?",
        "compress.cancelBody": "Справді скасувати поточний процес? Незбережений прогрес буде втрачено.",
        "compress.yesCancel": "Так, скасувати", "compress.noGoBack": "Ні, назад",
        "compress.complete": "Стиснення завершено!", "compress.compressed": "СТИСНУТО",
        "compress.savedPct": "ЕКОНОМІЯ %d%%", "compress.replaceOriginal": "Замінити оригінал", "compress.keepBoth": "Зберегти обидва",
        "compress.qualityNote": "Якість відео збережено, а розмір файлу зменшено вдвічі.",
        "compress.notification": "Сповіщення", "compress.successTitle": "Успішно стиснуто!",
        "compress.successBody": "Ваш файл повністю оптимізовано, щоб заощадити місце без втрати якості.",
        "compress.saved": "ЗАОЩАДЖЕНО", "compress.cleared": "ЗВІЛЬНЕНО", "compress.fileDetails": "Деталі файлу",
        "compress.originalSize": "Початковий розмір", "compress.newSize": "Новий розмір",
        "compress.errorTitle": "Помилка стиснення", "compress.errorOpen": "Не вдалося відкрити це відео.",
    ]

    private static let ru: [String: String] = [
        "tab.home": "Главная", "tab.vault": "Сейф", "tab.contacts": "Контакты", "tab.compress": "Сжать",
        "lang.title": "Язык", "lang.selected": "Выбрано", "lang.all": "Все языки",
        "lang.search": "Введите название языка...", "lang.start": "Начать",
        "settings.title": "Настройки", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "Мгновенно находите похожие фото", "settings.feature.noads": "Без рекламы и ограничений",
        "settings.feature.storage": "Экономьте память и время", "settings.getPremium": "Получить Premium",
        "settings.stayInTouch": "Оставайтесь на связи", "settings.share": "Поделиться приложением", "settings.rate": "Оцените нас",
        "settings.language": "Язык", "settings.support": "Поддержка", "settings.faq": "FAQ",
        "settings.contact": "Связаться с нами", "settings.restore": "Восстановить покупку",
        "settings.terms": "Условия использования", "settings.privacy": "Политика конфиденциальности",
        "common.delete": "Удалить", "common.cancel": "Отмена", "common.great": "Отлично!", "common.openSettings": "Открыть настройки",
        "home.storage": "Ваше хранилище", "home.quickClean": "Быстрая очистка (%@)", "home.reviewGroup": "Просмотреть группу",
        "home.bestMatch": "Лучший вариант", "home.photos": "%d фото", "home.videos": "%d видео",
        "home.tapToScan": "Коснитесь для сканирования",
        "home.cat.similar": "Похожие", "home.cat.duplicates": "Дубликаты",
        "home.cat.similarScreenshots": "Похожие скриншоты", "home.cat.similarVideos": "Похожие видео",
        "home.cat.otherScreenshots": "Другие скриншоты", "home.cat.chatPhotos": "Фото из чатов",
        "home.cat.videosOrganizer": "Упорядочить видео", "home.cat.other": "Другое",
        "compress.title": "Сжать", "compress.videosCount": "%d видео", "compress.noVideos": "Видео не найдено",
        "compress.permTitle": "Требуется доступ к Фото",
        "compress.permBody": "Разрешите доступ, чтобы приложение показало ваши видео для сжатия.",
        "compress.videoCompress": "Сжать видео", "compress.selectedFile": "Выбранный файл",
        "compress.changeFile": "Изменить файл", "compress.quality": "Качество сжатия",
        "compress.qBest": "Лучшее качество", "compress.qBalanced": "Сбалансированное", "compress.qSavings": "Максимальная экономия",
        "compress.qBestSub": "До 1080p — лучшее качество", "compress.qBalancedSub": "До 720p — удобно делиться",
        "compress.qSavingsSub": "До 540p — наименьший файл", "compress.recommended": "Рекомендуется",
        "compress.potentialSavings": "ВОЗМОЖНАЯ ЭКОНОМИЯ", "compress.original": "ОРИГИНАЛ", "compress.estimated": "ОЦЕНКА",
        "compress.start": "Начать сжатие", "compress.confirmTitle": "Подтвердить сжатие?",
        "compress.confirmBody": "Видео будет сжато. Вы сэкономите %@ памяти.",
        "compress.todaysUses": "Использовано сегодня: %d/%d", "compress.compressNow": "Сжать сейчас",
        "compress.compressing": "Сжатие вашего видео…", "compress.cancelProcess": "Отменить процесс",
        "compress.cancelTitle": "Вы уверены?",
        "compress.cancelBody": "Действительно отменить текущий процесс? Несохранённый прогресс будет потерян.",
        "compress.yesCancel": "Да, отменить", "compress.noGoBack": "Нет, назад",
        "compress.complete": "Сжатие завершено!", "compress.compressed": "СЖАТО",
        "compress.savedPct": "ЭКОНОМИЯ %d%%", "compress.replaceOriginal": "Заменить оригинал", "compress.keepBoth": "Оставить оба",
        "compress.qualityNote": "Качество видео сохранено, а размер файла уменьшен вдвое.",
        "compress.notification": "Уведомление", "compress.successTitle": "Успешно сжато!",
        "compress.successBody": "Ваш файл полностью оптимизирован, чтобы сэкономить место без потери качества.",
        "compress.saved": "СЭКОНОМЛЕНО", "compress.cleared": "ОСВОБОЖДЕНО", "compress.fileDetails": "Сведения о файле",
        "compress.originalSize": "Исходный размер", "compress.newSize": "Новый размер",
        "compress.errorTitle": "Ошибка сжатия", "compress.errorOpen": "Не удалось открыть это видео.",
    ]

    private static let he: [String: String] = [
        "tab.home": "בית", "tab.vault": "כספת", "tab.contacts": "אנשי קשר", "tab.compress": "כיווץ",
        "lang.title": "שפה", "lang.selected": "נבחר", "lang.all": "כל השפות",
        "lang.search": "הזינו שם של שפה...", "lang.start": "בואו נתחיל",
        "settings.title": "הגדרות", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "זיהוי מיידי של תמונות דומות", "settings.feature.noads": "ללא פרסומות והגבלות",
        "settings.feature.storage": "חיסכון באחסון ובזמן", "settings.getPremium": "קבלת פרימיום",
        "settings.stayInTouch": "נשארים בקשר", "settings.share": "שיתוף האפליקציה", "settings.rate": "דרגו אותנו",
        "settings.language": "שפה", "settings.support": "תמיכה", "settings.faq": "FAQ",
        "settings.contact": "צרו קשר", "settings.restore": "שחזור רכישה",
        "settings.terms": "תנאי שימוש", "settings.privacy": "מדיניות פרטיות",
        "common.delete": "מחק", "common.cancel": "ביטול", "common.great": "מצוין!", "common.openSettings": "פתח הגדרות",
        "home.storage": "האחסון שלך", "home.quickClean": "ניקוי מהיר (%@)", "home.reviewGroup": "בדיקת קבוצה",
        "home.bestMatch": "ההתאמה הטובה ביותר", "home.photos": "%d תמונות", "home.videos": "%d סרטונים",
        "home.tapToScan": "הקישו לסריקה",
        "home.cat.similar": "דומות", "home.cat.duplicates": "כפילויות",
        "home.cat.similarScreenshots": "צילומי מסך דומים", "home.cat.similarVideos": "סרטונים דומים",
        "home.cat.otherScreenshots": "צילומי מסך אחרים", "home.cat.chatPhotos": "תמונות מצ׳אטים",
        "home.cat.videosOrganizer": "ארגון סרטונים", "home.cat.other": "אחר",
        "compress.title": "כיווץ", "compress.videosCount": "%d סרטונים", "compress.noVideos": "לא נמצאו סרטונים",
        "compress.permTitle": "נדרשת גישה לתמונות",
        "compress.permBody": "אפשרו גישה כדי שהאפליקציה תוכל להציג את הסרטונים שלכם לכיווץ.",
        "compress.videoCompress": "כיווץ סרטון", "compress.selectedFile": "קובץ נבחר",
        "compress.changeFile": "החלפת קובץ", "compress.quality": "איכות הכיווץ",
        "compress.qBest": "האיכות הטובה ביותר", "compress.qBalanced": "מאוזנת", "compress.qSavings": "חיסכון מרבי",
        "compress.qBestSub": "עד 1080p — האיכות הטובה ביותר", "compress.qBalancedSub": "עד 720p — מצוין לשיתוף",
        "compress.qSavingsSub": "עד 540p — הקובץ הקטן ביותר", "compress.recommended": "מומלץ",
        "compress.potentialSavings": "חיסכון אפשרי", "compress.original": "מקורי", "compress.estimated": "משוער",
        "compress.start": "התחל כיווץ", "compress.confirmTitle": "לאשר כיווץ?",
        "compress.confirmBody": "הסרטון יכווץ. תחסכו %@ של אחסון.",
        "compress.todaysUses": "שימושים היום: %d/%d", "compress.compressNow": "כווץ עכשיו",
        "compress.compressing": "מכווץ את הסרטון שלך…", "compress.cancelProcess": "ביטול התהליך",
        "compress.cancelTitle": "בטוחים?",
        "compress.cancelBody": "האם באמת לבטל את התהליך הנוכחי? כל התקדמות שלא נשמרה תאבד.",
        "compress.yesCancel": "כן, בטל", "compress.noGoBack": "לא, חזרה",
        "compress.complete": "הכיווץ הושלם!", "compress.compressed": "כווץ",
        "compress.savedPct": "נחסך %d%%", "compress.replaceOriginal": "החלף את המקור", "compress.keepBoth": "שמור את שניהם",
        "compress.qualityNote": "איכות הסרטון נשמרה תוך הקטנת גודל הקובץ בחצי.",
        "compress.notification": "התראה", "compress.successTitle": "כווץ בהצלחה!",
        "compress.successBody": "הקובץ שלך עבר אופטימיזציה מלאה כדי לחסוך מקום בלי לאבד איכות.",
        "compress.saved": "נחסך", "compress.cleared": "פונה", "compress.fileDetails": "פרטי הקובץ",
        "compress.originalSize": "גודל מקורי", "compress.newSize": "גודל חדש",
        "compress.errorTitle": "שגיאת כיווץ", "compress.errorOpen": "לא ניתן לפתוח את הסרטון הזה.",
    ]

    private static let ar: [String: String] = [
        "tab.home": "الرئيسية", "tab.vault": "الخزنة", "tab.contacts": "جهات الاتصال", "tab.compress": "ضغط",
        "lang.title": "اللغة", "lang.selected": "المحددة", "lang.all": "كل اللغات",
        "lang.search": "أدخل اسم اللغة...", "lang.start": "لنبدأ",
        "settings.title": "الإعدادات", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "اكتشف الصور المتشابهة فورًا", "settings.feature.noads": "بلا إعلانات ولا قيود",
        "settings.feature.storage": "وفّر المساحة والوقت", "settings.getPremium": "احصل على بريميوم",
        "settings.stayInTouch": "ابقَ على تواصل", "settings.share": "مشاركة التطبيق", "settings.rate": "قيّمنا",
        "settings.language": "اللغة", "settings.support": "الدعم", "settings.faq": "FAQ",
        "settings.contact": "تواصل معنا", "settings.restore": "استعادة الشراء",
        "settings.terms": "شروط الخدمة", "settings.privacy": "سياسة الخصوصية",
        "common.delete": "حذف", "common.cancel": "إلغاء", "common.great": "رائع!", "common.openSettings": "فتح الإعدادات",
        "home.storage": "مساحتك", "home.quickClean": "تنظيف سريع (%@)", "home.reviewGroup": "مراجعة المجموعة",
        "home.bestMatch": "أفضل تطابق", "home.photos": "%d صورة", "home.videos": "%d فيديو",
        "home.tapToScan": "اضغط للفحص",
        "home.cat.similar": "متشابهة", "home.cat.duplicates": "مكررة",
        "home.cat.similarScreenshots": "لقطات شاشة متشابهة", "home.cat.similarVideos": "فيديوهات متشابهة",
        "home.cat.otherScreenshots": "لقطات شاشة أخرى", "home.cat.chatPhotos": "صور المحادثات",
        "home.cat.videosOrganizer": "تنظيم الفيديو", "home.cat.other": "أخرى",
        "compress.title": "ضغط", "compress.videosCount": "%d فيديو", "compress.noVideos": "لا توجد فيديوهات",
        "compress.permTitle": "مطلوب الوصول إلى الصور",
        "compress.permBody": "اسمح بالوصول ليتمكن التطبيق من عرض فيديوهاتك للضغط.",
        "compress.videoCompress": "ضغط الفيديو", "compress.selectedFile": "الملف المحدد",
        "compress.changeFile": "تغيير الملف", "compress.quality": "جودة الضغط",
        "compress.qBest": "أفضل جودة", "compress.qBalanced": "متوازنة", "compress.qSavings": "أقصى توفير",
        "compress.qBestSub": "حتى 1080p — أفضل جودة", "compress.qBalancedSub": "حتى 720p — مثالي للمشاركة",
        "compress.qSavingsSub": "حتى 540p — أصغر ملف", "compress.recommended": "موصى به",
        "compress.potentialSavings": "التوفير المحتمل", "compress.original": "الأصل", "compress.estimated": "تقديري",
        "compress.start": "بدء الضغط", "compress.confirmTitle": "تأكيد الضغط؟",
        "compress.confirmBody": "سيتم ضغط الفيديو. ستوفّر %@ من المساحة.",
        "compress.todaysUses": "استخدامات اليوم: %d/%d", "compress.compressNow": "اضغط الآن",
        "compress.compressing": "جارٍ ضغط الفيديو…", "compress.cancelProcess": "إلغاء العملية",
        "compress.cancelTitle": "هل أنت متأكد؟",
        "compress.cancelBody": "هل تريد فعلاً إلغاء العملية الحالية؟ سيُفقد أي تقدم غير محفوظ.",
        "compress.yesCancel": "نعم، إلغاء", "compress.noGoBack": "لا، رجوع",
        "compress.complete": "اكتمل الضغط!", "compress.compressed": "مضغوط",
        "compress.savedPct": "وُفّر %d%%", "compress.replaceOriginal": "استبدال الأصل", "compress.keepBoth": "الاحتفاظ بالاثنين",
        "compress.qualityNote": "تم الحفاظ على جودة الفيديو مع تقليل حجم الملف إلى النصف.",
        "compress.notification": "إشعار", "compress.successTitle": "تم الضغط بنجاح!",
        "compress.successBody": "تم تحسين ملفك بالكامل لتوفير المساحة دون فقدان الجودة.",
        "compress.saved": "وُفّر", "compress.cleared": "أُفرغ", "compress.fileDetails": "تفاصيل الملف",
        "compress.originalSize": "الحجم الأصلي", "compress.newSize": "الحجم الجديد",
        "compress.errorTitle": "خطأ في الضغط", "compress.errorOpen": "تعذّر فتح هذا الفيديو.",
    ]

    private static let fa: [String: String] = [
        "tab.home": "خانه", "tab.vault": "گاوصندوق", "tab.contacts": "مخاطبین", "tab.compress": "فشرده‌سازی",
        "lang.title": "زبان", "lang.selected": "انتخاب‌شده", "lang.all": "همه زبان‌ها",
        "lang.search": "نام زبان را وارد کنید...", "lang.start": "شروع کنیم",
        "settings.title": "تنظیمات", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "تشخیص فوری عکس‌های مشابه", "settings.feature.noads": "بدون تبلیغات و محدودیت",
        "settings.feature.storage": "صرفه‌جویی در فضا و زمان", "settings.getPremium": "تهیه نسخه ویژه",
        "settings.stayInTouch": "در ارتباط بمانید", "settings.share": "اشتراک‌گذاری برنامه", "settings.rate": "به ما امتیاز دهید",
        "settings.language": "زبان", "settings.support": "پشتیبانی", "settings.faq": "FAQ",
        "settings.contact": "تماس با ما", "settings.restore": "بازیابی خرید",
        "settings.terms": "شرایط استفاده", "settings.privacy": "سیاست حفظ حریم خصوصی",
        "common.delete": "حذف", "common.cancel": "لغو", "common.great": "عالی!", "common.openSettings": "باز کردن تنظیمات",
        "home.storage": "فضای شما", "home.quickClean": "پاک‌سازی سریع (%@)", "home.reviewGroup": "بررسی گروه",
        "home.bestMatch": "بهترین گزینه", "home.photos": "%d عکس", "home.videos": "%d ویدیو",
        "home.tapToScan": "برای اسکن ضربه بزنید",
        "home.cat.similar": "مشابه", "home.cat.duplicates": "تکراری",
        "home.cat.similarScreenshots": "اسکرین‌شات‌های مشابه", "home.cat.similarVideos": "ویدیوهای مشابه",
        "home.cat.otherScreenshots": "سایر اسکرین‌شات‌ها", "home.cat.chatPhotos": "عکس‌های گفتگو",
        "home.cat.videosOrganizer": "سازمان‌دهی ویدیو", "home.cat.other": "سایر",
        "compress.title": "فشرده‌سازی", "compress.videosCount": "%d ویدیو", "compress.noVideos": "ویدیویی یافت نشد",
        "compress.permTitle": "دسترسی به عکس‌ها لازم است",
        "compress.permBody": "دسترسی را مجاز کنید تا برنامه بتواند ویدیوهای شما را برای فشرده‌سازی فهرست کند.",
        "compress.videoCompress": "فشرده‌سازی ویدیو", "compress.selectedFile": "فایل انتخاب‌شده",
        "compress.changeFile": "تغییر فایل", "compress.quality": "کیفیت فشرده‌سازی",
        "compress.qBest": "بهترین کیفیت", "compress.qBalanced": "متعادل", "compress.qSavings": "حداکثر صرفه‌جویی",
        "compress.qBestSub": "تا 1080p — بهترین کیفیت", "compress.qBalancedSub": "تا 720p — مناسب اشتراک‌گذاری",
        "compress.qSavingsSub": "تا 540p — کوچک‌ترین فایل", "compress.recommended": "پیشنهادی",
        "compress.potentialSavings": "صرفه‌جویی ممکن", "compress.original": "اصلی", "compress.estimated": "تخمینی",
        "compress.start": "شروع فشرده‌سازی", "compress.confirmTitle": "تأیید فشرده‌سازی؟",
        "compress.confirmBody": "ویدیو فشرده می‌شود. شما %@ فضا صرفه‌جویی می‌کنید.",
        "compress.todaysUses": "استفاده‌های امروز: %d/%d", "compress.compressNow": "اکنون فشرده کن",
        "compress.compressing": "در حال فشرده‌سازی ویدیو…", "compress.cancelProcess": "لغو فرایند",
        "compress.cancelTitle": "مطمئنید؟",
        "compress.cancelBody": "واقعاً می‌خواهید فرایند فعلی را لغو کنید؟ هر پیشرفت ذخیره‌نشده از بین می‌رود.",
        "compress.yesCancel": "بله، لغو کن", "compress.noGoBack": "خیر، بازگشت",
        "compress.complete": "فشرده‌سازی کامل شد!", "compress.compressed": "فشرده‌شده",
        "compress.savedPct": "صرفه‌جویی %d%%", "compress.replaceOriginal": "جایگزینی فایل اصلی", "compress.keepBoth": "نگه‌داری هر دو",
        "compress.qualityNote": "کیفیت ویدیو حفظ شد و حجم فایل به نصف کاهش یافت.",
        "compress.notification": "اعلان", "compress.successTitle": "با موفقیت فشرده شد!",
        "compress.successBody": "فایل شما کاملاً بهینه شد تا بدون افت کیفیت در فضا صرفه‌جویی شود.",
        "compress.saved": "صرفه‌جویی", "compress.cleared": "آزادشده", "compress.fileDetails": "جزئیات فایل",
        "compress.originalSize": "اندازه اصلی", "compress.newSize": "اندازه جدید",
        "compress.errorTitle": "خطای فشرده‌سازی", "compress.errorOpen": "باز کردن این ویدیو ممکن نشد.",
    ]

    private static let id: [String: String] = [
        "tab.home": "Beranda", "tab.vault": "Brankas", "tab.contacts": "Kontak", "tab.compress": "Kompres",
        "lang.title": "Bahasa", "lang.selected": "Dipilih", "lang.all": "Semua bahasa",
        "lang.search": "Masukkan nama bahasa...", "lang.start": "Mulai",
        "settings.title": "Pengaturan", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "Deteksi foto serupa secara instan", "settings.feature.noads": "Tanpa iklan dan batasan",
        "settings.feature.storage": "Hemat penyimpanan & waktu", "settings.getPremium": "Dapatkan Premium",
        "settings.stayInTouch": "Tetap terhubung", "settings.share": "Bagikan aplikasi", "settings.rate": "Beri nilai",
        "settings.language": "Bahasa", "settings.support": "Dukungan", "settings.faq": "FAQ",
        "settings.contact": "Hubungi kami", "settings.restore": "Pulihkan pembelian",
        "settings.terms": "Ketentuan layanan", "settings.privacy": "Kebijakan privasi",
        "common.delete": "Hapus", "common.cancel": "Batal", "common.great": "Bagus!", "common.openSettings": "Buka Pengaturan",
        "home.storage": "Penyimpananmu", "home.quickClean": "Pembersihan Cepat (%@)", "home.reviewGroup": "Tinjau grup",
        "home.bestMatch": "Pilihan terbaik", "home.photos": "%d foto", "home.videos": "%d video",
        "home.tapToScan": "Ketuk untuk memindai",
        "home.cat.similar": "Serupa", "home.cat.duplicates": "Duplikat",
        "home.cat.similarScreenshots": "Tangkapan layar serupa", "home.cat.similarVideos": "Video serupa",
        "home.cat.otherScreenshots": "Tangkapan layar lain", "home.cat.chatPhotos": "Foto obrolan",
        "home.cat.videosOrganizer": "Atur video", "home.cat.other": "Lainnya",
        "compress.title": "Kompres", "compress.videosCount": "%d video", "compress.noVideos": "Tidak ada video",
        "compress.permTitle": "Perlu akses Foto",
        "compress.permBody": "Izinkan akses agar aplikasi dapat menampilkan video untuk dikompres.",
        "compress.videoCompress": "Kompres video", "compress.selectedFile": "File terpilih",
        "compress.changeFile": "Ganti file", "compress.quality": "Kualitas kompresi",
        "compress.qBest": "Kualitas terbaik", "compress.qBalanced": "Seimbang", "compress.qSavings": "Hemat maksimum",
        "compress.qBestSub": "Hingga 1080p — kualitas terbaik", "compress.qBalancedSub": "Hingga 720p — ideal untuk berbagi",
        "compress.qSavingsSub": "Hingga 540p — file terkecil", "compress.recommended": "Disarankan",
        "compress.potentialSavings": "POTENSI HEMAT", "compress.original": "ASLI", "compress.estimated": "PERKIRAAN",
        "compress.start": "Mulai kompresi", "compress.confirmTitle": "Konfirmasi kompresi?",
        "compress.confirmBody": "Video akan dikompres. Kamu akan menghemat %@ penyimpanan.",
        "compress.todaysUses": "Penggunaan hari ini: %d/%d", "compress.compressNow": "Kompres sekarang",
        "compress.compressing": "Mengompres videomu…", "compress.cancelProcess": "Batalkan proses",
        "compress.cancelTitle": "Apakah kamu yakin?",
        "compress.cancelBody": "Yakin ingin membatalkan proses saat ini? Kemajuan yang belum disimpan akan hilang.",
        "compress.yesCancel": "Ya, batalkan", "compress.noGoBack": "Tidak, kembali",
        "compress.complete": "Kompresi selesai!", "compress.compressed": "DIKOMPRES",
        "compress.savedPct": "HEMAT %d%%", "compress.replaceOriginal": "Ganti yang asli", "compress.keepBoth": "Simpan keduanya",
        "compress.qualityNote": "Kualitas video dipertahankan sambil memperkecil ukuran file setengahnya.",
        "compress.notification": "Notifikasi", "compress.successTitle": "Berhasil dikompres!",
        "compress.successBody": "File-mu telah dioptimalkan sepenuhnya untuk menghemat ruang tanpa kehilangan kualitas.",
        "compress.saved": "HEMAT", "compress.cleared": "DIBEBASKAN", "compress.fileDetails": "Detail file",
        "compress.originalSize": "Ukuran asli", "compress.newSize": "Ukuran baru",
        "compress.errorTitle": "Galat kompresi", "compress.errorOpen": "Tidak dapat membuka video ini.",
    ]

    private static let vi: [String: String] = [
        "tab.home": "Trang chủ", "tab.vault": "Kho bảo mật", "tab.contacts": "Danh bạ", "tab.compress": "Nén",
        "lang.title": "Ngôn ngữ", "lang.selected": "Đã chọn", "lang.all": "Tất cả ngôn ngữ",
        "lang.search": "Nhập tên ngôn ngữ...", "lang.start": "Bắt đầu",
        "settings.title": "Cài đặt", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "Phát hiện ảnh trùng lặp tức thì", "settings.feature.noads": "Không quảng cáo & giới hạn",
        "settings.feature.storage": "Tiết kiệm dung lượng & thời gian", "settings.getPremium": "Nâng cấp Premium",
        "settings.stayInTouch": "Giữ liên lạc", "settings.share": "Chia sẻ ứng dụng", "settings.rate": "Đánh giá",
        "settings.language": "Ngôn ngữ", "settings.support": "Hỗ trợ", "settings.faq": "FAQ",
        "settings.contact": "Liên hệ", "settings.restore": "Khôi phục giao dịch",
        "settings.terms": "Điều khoản dịch vụ", "settings.privacy": "Chính sách bảo mật",
        "common.delete": "Xóa", "common.cancel": "Hủy", "common.great": "Tuyệt!", "common.openSettings": "Mở Cài đặt",
        "home.storage": "Bộ nhớ của bạn", "home.quickClean": "Dọn nhanh (%@)", "home.reviewGroup": "Xem nhóm",
        "home.bestMatch": "Ảnh tốt nhất", "home.photos": "%d ảnh", "home.videos": "%d video",
        "home.tapToScan": "Chạm để quét",
        "home.cat.similar": "Tương tự", "home.cat.duplicates": "Trùng lặp",
        "home.cat.similarScreenshots": "Ảnh chụp màn hình tương tự", "home.cat.similarVideos": "Video tương tự",
        "home.cat.otherScreenshots": "Ảnh chụp màn hình khác", "home.cat.chatPhotos": "Ảnh từ trò chuyện",
        "home.cat.videosOrganizer": "Sắp xếp video", "home.cat.other": "Khác",
        "compress.title": "Nén", "compress.videosCount": "%d video", "compress.noVideos": "Không tìm thấy video",
        "compress.permTitle": "Cần quyền truy cập Ảnh",
        "compress.permBody": "Cho phép truy cập để ứng dụng hiển thị video của bạn để nén.",
        "compress.videoCompress": "Nén video", "compress.selectedFile": "Tệp đã chọn",
        "compress.changeFile": "Đổi tệp", "compress.quality": "Chất lượng nén",
        "compress.qBest": "Chất lượng tốt nhất", "compress.qBalanced": "Cân bằng", "compress.qSavings": "Tiết kiệm tối đa",
        "compress.qBestSub": "Tối đa 1080p — chất lượng tốt nhất", "compress.qBalancedSub": "Tối đa 720p — phù hợp chia sẻ",
        "compress.qSavingsSub": "Tối đa 540p — tệp nhỏ nhất", "compress.recommended": "Khuyến nghị",
        "compress.potentialSavings": "TIẾT KIỆM ƯỚC TÍNH", "compress.original": "GỐC", "compress.estimated": "ƯỚC TÍNH",
        "compress.start": "Bắt đầu nén", "compress.confirmTitle": "Xác nhận nén?",
        "compress.confirmBody": "Video sẽ được nén. Bạn sẽ tiết kiệm %@ dung lượng.",
        "compress.todaysUses": "Lượt dùng hôm nay: %d/%d", "compress.compressNow": "Nén ngay",
        "compress.compressing": "Đang nén video của bạn…", "compress.cancelProcess": "Hủy tiến trình",
        "compress.cancelTitle": "Bạn có chắc không?",
        "compress.cancelBody": "Bạn có thực sự muốn hủy tiến trình hiện tại? Mọi tiến độ chưa lưu sẽ bị mất.",
        "compress.yesCancel": "Có, hủy", "compress.noGoBack": "Không, quay lại",
        "compress.complete": "Nén hoàn tất!", "compress.compressed": "ĐÃ NÉN",
        "compress.savedPct": "TIẾT KIỆM %d%%", "compress.replaceOriginal": "Thay thế bản gốc", "compress.keepBoth": "Giữ cả hai",
        "compress.qualityNote": "Chất lượng video được giữ nguyên trong khi giảm một nửa dung lượng tệp.",
        "compress.notification": "Thông báo", "compress.successTitle": "Đã nén thành công!",
        "compress.successBody": "Tệp của bạn đã được tối ưu hoàn toàn để tiết kiệm dung lượng mà không giảm chất lượng.",
        "compress.saved": "TIẾT KIỆM", "compress.cleared": "ĐÃ GIẢI PHÓNG", "compress.fileDetails": "Chi tiết tệp",
        "compress.originalSize": "Dung lượng gốc", "compress.newSize": "Dung lượng mới",
        "compress.errorTitle": "Lỗi nén", "compress.errorOpen": "Không thể mở video này.",
    ]

    private static let ja: [String: String] = [
        "tab.home": "ホーム", "tab.vault": "金庫", "tab.contacts": "連絡先", "tab.compress": "圧縮",
        "lang.title": "言語", "lang.selected": "選択中", "lang.all": "すべての言語",
        "lang.search": "言語名を入力...", "lang.start": "はじめる",
        "settings.title": "設定", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "似た写真をすぐに検出", "settings.feature.noads": "広告も制限もなし",
        "settings.feature.storage": "容量も時間も節約", "settings.getPremium": "プレミアムを取得",
        "settings.stayInTouch": "つながる", "settings.share": "アプリを共有", "settings.rate": "評価する",
        "settings.language": "言語", "settings.support": "サポート", "settings.faq": "FAQ",
        "settings.contact": "お問い合わせ", "settings.restore": "購入を復元",
        "settings.terms": "利用規約", "settings.privacy": "プライバシーポリシー",
        "common.delete": "削除", "common.cancel": "キャンセル", "common.great": "完了！", "common.openSettings": "設定を開く",
        "home.storage": "ストレージ", "home.quickClean": "クイッククリーン (%@)", "home.reviewGroup": "グループを確認",
        "home.bestMatch": "ベストマッチ", "home.photos": "%d枚の写真", "home.videos": "%d本の動画",
        "home.tapToScan": "タップしてスキャン",
        "home.cat.similar": "類似", "home.cat.duplicates": "重複",
        "home.cat.similarScreenshots": "類似スクショ", "home.cat.similarVideos": "類似動画",
        "home.cat.otherScreenshots": "その他のスクショ", "home.cat.chatPhotos": "チャットの写真",
        "home.cat.videosOrganizer": "動画を整理", "home.cat.other": "その他",
        "compress.title": "圧縮", "compress.videosCount": "%d本の動画", "compress.noVideos": "動画が見つかりません",
        "compress.permTitle": "写真へのアクセスが必要です",
        "compress.permBody": "圧縮する動画を表示できるよう、アクセスを許可してください。",
        "compress.videoCompress": "動画を圧縮", "compress.selectedFile": "選択したファイル",
        "compress.changeFile": "ファイルを変更", "compress.quality": "圧縮品質",
        "compress.qBest": "最高品質", "compress.qBalanced": "バランス", "compress.qSavings": "最大節約",
        "compress.qBestSub": "最大1080p — 最高品質", "compress.qBalancedSub": "最大720p — 共有に最適",
        "compress.qSavingsSub": "最大540p — 最小ファイル", "compress.recommended": "おすすめ",
        "compress.potentialSavings": "節約見込み", "compress.original": "元", "compress.estimated": "推定",
        "compress.start": "圧縮を開始", "compress.confirmTitle": "圧縮しますか？",
        "compress.confirmBody": "動画を圧縮します。%@の容量を節約できます。",
        "compress.todaysUses": "本日の利用: %d/%d", "compress.compressNow": "今すぐ圧縮",
        "compress.compressing": "動画を圧縮しています…", "compress.cancelProcess": "処理をキャンセル",
        "compress.cancelTitle": "よろしいですか？",
        "compress.cancelBody": "現在の処理を本当にキャンセルしますか？保存していない進行状況は失われます。",
        "compress.yesCancel": "はい、キャンセル", "compress.noGoBack": "いいえ、戻る",
        "compress.complete": "圧縮が完了しました！", "compress.compressed": "圧縮済み",
        "compress.savedPct": "%d%% 節約", "compress.replaceOriginal": "元と置き換える", "compress.keepBoth": "両方を保持",
        "compress.qualityNote": "ファイルサイズを半分に減らしつつ、動画の品質を維持しました。",
        "compress.notification": "通知", "compress.successTitle": "圧縮に成功しました！",
        "compress.successBody": "品質を損なわず容量を節約できるよう、ファイルを完全に最適化しました。",
        "compress.saved": "節約", "compress.cleared": "解放", "compress.fileDetails": "ファイル詳細",
        "compress.originalSize": "元のサイズ", "compress.newSize": "新しいサイズ",
        "compress.errorTitle": "圧縮エラー", "compress.errorOpen": "この動画を開けませんでした。",
    ]

    private static let ko: [String: String] = [
        "tab.home": "홈", "tab.vault": "보관함", "tab.contacts": "연락처", "tab.compress": "압축",
        "lang.title": "언어", "lang.selected": "선택됨", "lang.all": "모든 언어",
        "lang.search": "언어 이름 입력...", "lang.start": "시작하기",
        "settings.title": "설정", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "유사한 사진 즉시 감지", "settings.feature.noads": "광고와 제한 없음",
        "settings.feature.storage": "저장 공간과 시간 절약", "settings.getPremium": "프리미엄 받기",
        "settings.stayInTouch": "소통하기", "settings.share": "앱 공유", "settings.rate": "평가하기",
        "settings.language": "언어", "settings.support": "지원", "settings.faq": "FAQ",
        "settings.contact": "문의하기", "settings.restore": "구매 복원",
        "settings.terms": "서비스 약관", "settings.privacy": "개인정보 처리방침",
        "common.delete": "삭제", "common.cancel": "취소", "common.great": "좋아요!", "common.openSettings": "설정 열기",
        "home.storage": "내 저장 공간", "home.quickClean": "빠른 정리 (%@)", "home.reviewGroup": "그룹 검토",
        "home.bestMatch": "최적 사진", "home.photos": "사진 %d장", "home.videos": "동영상 %d개",
        "home.tapToScan": "탭하여 스캔",
        "home.cat.similar": "유사", "home.cat.duplicates": "중복",
        "home.cat.similarScreenshots": "유사한 스크린샷", "home.cat.similarVideos": "유사한 동영상",
        "home.cat.otherScreenshots": "기타 스크린샷", "home.cat.chatPhotos": "채팅 사진",
        "home.cat.videosOrganizer": "동영상 정리", "home.cat.other": "기타",
        "compress.title": "압축", "compress.videosCount": "동영상 %d개", "compress.noVideos": "동영상이 없습니다",
        "compress.permTitle": "사진 접근 권한 필요",
        "compress.permBody": "압축할 동영상을 표시할 수 있도록 접근을 허용해 주세요.",
        "compress.videoCompress": "동영상 압축", "compress.selectedFile": "선택한 파일",
        "compress.changeFile": "파일 변경", "compress.quality": "압축 품질",
        "compress.qBest": "최고 품질", "compress.qBalanced": "균형", "compress.qSavings": "최대 절약",
        "compress.qBestSub": "최대 1080p — 최고 품질", "compress.qBalancedSub": "최대 720p — 공유에 적합",
        "compress.qSavingsSub": "최대 540p — 가장 작은 파일", "compress.recommended": "추천",
        "compress.potentialSavings": "예상 절약", "compress.original": "원본", "compress.estimated": "예상",
        "compress.start": "압축 시작", "compress.confirmTitle": "압축하시겠어요?",
        "compress.confirmBody": "동영상이 압축됩니다. 저장 공간 %@를 절약합니다.",
        "compress.todaysUses": "오늘 사용: %d/%d", "compress.compressNow": "지금 압축",
        "compress.compressing": "동영상을 압축하는 중…", "compress.cancelProcess": "처리 취소",
        "compress.cancelTitle": "확실해요?",
        "compress.cancelBody": "현재 처리를 정말 취소하시겠어요? 저장되지 않은 진행 내용은 사라집니다.",
        "compress.yesCancel": "예, 취소", "compress.noGoBack": "아니요, 돌아가기",
        "compress.complete": "압축 완료!", "compress.compressed": "압축됨",
        "compress.savedPct": "%d%% 절약", "compress.replaceOriginal": "원본 교체", "compress.keepBoth": "둘 다 유지",
        "compress.qualityNote": "파일 크기를 절반으로 줄이면서 동영상 품질을 유지했습니다.",
        "compress.notification": "알림", "compress.successTitle": "압축 성공!",
        "compress.successBody": "품질 손실 없이 저장 공간을 절약하도록 파일이 완전히 최적화되었습니다.",
        "compress.saved": "절약", "compress.cleared": "확보", "compress.fileDetails": "파일 정보",
        "compress.originalSize": "원본 크기", "compress.newSize": "새 크기",
        "compress.errorTitle": "압축 오류", "compress.errorOpen": "이 동영상을 열 수 없습니다.",
    ]

    private static let zhHans: [String: String] = [
        "tab.home": "首页", "tab.vault": "保险库", "tab.contacts": "通讯录", "tab.compress": "压缩",
        "lang.title": "语言", "lang.selected": "已选择", "lang.all": "所有语言",
        "lang.search": "输入语言名称...", "lang.start": "开始",
        "settings.title": "设置", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "即时检测相似照片", "settings.feature.noads": "无广告无限制",
        "settings.feature.storage": "节省空间和时间", "settings.getPremium": "获取高级版",
        "settings.stayInTouch": "保持联系", "settings.share": "分享应用", "settings.rate": "给我们评分",
        "settings.language": "语言", "settings.support": "支持", "settings.faq": "FAQ",
        "settings.contact": "联系我们", "settings.restore": "恢复购买",
        "settings.terms": "服务条款", "settings.privacy": "隐私政策",
        "common.delete": "删除", "common.cancel": "取消", "common.great": "太好了！", "common.openSettings": "打开设置",
        "home.storage": "你的存储", "home.quickClean": "快速清理 (%@)", "home.reviewGroup": "查看分组",
        "home.bestMatch": "最佳匹配", "home.photos": "%d 张照片", "home.videos": "%d 个视频",
        "home.tapToScan": "点按扫描",
        "home.cat.similar": "相似", "home.cat.duplicates": "重复",
        "home.cat.similarScreenshots": "相似截图", "home.cat.similarVideos": "相似视频",
        "home.cat.otherScreenshots": "其他截图", "home.cat.chatPhotos": "聊天照片",
        "home.cat.videosOrganizer": "整理视频", "home.cat.other": "其他",
        "compress.title": "压缩", "compress.videosCount": "%d 个视频", "compress.noVideos": "未找到视频",
        "compress.permTitle": "需要照片访问权限",
        "compress.permBody": "请允许访问，以便应用列出可压缩的视频。",
        "compress.videoCompress": "压缩视频", "compress.selectedFile": "已选文件",
        "compress.changeFile": "更换文件", "compress.quality": "压缩质量",
        "compress.qBest": "最佳质量", "compress.qBalanced": "均衡", "compress.qSavings": "最大节省",
        "compress.qBestSub": "最高 1080p — 最佳质量", "compress.qBalancedSub": "最高 720p — 适合分享",
        "compress.qSavingsSub": "最高 540p — 文件最小", "compress.recommended": "推荐",
        "compress.potentialSavings": "预计节省", "compress.original": "原始", "compress.estimated": "预计",
        "compress.start": "开始压缩", "compress.confirmTitle": "确认压缩？",
        "compress.confirmBody": "视频将被压缩。你将节省 %@ 存储空间。",
        "compress.todaysUses": "今日使用：%d/%d", "compress.compressNow": "立即压缩",
        "compress.compressing": "正在压缩你的视频…", "compress.cancelProcess": "取消处理",
        "compress.cancelTitle": "确定吗？",
        "compress.cancelBody": "确定要取消当前处理吗？未保存的进度将会丢失。",
        "compress.yesCancel": "是，取消", "compress.noGoBack": "否，返回",
        "compress.complete": "压缩完成！", "compress.compressed": "已压缩",
        "compress.savedPct": "节省 %d%%", "compress.replaceOriginal": "替换原文件", "compress.keepBoth": "两者都保留",
        "compress.qualityNote": "在将文件大小减半的同时保持了视频质量。",
        "compress.notification": "通知", "compress.successTitle": "压缩成功！",
        "compress.successBody": "你的文件已全面优化，在不损失质量的情况下节省空间。",
        "compress.saved": "已节省", "compress.cleared": "已释放", "compress.fileDetails": "文件详情",
        "compress.originalSize": "原始大小", "compress.newSize": "新大小",
        "compress.errorTitle": "压缩错误", "compress.errorOpen": "无法打开此视频。",
    ]

    private static let zhHant: [String: String] = [
        "tab.home": "首頁", "tab.vault": "保險庫", "tab.contacts": "通訊錄", "tab.compress": "壓縮",
        "lang.title": "語言", "lang.selected": "已選擇", "lang.all": "所有語言",
        "lang.search": "輸入語言名稱...", "lang.start": "開始",
        "settings.title": "設定", "settings.ultimate": "Cleaner Ultimate",
        "settings.feature.similar": "即時偵測相似照片", "settings.feature.noads": "無廣告無限制",
        "settings.feature.storage": "節省空間與時間", "settings.getPremium": "取得進階版",
        "settings.stayInTouch": "保持聯絡", "settings.share": "分享應用程式", "settings.rate": "為我們評分",
        "settings.language": "語言", "settings.support": "支援", "settings.faq": "FAQ",
        "settings.contact": "聯絡我們", "settings.restore": "還原購買",
        "settings.terms": "服務條款", "settings.privacy": "隱私權政策",
        "common.delete": "刪除", "common.cancel": "取消", "common.great": "太好了！", "common.openSettings": "開啟設定",
        "home.storage": "你的儲存空間", "home.quickClean": "快速清理 (%@)", "home.reviewGroup": "檢視群組",
        "home.bestMatch": "最佳匹配", "home.photos": "%d 張照片", "home.videos": "%d 個影片",
        "home.tapToScan": "點按掃描",
        "home.cat.similar": "相似", "home.cat.duplicates": "重複",
        "home.cat.similarScreenshots": "相似截圖", "home.cat.similarVideos": "相似影片",
        "home.cat.otherScreenshots": "其他截圖", "home.cat.chatPhotos": "聊天照片",
        "home.cat.videosOrganizer": "整理影片", "home.cat.other": "其他",
        "compress.title": "壓縮", "compress.videosCount": "%d 個影片", "compress.noVideos": "找不到影片",
        "compress.permTitle": "需要照片存取權限",
        "compress.permBody": "請允許存取，讓應用程式列出可壓縮的影片。",
        "compress.videoCompress": "壓縮影片", "compress.selectedFile": "已選檔案",
        "compress.changeFile": "更換檔案", "compress.quality": "壓縮品質",
        "compress.qBest": "最佳品質", "compress.qBalanced": "均衡", "compress.qSavings": "最大節省",
        "compress.qBestSub": "最高 1080p — 最佳品質", "compress.qBalancedSub": "最高 720p — 適合分享",
        "compress.qSavingsSub": "最高 540p — 檔案最小", "compress.recommended": "推薦",
        "compress.potentialSavings": "預計節省", "compress.original": "原始", "compress.estimated": "預計",
        "compress.start": "開始壓縮", "compress.confirmTitle": "確認壓縮？",
        "compress.confirmBody": "影片將被壓縮。你將節省 %@ 儲存空間。",
        "compress.todaysUses": "今日使用：%d/%d", "compress.compressNow": "立即壓縮",
        "compress.compressing": "正在壓縮你的影片…", "compress.cancelProcess": "取消處理",
        "compress.cancelTitle": "確定嗎？",
        "compress.cancelBody": "確定要取消目前的處理嗎？未儲存的進度將會遺失。",
        "compress.yesCancel": "是，取消", "compress.noGoBack": "否，返回",
        "compress.complete": "壓縮完成！", "compress.compressed": "已壓縮",
        "compress.savedPct": "節省 %d%%", "compress.replaceOriginal": "取代原檔", "compress.keepBoth": "兩者都保留",
        "compress.qualityNote": "在將檔案大小減半的同時維持了影片品質。",
        "compress.notification": "通知", "compress.successTitle": "壓縮成功！",
        "compress.successBody": "你的檔案已完整最佳化，在不損失品質的情況下節省空間。",
        "compress.saved": "已節省", "compress.cleared": "已釋放", "compress.fileDetails": "檔案詳情",
        "compress.originalSize": "原始大小", "compress.newSize": "新大小",
        "compress.errorTitle": "壓縮錯誤", "compress.errorOpen": "無法開啟此影片。",
    ]
}
